namespace RadioReport.MammaMRT.Domain.Enums
{
    public enum DiagnosisType : byte
    {
        None = 0,
        FibrocysticChanges = 1,
        SimpleCyst = 2,
        Fibroadenoma = 3,
        LipoidNecrosis = 4,
        OilCyst = 5,
        BreastParenchymaNonSpecific = 6,
        IntramammaryLymphNodes = 7,
        InSituCarcinomaDCIS = 8,
        InSituCarcinomaLCIS = 9,
        RadialScar = 10,
        BreastCarcinomaNotFurtherSpecified = 11,
        InvasiveDuctalBreastCarcinoma = 12,
        Mastitis = 13,
        Abscess = 14,
        Adenoma = 15,
        BenignPhylloidTumor = 16,
        Hamartoma = 17,
        Hemangioma = 18,
        Haematoma = 19,
        PASH = 20,
        Lipoma = 21,
        Scar = 22,
        Seroma = 23,
        ADH = 24,
        Papilloma = 25,
        CystWithSolidComponents = 26,
        InvasiveLobularBreastCarcinoma = 27,
        IntracycticPapillaryCarcinoma = 28,
        InflammatoryCarcinoma = 29,
        InvasivePapillaryCarcinoma = 30,
        MedullaryCarcinoma = 31,
        MucinousCarcinoma = 32,
        MetaplasticCarcinoma = 33,
        MalignantPhylloidTumor = 34,
        Sarcoma = 35,
        Lymphoma = 36,
        BenignLesionNotFurtherDefined = 37,
        MalignantLesionNotFurtherDefined = 38,
        DignityUnclear = 39
    }
}
