namespace RadioReport.PelvisMRT.Domain.Enums.Bladder
{
    public enum BladderDiagnosisType : byte
    {
        None = 0,
        BenignLesionNotFurtherSpecified = 1,
        MalignantLesionNotFurtherSpecified = 2,
        UnclearDignity = 3,
        WallEdema = 4,
        InadequateDistension = 5,
        TrabeculatedBladderPostvesicalObstruction = 6,
        StatusPostTransurethralResectionTUR = 7,
        Cystitis = 8,
        Hematoma = 9,
        Papilloma = 10,
        Granuloma = 11,
        NeurogenicBladder = 12,
        GenitourinarySchistosomiasis = 13,
        Endometriosis = 14,
        RetroperitonealFibrosis = 15,
        PelvicLipomatosis = 16,
        Lymphocele = 17,
        VenousCollaterals = 18,
        Diverticulitis = 19,
        Abscess = 20,
        UrinaryBladderCarcinoma = 21,
        Sarcoma = 22,
        InfiltratedByRectalCarcinoma = 23,
        InfiltratedByUterusOvarianCarcinoma = 24,
        InfiltratedByProstateSeminalVesicleCarcinoma = 25,
        Lipoma = 26,
        HematomaNotFurtherSpecified = 27,
        HematomaAcute = 28,
        HematomaSubacute = 29,
        HematomaChronic = 30,
        Seroma = 31,
        Hibernoma = 32,
        Neurofibromatosis = 33,
        MyositisOssificans = 34,
        SarcomaNotFurtherDefined = 35,
        Liposarcoma = 36,
        Fibrosarcoma = 37,
        PleomorphicUndifferentiatedSarcoma = 38,
        SynovialSarcoma = 39,
        MalignantPeripheralNerveSheathTumorMPNST = 40
    }
}