export enum BonesDiagnosisType {
  None = 'None',
  Chondrosarcoma = 'Chondrosarcoma',
  BoneInfarct = 'BoneInfarct',
  DignityUnclear = 'DignityUnclear',
  OtherLesion = 'OtherLesion',
  Enchondrome = 'Enchondrome',
  Hemangioma = 'Hemangioma',
  SclerosisIslandOrEnostosis = 'SclerosisIslandOrEnostosis',
  IntraossalLipoma = 'IntraossalLipoma',
  IntraosseousCyst = 'IntraosseousCyst',
  FibrousDysplasia = 'FibrousDysplasia',
  AneurysmaticBoneCyst = 'AneurysmaticBoneCyst',
  Osteoidosteom = 'Osteoidosteom',
  Osteochondrome = 'Osteochondrome',
  Chondroblastoma = 'Chondroblastoma',
  BenignLesionNotFurtherClassified = 'BenignLesionNotFurtherClassified',
  EwingSarcoma = 'EwingSarcoma',
  Osteosarcoma = 'Osteosarcoma',
  Osteoblastoma = 'Osteoblastoma',
  GiantCellTumor = 'GiantCellTumor',
  Metastasis = 'Metastasis',
  Lymphoma = 'Lymphoma',
  MultipleMyeloma = 'MultipleMyeloma',
  MalignantLesionNotFurtherClassified = 'MalignantLesionNotFurtherClassified',
  Osteomyelitis = 'Osteomyelitis'
}
