export enum FigoStageDetailsTypeEnum {
  None = 'None',
  IA = 'IA',
  IB = 'IB',
  IB1 = 'IB1',
  IB2 = 'IB2',
  IIA = 'IIA',
  IIA1 = 'IIA1',
  IIA2 = 'IIA2',
  IIB = 'IIB',
  IIIATumorAffectsSerosa = 'IIIATumorAffectsSerosa',
  IIIAInvasionOfTheLowerThird = 'IIIAInvasionOfTheLowerThird',
  IIIBTumorInfiltratesVagina = 'IIIBTumorInfiltratesVagina',
  IIIBInvasionOfThePelvicWall = 'IIIBInvasionOfThePelvicWall',
  IIIC = 'IIIC',
  IIIC1 = 'IIIC1',
  IIIC2 = 'IIIC2',
  IVATumorInfiltratesBladder = 'IVATumorInfiltratesBladder',
  IVAInvasionOfTheBladderOrRectum = 'IVAInvasionOfTheBladderOrRectum',
  IVB = 'IVB'
}
