import { FindingBase } from '@models/shared/finding/finding.base';
import { LesionTypeEnum } from '@enums/pelvisMRT/pelvic-floor/lesion-type.enum';
import { PelvicFloorFindingTypeEnum } from '@enums/pelvisMRT/pelvic-floor/pelvic-floor-finding-type.enum';
import { DescriptionTypeEnum } from '@enums/shared/description-type.enum';
import { PhaseTypeEnum } from '@enums/pelvisMRT/pelvic-floor/phase-type.enum';
import { GradingTypeEnum } from '@enums/pelvisMRT/pelvic-floor/grading-type.enum';
import { SslTypeEnum } from '@enums/pelvisMRT/pelvic-floor/ssl-type.enum';
import { StageTypeEnum } from '@enums/pelvisMRT/pelvic-floor/stage-type.enum';
import { DirectionTypeEnum } from '@enums/shared/direction-type.enum';
import { RectalIntussusceptionTypeEnum } from '@enums/pelvisMRT/pelvic-floor/rectal-intussusception-type.enum';
import { ExpansionLongitudionalTypeEnum } from '@enums/pelvisMRT/pelvic-floor/expansion-longitudional-type.enum';
import { HorizontalExpansionTypeEnum } from '@enums/pelvisMRT/pelvic-floor/horizontal-expansion-type.enum';
import { MlpPositionTypeEnum } from '@enums/pelvisMRT/pelvic-floor/mlp-position-type.enum';

export class PelvicFloorFindingApiModel extends FindingBase {
  findingType: PelvicFloorFindingTypeEnum;
  descriptionType: DescriptionTypeEnum;

  isVaginaLossOfTheHShape: boolean;
  isPosteriorDislocationOfTheVaginaFornix: boolean;
  isBladderSaddlebagSign: boolean;
  isLesionPeriurethralLigament: boolean;
  isLesionPeriurethralLigamentLeft: boolean;
  isLesionPeriurethralLigamentRight: boolean;
  isLesionPeriurethralLigamentSuspicionOf: boolean;
  isLesionParaurethralLigament: boolean;
  isLesionParaurethralLigamentLeft: boolean;
  isLesionParaurethralLigamentRight: boolean;
  isLesionParaurethralLigamentSuspicionOf: boolean;
  isPubourethralLigamentLesion: boolean;
  isPubourethralLigamentLesionLeft: boolean;
  isPubourethralLigamentLesionRight: boolean;
  isPubourethralLigamentLesionSuspicionOf: boolean;
  isSuspicionOn: boolean;
  isLesionOfOuterSphincterMuscle: boolean;
  isOuterSsl: boolean;
  sslOuterType: SslTypeEnum;
  sslLesionOuterSphincterMuscleType: LesionTypeEnum;
  isInnerSphincterLesion: boolean;
  isInnerSsl: boolean;
  sslInnerType: SslTypeEnum;
  sslLesionInnerSphincterMuscleType: LesionTypeEnum;
  isLesionPuborectalisMuscle: boolean;
  puborectalisLesionType: LesionTypeEnum;
  isLesionMPuborectalisRight: boolean;
  isLesionMPuborectalisLeft: boolean;
  isMPuborectalisSuspicionOf: boolean;
  isLesionMIliococcygeusMuscle: boolean;
  mIliococcygeusLesionType: LesionTypeEnum;
  isLesionMPubococygeusRight: boolean;
  isLesionMPubococygeusLeft: boolean;
  isMPubococygeusSuspicionOf: boolean;
  isLesionPubococygeusMuscle: boolean;
  mPubococygeusLesionType: LesionTypeEnum;
  isLesionMIliococcygeusRight: boolean;
  isLesionMIliococcygeusLeft: boolean;
  isMIliococcygeusSuspicionOf: boolean;
  isCystocele: boolean;
  maxCraniocaudalExtensioToPlcInMm: number;
  craniocaudalExtensioToPlcPhaseType: PhaseTypeEnum;
  craniocaudalExtensionInReferenceToMlpInMm: number;
  craniocaudalExtensionInReferenceToMplType: MlpPositionTypeEnum;
  isAnteriorCompartmentOrganVersion: boolean;
  craniocaudalExtensionInReferenceToMlpPhaseType: PhaseTypeEnum;
  isUrethrovesicalJunctionKinking: boolean;
  isAnteriorUrethralAngulation: boolean;
  anteriorUrethralAngulationInDegrees: number;
  isUterineVaginalProlapse: boolean;
  maxMiddleCraniocaudalExtensionToPclInMm: number;
  middleCraniocaudalExtensionToPclPhaseType: PhaseTypeEnum;
  middleCraniocoudalExtensionToMPLInMm: number;
  middleCraniocoudalExtensionMlpPositionType: MlpPositionTypeEnum;
  isMiddleCompartmentOrganVersion: boolean;
  middleCraniocaudalExtensionToMplPhaseType: PhaseTypeEnum;
  isUterineProlapseExceedingGenital: boolean;
  isEversionOfTheVaginalWalls: boolean;
  isHorizontalShiftOfTheVaginalAxis: boolean;
  isEvidenceOfLargeUterusMyoma: boolean;
  isEnterocele: boolean;
  enterocelePhaseType: PhaseTypeEnum;
  isIncarceration: boolean;
  isCulDeSacFailureOfPassage: boolean;
  isPerienericFreeFluid: boolean;
  isPerinealHernia: boolean;
  isPeritoneocele: boolean;
  peritoneocelePhaseType: PhaseTypeEnum;
  isFreeFluid: boolean;
  isEdema: boolean;
  isSigmoidocele: boolean;
  sigmoidocelePhaseType: PhaseTypeEnum;
  isSigmoidoceleIncarceration: boolean;
  isSigmoidoceleFailureOfPassage: boolean;
  isSigmoidocelePerisigmoidalFluid: boolean;
  isAnteriorRectocele: boolean;
  expansionInReferenceToAnteriorRectalWallInMm: number;
  anteriorRectocelePhaseType: PhaseTypeEnum;
  anteriorRectoceleGrading: GradingTypeEnum;
  isIntraluminalCmRetentionAfterDefecation: boolean;
  isPosteriorRectocele: boolean;
  isLateralRectocele: boolean;
  lateralRectoceleDirectionType: DirectionTypeEnum;
  isRectalIntussusception: boolean;
  rectalIntussusceptionType: RectalIntussusceptionTypeEnum;
  longitudinalExpansionType: ExpansionLongitudionalTypeEnum;
  horizontalExpansionType: HorizontalExpansionTypeEnum;
  isPosteriorCompartmentFailureOfPassage: boolean;
  isHiatalExtension: boolean;
  hiatalExtensionInMm: number;
  hiatalExtensionPhaseType: PhaseTypeEnum;
  hiatalExtensionGrading: GradingTypeEnum;
  isDescendingPelvicFloor: boolean;
  descendingPelvicFloorInMm: number;
  descendingPelvicFloorPhaseType: PhaseTypeEnum;
  descendingPelvicFloorGrading: GradingTypeEnum;
  isCaudalAngulationOfLevatorPlate: boolean;
  craniocaudalExtensioToPlcGradingInMm: GradingTypeEnum;
  craniocaudalExtensionInReferenceToMplGradingInMm: StageTypeEnum;
  middleCraniocaudalExtensionToPclGradingInMm: GradingTypeEnum;
  middleCraniocaudalExtensionToMplGradingInMm: StageTypeEnum;
  anteriorRectoceleGradingInMm: GradingTypeEnum;

  // DyssynergicDefecationAnism

  isAnorectalAngle: boolean;
  anorectalAngleAtRestInDegrees: number;
  anorectalAngleWhilePressingInDegrees: number;
  anorectalAngleDuringDefecationInDegrees: number;
  reductionOfTheAnorectalAngleDuringPressing: number;
  openingOfTheAnorectalAngleAtDefecation: number;
  isAbsentPelvicFloorDescentAtDefecation: boolean;
  isEmphasizedPuborectalisMuscle: boolean;
  isDelayedDefecation: boolean;
  isIncreasedIntervalBetweenOpeningAndDefecation: boolean;
  isIncompleteRectalEvacuation: boolean;

  constructor() {
    super();
    this.findingType = PelvicFloorFindingTypeEnum.None;
    this.descriptionType = DescriptionTypeEnum.None;

    this.isVaginaLossOfTheHShape = false;
    this.isPosteriorDislocationOfTheVaginaFornix = false;
    this.isBladderSaddlebagSign = false;
    this.isLesionPeriurethralLigament = false;
    this.isLesionPeriurethralLigamentLeft = false;
    this.isLesionPeriurethralLigamentRight = false;
    this.isLesionPeriurethralLigamentSuspicionOf = false;
    this.isLesionParaurethralLigament = false;
    this.isLesionParaurethralLigamentLeft = false;
    this.isLesionParaurethralLigamentRight = false;
    this.isLesionParaurethralLigamentSuspicionOf = false;
    this.isPubourethralLigamentLesion = false;
    this.isPubourethralLigamentLesionLeft = false;
    this.isPubourethralLigamentLesionRight = false;
    this.isPubourethralLigamentLesionSuspicionOf = false;
    this.isSuspicionOn = false;
    this.isLesionOfOuterSphincterMuscle = false;
    this.isOuterSsl = false;
    this.sslOuterType = SslTypeEnum.None;
    this.sslLesionOuterSphincterMuscleType = LesionTypeEnum.None;
    this.isInnerSphincterLesion = false;
    this.isInnerSsl = false;
    this.sslInnerType = SslTypeEnum.None;
    this.sslLesionInnerSphincterMuscleType = LesionTypeEnum.None;
    this.isLesionPuborectalisMuscle = false;
    this.puborectalisLesionType = LesionTypeEnum.None;
    this.isLesionMPuborectalisRight = false;
    this.isLesionMPuborectalisLeft = false;
    this.isMPuborectalisSuspicionOf = false;
    this.isLesionMIliococcygeusMuscle = false;
    this.mIliococcygeusLesionType = LesionTypeEnum.None;
    this.isLesionMIliococcygeusRight = false;
    this.isLesionMIliococcygeusLeft = false;
    this.isMIliococcygeusSuspicionOf = false;
    this.isLesionPubococygeusMuscle = false;
    this.mPubococygeusLesionType = LesionTypeEnum.None;
    this.isLesionMPubococygeusRight = false;
    this.isLesionMPubococygeusLeft = false;
    this.isMPubococygeusSuspicionOf = false;
    this.isCystocele = false;
    this.maxCraniocaudalExtensioToPlcInMm = null;
    this.craniocaudalExtensioToPlcPhaseType = PhaseTypeEnum.None;
    this.craniocaudalExtensionInReferenceToMlpInMm = null;
    this.craniocaudalExtensionInReferenceToMplType = MlpPositionTypeEnum.None;
    this.isAnteriorCompartmentOrganVersion = false;
    this.craniocaudalExtensionInReferenceToMlpPhaseType = PhaseTypeEnum.None;
    this.isUrethrovesicalJunctionKinking = false;
    this.isAnteriorUrethralAngulation = false;
    this.anteriorUrethralAngulationInDegrees = null;
    this.isUterineVaginalProlapse = false;
    this.maxMiddleCraniocaudalExtensionToPclInMm = null;
    this.middleCraniocaudalExtensionToPclPhaseType = PhaseTypeEnum.None;
    this.middleCraniocoudalExtensionToMPLInMm = null;
    this.middleCraniocoudalExtensionMlpPositionType = MlpPositionTypeEnum.None;
    this.isMiddleCompartmentOrganVersion = false;
    this.middleCraniocaudalExtensionToMplPhaseType = PhaseTypeEnum.None;
    this.isUterineProlapseExceedingGenital = false;
    this.isEversionOfTheVaginalWalls = false;
    this.isHorizontalShiftOfTheVaginalAxis = false;
    this.isEvidenceOfLargeUterusMyoma = false;
    this.isEnterocele = false;
    this.enterocelePhaseType = PhaseTypeEnum.None;
    this.isIncarceration = false;
    this.isCulDeSacFailureOfPassage = false;
    this.isPerienericFreeFluid = false;
    this.isPerinealHernia = false;
    this.isPeritoneocele = false;
    this.peritoneocelePhaseType = PhaseTypeEnum.None;
    this.isFreeFluid = false;
    this.isEdema = false;
    this.isSigmoidocele = false;
    this.sigmoidocelePhaseType = PhaseTypeEnum.None;
    this.isSigmoidoceleIncarceration = false;
    this.isSigmoidoceleFailureOfPassage = false;
    this.isSigmoidocelePerisigmoidalFluid = false;
    this.isAnteriorRectocele = false;
    this.expansionInReferenceToAnteriorRectalWallInMm = null;
    this.anteriorRectocelePhaseType = PhaseTypeEnum.None;
    this.anteriorRectoceleGrading = GradingTypeEnum.None;
    this.isIntraluminalCmRetentionAfterDefecation = false;
    this.isPosteriorRectocele = false;
    this.isLateralRectocele = false;
    this.lateralRectoceleDirectionType = DirectionTypeEnum.None;
    this.isRectalIntussusception = false;
    this.rectalIntussusceptionType = RectalIntussusceptionTypeEnum.None;
    this.longitudinalExpansionType = ExpansionLongitudionalTypeEnum.None;
    this.horizontalExpansionType = HorizontalExpansionTypeEnum.None;
    this.isPosteriorCompartmentFailureOfPassage = false;
    this.isHiatalExtension = false;
    this.hiatalExtensionInMm = null;
    this.hiatalExtensionPhaseType = PhaseTypeEnum.None;
    this.hiatalExtensionGrading = GradingTypeEnum.None;
    this.isDescendingPelvicFloor = false;
    this.descendingPelvicFloorInMm = null;
    this.descendingPelvicFloorPhaseType = PhaseTypeEnum.None;
    this.descendingPelvicFloorGrading = GradingTypeEnum.None;
    this.isCaudalAngulationOfLevatorPlate = false;
    this.craniocaudalExtensioToPlcGradingInMm = GradingTypeEnum.None;
    this.craniocaudalExtensionInReferenceToMplGradingInMm = StageTypeEnum.None;
    this.middleCraniocaudalExtensionToPclGradingInMm = GradingTypeEnum.None;
    this.middleCraniocaudalExtensionToMplGradingInMm = StageTypeEnum.None;
    this.anteriorRectoceleGradingInMm = GradingTypeEnum.None;

    // DyssynergicDefecationAnism

    this.isAnorectalAngle = false;
    this.anorectalAngleAtRestInDegrees = null;
    this.anorectalAngleWhilePressingInDegrees = null;
    this.anorectalAngleDuringDefecationInDegrees = null;
    this.reductionOfTheAnorectalAngleDuringPressing = null;
    this.openingOfTheAnorectalAngleAtDefecation = null;
    this.isAbsentPelvicFloorDescentAtDefecation = false;
    this.isEmphasizedPuborectalisMuscle = false;
    this.isDelayedDefecation = false;
    this.isIncreasedIntervalBetweenOpeningAndDefecation = false;
    this.isIncompleteRectalEvacuation = false;
  }
}
