export enum ClinicTypeEnum {
  None = 'None',
  Headache = 'Headache',
  Vertigo = 'Vertigo',
  VisualDisturbances = 'VisualDisturbances',
  CognitiveChanges = 'CognitiveChanges',
  DisordersOfConsciousness = 'DisordersOfConsciousness',
  SignsOfIncreasedIntracranialPressure = 'SignsOfIncreasedIntracranialPressure',
  SignsOfInflammation = 'SignsOfInflammation',
  MotorDeficit = 'MotorDeficit',
  CranialNerves = 'CranialNerves',
  Dysesthesia = 'Dysesthesia',
  Tremor = 'Tremor',
  Ataxia = 'Ataxia',
  SpeechDisorder = 'SpeechDisorder',
  Dysphagia = 'Dysphagia',
  HearingImpairment = 'HearingImpairment',
  PupilEyelidEyeOrbit = 'PupilEyelidEyeOrbit',
  Nystagmus = 'Nystagmus',
  Sinusitis = 'Sinusitis',
  EndocrineDisorder = 'EndocrineDisorder',
  PsychiatricDisorder = 'PsychiatricDisorder'
}
