import { ThoraxBonesFindingsTypeEnum } from '@enums/thoraxCT/bones/thorax-bones-findings-type.enum';
import { BonesDifferentialDiagnosisTypeEnum } from '@enums/thoraxCT/bones/bones-differential-diagnosis-type.enum';
import { HomogeneityTypeEnum } from '@enums/thoraxCT/bones/homogeneity-type.enum';
import { CorticalBoneTypeEnum } from '@enums/thoraxCT/bones/cortical-bone-type.enum';
import { FormTypeEnum } from '@enums/thoraxCT/bones/form-type.enum';
import { DensityTypeEnum } from '@enums/thoraxCT/bones/density-type.enum';
import { MatrixTypeEnum } from '@enums/thoraxCT/bones/matrix-type.enum';
import { CalcificationTypeEnum } from '@enums/thoraxCT/bones/calcification-type.enum';
import { PeriostealReactionTypeEnum } from '@enums/thoraxCT/bones/periosteal-reaction-type.enum';
import { AdjacentSclerosisTypeEnum } from '@enums/thoraxCT/bones/adjacent-sclerosis-type.enum';
import { FindingBase } from '@models/shared/finding/finding.base';
import { MarginTypeEnum } from '@enums/thoraxCT/common/margin-type.enum';

export class BonesFindingBaseUiModel extends FindingBase {
  findingType: ThoraxBonesFindingsTypeEnum;
  bonesDifferentialDiagnosisType: BonesDifferentialDiagnosisTypeEnum;
  sizeInMm: number;
  secondPlaneInMm: number;
  thirdPlaneInMm: number;
  marginType: MarginTypeEnum;
  homogeneityType: HomogeneityTypeEnum;
  corticalBoneType: CorticalBoneTypeEnum;
  formType: FormTypeEnum;
  densityType: DensityTypeEnum;
  matrixType: MatrixTypeEnum;
  isCalcification: boolean;
  calcificationType: CalcificationTypeEnum;
  isSclerosis: boolean;
  isSepta: boolean;
  isNidus: boolean;
  isPunctiformHyperintens: boolean;
  isFatty: boolean;
  isCystic: boolean;
  isGroundGlassAspect: boolean;
  isLiquidLevel: boolean;
  isExpansion: boolean;
  isOsteolytic: boolean;
  isOsteoblastic: boolean;
  isPermeativeGrowth: boolean;
  isScleroticBorder: boolean;
  isGeographic: boolean;
  isPedunculatedGrowingFromTheEpiphysis: boolean;
  isSubchondral: boolean;
  isInfiltrationOfAdjacentSoftTissue: boolean;
  periostealReactionType: PeriostealReactionTypeEnum;
  isRemodelling: boolean;
  isLamination: boolean;
  isSpiculated: boolean;
  isSunburst: boolean;
  isCodmanTriangle: boolean;
  isAdjacentSclerosis: boolean;
  adjacentSclerosisType: AdjacentSclerosisTypeEnum;
  isDestructionOfEndPlate: boolean;
  isOsteoproliferativeReaction: boolean;
  isBoneApposition: boolean;
  isEdgrenVainoSign: boolean;
  isVertebralHemangioma: boolean;
  isPathologicalFracture: boolean;
  isInvolvingOfThePosteriorWall: boolean;
  isMoreThanOneLesion: boolean;

  constructor() {
    super();
    this.findingType = ThoraxBonesFindingsTypeEnum.None;
    this.bonesDifferentialDiagnosisType = BonesDifferentialDiagnosisTypeEnum.None;
    this.sizeInMm = null;
    this.secondPlaneInMm = null;
    this.thirdPlaneInMm = null;
    this.marginType = MarginTypeEnum.None;
    this.homogeneityType = HomogeneityTypeEnum.None;
    this.corticalBoneType = CorticalBoneTypeEnum.None;
    this.formType = FormTypeEnum.None;
    this.densityType = DensityTypeEnum.None;
    this.matrixType = MatrixTypeEnum.None;
    this.isCalcification = false;
    this.calcificationType = CalcificationTypeEnum.None;
    this.isSclerosis = false;
    this.isSepta = false;
    this.isNidus = false;
    this.isPunctiformHyperintens = false;
    this.isFatty = false;
    this.isCystic = false;
    this.isGroundGlassAspect = false;
    this.isLiquidLevel = false;
    this.isExpansion = false;
    this.isOsteolytic = false;
    this.isOsteoblastic = false;
    this.isPermeativeGrowth = false;
    this.isScleroticBorder = false;
    this.isGeographic = false;
    this.isPedunculatedGrowingFromTheEpiphysis = false;
    this.isSubchondral = false;
    this.isInfiltrationOfAdjacentSoftTissue = false;
    this.periostealReactionType = PeriostealReactionTypeEnum.None;
    this.isRemodelling = false;
    this.isLamination = false;
    this.isSpiculated = false;
    this.isSunburst = false;
    this.isCodmanTriangle = false;
    this.isAdjacentSclerosis = false;
    this.adjacentSclerosisType = AdjacentSclerosisTypeEnum.None;
    this.isDestructionOfEndPlate = false;
    this.isOsteoproliferativeReaction = false;
    this.isBoneApposition = false;
    this.isEdgrenVainoSign = false;
    this.isVertebralHemangioma = false;
    this.isPathologicalFracture = false;
    this.isInvolvingOfThePosteriorWall = false;
    this.isMoreThanOneLesion = false;
  }
}
