namespace RadioReport.NeckMRT.Domain.Enums.Pharynx
{
    public enum DifferentialDiagnosisType : byte
    {
        None = 0,
        BenignLesionNotFurtherSpecified = 1,
        MalignantLesionNotFurtherSpecified = 2,
        DignityUnclear = 3,
        Cephalocele = 4,
        Hyperplasia = 5,
        ChoanalPolyp = 6,
        RathkeSCyst = 7,
        RetentionCyst = 8,
        TornwaldtCyst = 9,
        PharyngealDiverticulum = 10,
        EpidermoidDermoid = 11,
        MalformationLymphatic = 12,
        MalformationVenous = 13,
        Hemangioma = 14,
        EctopicThyroidTissue = 15,
        NasopharyngealCarcinoma = 16,
        OropharyngealCarcinoma = 17,
        HypopharyngealCarcinoma = 18,
        TonsillarCarcinoma = 19,
        Lymphoma = 20,
        LymphNodeMetastasis = 21,
        InflammationAcute = 22,
        InflammationChronic = 23,
        Parotitis = 24,
        Tonsillitis = 25,
        Phlegmon = 26,
        Abscess = 27,
        TonsillarAbscess = 28,
        RetropharyngealAbscess = 29,
        ParapharyngealAbscess = 30,
        ReactiveLymphNodes = 31,
        Epiglottitis = 32,
        InfectiousMononucleosis = 33,
        Thyroiditis = 34,
        NonspecificCysticLesionsOfTheTonsil = 35,
        LymphedemaAfterRadiation = 36,
        LymphedemaAfterSurgery = 37
    }
}
