export enum DifferentialDiagnosisEnum {
  None = 'None',
  Enchondrome = 'Enchondrome',
  Hemangioma = 'Hemangioma',
  SclerosisIslandorEnostosis = 'SclerosisIslandorEnostosis',
  IntraosseousLipoma = 'IntraosseousLipoma',
  IntraosseousCyst = 'IntraosseousCyst',
  BoneInfarction = 'BoneInfarction',
  FibrousDysplasia = 'FibrousDysplasia',
  AneurysmaticBoneCyst = 'AneurysmaticBoneCyst',
  OsteoidOsteoma = 'OsteoidOsteoma',
  Osteochondrome = 'Osteochondrome',
  Chondroblastoma = 'Chondroblastoma',
  Osteoblastoma = 'Osteoblastoma',
  BenignLesionNotFurtherClassified = 'BenignLesionNotFurtherClassified',
  EwingsSarcoma = 'EwingsSarcoma',
  Osteosarcoma = 'Osteosarcoma',
  GiantCellTumor = 'GiantCellTumor',
  Chondrosarcoma = 'Chondrosarcoma',
  Metastasis = 'Metastasis',
  Lymphoma = 'Lymphoma',
  MultipleMyeloma = 'MultipleMyeloma',
  MalignantLesionNotFurtherClassified = 'MalignantLesionNotFurtherClassified',
  Osteomyelitis = 'Osteomyelitis'
}
