export enum DifferentialDiagnoseTypeEnum {
  None = 'None',
  BenignLesionNotSpecified = 'BenignLesionNotSpecified',
  MalignantLesionNotSpecified = 'MalignantLesionNotSpecified',
  DignityUnclear = 'DignityUnclear',
  Enchondroma = 'Enchondroma',
  Hemangioma = 'Hemangioma',
  BoneIsland = 'BoneIsland',
  IntraosseousLipoma = 'IntraosseousLipoma',
  IntraosseeousCyst = 'IntraosseeousCyst',
  FibrousDysplasia = 'FibrousDysplasia',
  AneurysmalBoneCyst = 'AneurysmalBoneCyst',
  OsteoidOsteoma = 'OsteoidOsteoma',
  Osteochondroma = 'Osteochondroma',
  Chondroblastoma = 'Chondroblastoma',
  Osteoblastoma = 'Osteoblastoma',
  BeningGiantCellTumor = 'BeningGiantCellTumor',
  EwingsSarcoma = 'EwingsSarcoma',
  Osteosarcoma = 'Osteosarcoma',
  MalignantGiantCellTumor = 'MalignantGiantCellTumor',
  Chondrosarcoma = 'Chondrosarcoma',
  Metastasis = 'Metastasis',
  Lymphoma = 'Lymphoma',
  MultipleMyeloma = 'MultipleMyeloma',
  Osteomyelitis = 'Osteomyelitis',
  BoneInfarction = 'BoneInfarction'
}
