export enum SoftTissueDifferentialDiagnosisTypeEnum {
  None = 'None',
  BenignLesionNotFurtherSpecified = 'BenignLesionNotFurtherSpecified',
  MalignantLesionNotFurtherSpecified = 'MalignantLesionNotFurtherSpecified',
  DignityUnclear = 'DignityUnclear',
  GanglionCyst = 'GanglionCyst',
  Lipoma = 'Lipoma',
  Hemangioma = 'Hemangioma',
  GlomusTumor = 'GlomusTumor',
  VascularMalformation = 'VascularMalformation',
  Neuroma = 'Neuroma',
  SchwannomaNeurinoma = 'SchwannomaNeurinoma',
  Neurofibroma = 'Neurofibroma',
  EpidermalCyst = 'EpidermalCyst',
  CarpalTunnelFibroma = 'CarpalTunnelFibroma',
  TenosynovialGiantCellTumor = 'TenosynovialGiantCellTumor',
  Pilomatrixoma = 'Pilomatrixoma',
  FibrolipomatousHamartoma = 'FibrolipomatousHamartoma',
  NodularFasciitis = 'NodularFasciitis',
  SoftTissueSarcoma = 'SoftTissueSarcoma',
  SquamousCellCarcinoma = 'SquamousCellCarcinoma',
  MalignantPeripheralNerveSheathTumorMpnst = 'MalignantPeripheralNerveSheathTumorMpnst',
  MalignantMelanoma = 'MalignantMelanoma',
  Metastasis = 'Metastasis',
  PostoperativeScar = 'PostoperativeScar',
  PostoperativeGranulationTissue = 'PostoperativeGranulationTissue'
}
