export enum ClinicalSymptomType {
  None = 'None',
  Headache = 'Headache',
  Vertigo = 'Vertigo',
  VisualDisturbances = 'VisualDisturbances',
  CognitiveChanges = 'CognitiveChanges',
  AlteredStateOfConsciousness = 'AlteredStateOfConsciousness',
  SignsOfIncreasedIntracranialPressure = 'SignsOfIncreasedIntracranialPressure',
  SignsOfInflammation = 'SignsOfInflammation',
  MotorDeficit = 'MotorDeficit',
  Neglect = 'Neglect',
  CranialNerves = 'CranialNerves',
  Dysesthesia = 'Dysesthesia',
  Tremor = 'Tremor',
  Ataxia = 'Ataxia',
  SpeechDisorder = 'SpeechDisorder',
  Dysphagia = 'Dysphagia',
  HearingImpairment = 'HearingImpairment',
  PupilEyelidOrbit = 'PupilEyelidOrbit',
  Nystagmus = 'Nystagmus',
  Sinusitis = 'Sinusitis',
  CentralEndocrineDisorder = 'CentralEndocrineDisorder',
  PsychiatricDisorder = 'PsychiatricDisorder',
  UrinaryIncontinence = 'UrinaryIncontinence',
  SoftTissueHematoma = 'SoftTissueHematoma',
  ScalpLaceration = 'ScalpLaceration'
}
