export enum LocalizationTypeEnum {
  None = 'None',
  AbdominalAorta = 'AbdominalAorta',
  RenalArtery = 'RenalArtery',
  Bifurcation = 'Bifurcation',
  CommonIliacArtery = 'CommonIliacArtery',
  ExternalIliacArtery = 'ExternalIliacArtery',
  InternalIliacArtery = 'InternalIliacArtery',
  CommonFemoralArtery = 'CommonFemoralArtery',
  FemoralBifurcation = 'FemoralBifurcation',
  SuperficialFemoralArtery = 'SuperficialFemoralArtery',
  ProfundaFemoralArtery = 'ProfundaFemoralArtery',
  PoplitealArtery = 'PoplitealArtery',
  AnteriorTibialArtery = 'AnteriorTibialArtery',
  TibioperonealTrunk = 'TibioperonealTrunk',
  PosteriorTibialArtery = 'PosteriorTibialArtery',
  PeronealArtery = 'PeronealArtery',
  DorsalisPedisArtery = 'DorsalisPedisArtery',
  PlantarArchArteries = 'PlantarArchArteries'
}
