export enum CortexLocationsEnum {
  None = 'None',
  FrontalLobeRight = 'FrontalLobeRight',
  SuperiorFrontalGyrusRight = 'SuperiorFrontalGyrusRight',
  MiddleFrontalGyrusRight = 'MiddleFrontalGyrusRight',
  PrecentralGyrusRight = 'PrecentralGyrusRight',
  CentrumSemiovaleRight = 'CentrumSemiovaleRight',
  ParietalLobeRight = 'ParietalLobeRight',
  PostcentralLobeRight = 'PostcentralLobeRight',
  OccipitalLobeRight = 'OccipitalLobeRight',
  InsulaRight = 'InsulaRight',
  TemporalLobeRight = 'TemporalLobeRight',
  HippocampusRight = 'HippocampusRight',
  TemporalPoleRight = 'TemporalPoleRight',
  OperculumRight = 'OperculumRight',
  CerebellumRight = 'CerebellumRight',
  CerebellarHemisphereRight = 'CerebellarHemisphereRight',
  CerebellarTonsilRight = 'CerebellarTonsilRight',
  CerebellarVermisRight = 'CerebellarVermisRight',

  FrontalLobeLeft = 'FrontalLobeLeft',
  SuperiorFrontalGyrusLeft = 'SuperiorFrontalGyrusLeft',
  MiddleFrontalGyrusLeft = 'MiddleFrontalGyrusLeft',
  PrecentralGyrusLeft = 'PrecentralGyrusLeft',
  CentrumSemiovaleLeft = 'CentrumSemiovaleLeft',
  ParietalLobeLeft = 'ParietalLobeLeft',
  PostcentralLobeLeft = 'PostcentralLobeLeft',
  OccipitalLobeLeft = 'OccipitalLobeLeft',
  InsulaLeft = 'InsulaLeft',
  TemporalLobeLeft = 'TemporalLobeLeft',
  HippocampusLeft = 'HippocampusLeft',
  TemporalPoleLeft = 'TemporalPoleLeft',
  OperculumLeft = 'OperculumLeft',
  CerebellumLeft = 'CerebellumLeft',
  CerebellarHemisphereLeft = 'CerebellarHemisphereLeft',
  CerebellarTonsilLeft = 'CerebellarTonsilLeft',
  CerebellarVermisLeft = 'CerebellarVermisLeft'
}
