import { FindingBase } from '@models/shared/finding/finding.base';
import {
  AgeOfTheLesionTypeEnum,
  DifferentialDiagnosisTypeEnum,
  LigamentaLocalisationTypeEnum,
  LigamentaTypeEnum,
  LocalizationTypeEnum,
  PartialRupturetTypeEnum,
  RuptureLocalizationTypeEnum,
  RuptureTypeEnum
} from '@enums/feetMRT/ligaments-and-tendos';
import { AssociatedFindingsTypeEnum } from '@enums/feetMRT/ligaments-and-tendos/associated-findings-type.enum';
import { FootBigTendonsModel } from '@models/feetMRT/ui/localizers/foot-big-tendons.model';
import { LocalizationOfTheTendonRuptureTypeEnum } from '@enums/feetMRT/ligaments-and-tendos/localization-of-the-tendon-rupture-type.enum';

export class LigamentsAndTendonsFindingUiModel extends FindingBase {
  findingType: string;
  ligamentaType: LigamentaTypeEnum;
  ligamentaLocalizationType: LigamentaLocalisationTypeEnum;
  isAnteriorTibiofibularLigament: boolean;
  isPosteriorTibiofibularLigament: boolean;
  isTertiusFracture: boolean;
  isInterosseousTibiofibularLigament: boolean;
  isAnteriorTalofibularLigament: boolean;
  fibulotalareAnteriusLigamnetType: RuptureTypeEnum;
  isCalcaneofibularLigament: boolean;
  isPosteriorTalofibularLigament: boolean;
  isTibionavicularLigament: boolean;
  isAvulsionFractureOfTheMedialMalleolus: boolean;
  isParsTibiocalcaneareBonyAvulsionOnMalleolusMedialis: boolean;
  isTibiocalcanealLigament: boolean;
  isAnteriorTibiotalarLigament: boolean;
  isPosteriorTibiotalarLigament: boolean;
  ageOfTheLesionType: AgeOfTheLesionTypeEnum;
  isSoftTissueHematoma: boolean;
  isScarTissue: boolean;
  isInferoplantarLongitudinalLigament: boolean;
  isMedioplantarObliqueLigament: boolean;
  isSuperomedialCalcaneonavicularLigament: boolean;
  ruptureType: RuptureTypeEnum;
  partialRuptureType: PartialRupturetTypeEnum;
  isIncreasedT2Signal: boolean;
  isWithRetraction: boolean;
  isTalocalcanealLigamentRupture: boolean;
  isCervicalLigamentRupture: boolean;
  isTalocalcanealInterosseouseLigamentRupture: boolean;
  isTarsalSinusFatEdema: boolean;
  isGanglion: boolean;
  diameterInMm: number;
  isCalcaneonavicularLigament: boolean;
  isCalcaneocuboidalLigament: boolean;
  isOsseousAvulsionFracture: boolean;
  isAnteriorProcessOfTheCalcaneus: boolean;
  isLongPlantarLigament: boolean;
  isShortPlantarLigament: boolean;
  isTendinopathy: boolean;
  isThickening: boolean;
  localizationType: LocalizationTypeEnum;
  distanceFromTuberCalcanei: number;
  isRetrocalcanealSubachillealBursitis: boolean;
  isIntrinsicCalcification: boolean;
  isIntratendinousSoftTissueFoci: boolean;
  isHypervascularizationTheTendon: boolean;
  isOsteitisOnTheTuberCalcanei: boolean;
  isHaglundDeformity: boolean;
  isDorsalHeelSpur: boolean;
  isPeritendinousEdema: boolean;
  isEdemaInKagerFatPad: boolean;
  differentialDiagnosisType: DifferentialDiagnosisTypeEnum;
  isTear: boolean;
  retractionInMm: number;
  ruptureLocalizationType: RuptureLocalizationTypeEnum;
  longitudinalExpansionTheLesionInMm: number;
  associatedFindingsType: AssociatedFindingsTypeEnum;
  isPeritendinitis: boolean;
  isOsPeroneum: boolean;
  isTendovaginitis: boolean;
  isContactWithOsteosynthesisMaterial: boolean;
  isFluidInTendonSheath: boolean;
  isOsTrigonumSyndrome: boolean;
  isAccompanyingBoneMarrowEdema: boolean;
  isPesPlanumDeformity: boolean;
  isT2wPDHyperintensity: boolean;
  isT1wHyperintensity: boolean;
  isConvexAnteriorContour: boolean;
  isFusiformContour: boolean;
  isCalcifyingTendinitis: boolean;
  isIntratendinousSoftTissueIntensive: boolean;
  isTendonHypervascularisation: boolean;
  isOsteitisOfTheTuber: boolean;
  isLongitudinalTear: boolean;
  isReRupture: boolean;
  isFluidInTheCommonTendonSheathOfThePeronealTendons: boolean;
  isMPeroneusLongusTendon: boolean;
  isFluidInTheTendonSheathDistalToTheLateralMalleolus: boolean;
  isGanglionAtTheLevelOfTheInsertionAtOsMetatarsalD1OsCuboideum: boolean;
  isTendonDislocation: boolean;
  isTendovaginitisDueToOsteophyteAtDorsomedialDistalTibia: boolean;
  isAfterHalluxValgusSurgery: boolean;
  isAnkleJointEffusion: boolean;
  isGanglionToInsertionBaseDistalPhalanxD1: boolean;
  isOsTibialAccessorium: boolean;
  isPseudotumorOnTheBackOfTheFoot: boolean;
  localizationOfTendonRuptureType: LocalizationOfTheTendonRuptureTypeEnum;
  maxExtentInCrossSectionInPercent: number;
  craniocaudaleExtensionInMm: number;
  sizeInMm: number;
  maxSagittalDiameterInMm: number;
  distanceToTuberCalcaneiInMm: number;
  extraarticularLocalizationType: FootBigTendonsModel;

  constructor() {
    super();
    this.findingType = 'None';
    this.ligamentaType = LigamentaTypeEnum.None;
    this.ligamentaLocalizationType = LigamentaLocalisationTypeEnum.None;
    this.isAnteriorTibiofibularLigament = false;
    this.isPosteriorTibiofibularLigament = false;
    this.isTertiusFracture = false;
    this.isInterosseousTibiofibularLigament = false;
    this.isAnteriorTalofibularLigament = false;
    this.fibulotalareAnteriusLigamnetType = RuptureTypeEnum.None;
    this.isCalcaneofibularLigament = false;
    this.isPosteriorTalofibularLigament = false;
    this.isTibionavicularLigament = false;
    this.isAvulsionFractureOfTheMedialMalleolus = false;
    this.isParsTibiocalcaneareBonyAvulsionOnMalleolusMedialis = false;
    this.isTibiocalcanealLigament = false;
    this.isAnteriorTibiotalarLigament = false;
    this.isPosteriorTibiotalarLigament = false;
    this.ageOfTheLesionType = AgeOfTheLesionTypeEnum.None;
    this.isSoftTissueHematoma = false;
    this.isScarTissue = false;
    this.isInferoplantarLongitudinalLigament = false;
    this.isMedioplantarObliqueLigament = false;
    this.isSuperomedialCalcaneonavicularLigament = false;
    this.ruptureType = RuptureTypeEnum.None;
    this.partialRuptureType = PartialRupturetTypeEnum.None;
    this.isIncreasedT2Signal = false;
    this.isWithRetraction = false;
    this.isTalocalcanealLigamentRupture = false;
    this.isCervicalLigamentRupture = false;
    this.isTalocalcanealInterosseouseLigamentRupture = false;
    this.isTarsalSinusFatEdema = false;
    this.isGanglion = false;
    this.diameterInMm = null;
    this.isCalcaneonavicularLigament = false;
    this.isCalcaneocuboidalLigament = false;
    this.isOsseousAvulsionFracture = false;
    this.isAnteriorProcessOfTheCalcaneus = false;
    this.isLongPlantarLigament = false;
    this.isShortPlantarLigament = false;
    this.isTendinopathy = false;
    this.isThickening = false;
    this.isFusiformContour = false;
    this.localizationType = LocalizationTypeEnum.None;
    this.distanceFromTuberCalcanei = null;
    this.isRetrocalcanealSubachillealBursitis = false;
    this.isIntrinsicCalcification = false;
    this.isIntratendinousSoftTissueFoci = false;
    this.isHypervascularizationTheTendon = false;
    this.isOsteitisOnTheTuberCalcanei = false;
    this.isHaglundDeformity = false;
    this.isDorsalHeelSpur = false;
    this.isPeritendinousEdema = false;
    this.isEdemaInKagerFatPad = false;
    this.differentialDiagnosisType = DifferentialDiagnosisTypeEnum.None;
    this.isTear = false;
    this.retractionInMm = null;
    this.ruptureLocalizationType = RuptureLocalizationTypeEnum.None;
    this.associatedFindingsType = AssociatedFindingsTypeEnum.None;
    this.isPeritendinitis = false;
    this.isOsPeroneum = false;
    this.longitudinalExpansionTheLesionInMm = null;
    this.isTendovaginitis = false;
    this.isContactWithOsteosynthesisMaterial = false;
    this.isFluidInTendonSheath = false;
    this.isOsTrigonumSyndrome = false;
    this.isAccompanyingBoneMarrowEdema = false;
    this.isPesPlanumDeformity = false;
    this.isT2wPDHyperintensity = false;
    this.isT1wHyperintensity = false;
    this.isConvexAnteriorContour = false;
    this.isFusiformContour = false;
    this.isCalcifyingTendinitis = false;
    this.isIntratendinousSoftTissueIntensive = false;
    this.isTendonHypervascularisation = false;
    this.isOsteitisOfTheTuber = false;
    this.isLongitudinalTear = false;
    this.isReRupture = false;
    this.isFluidInTheCommonTendonSheathOfThePeronealTendons = false;
    this.isMPeroneusLongusTendon = false;
    this.isFluidInTheTendonSheathDistalToTheLateralMalleolus = false;
    this.isGanglionAtTheLevelOfTheInsertionAtOsMetatarsalD1OsCuboideum = false;
    this.isTendonDislocation = false;
    this.isTendovaginitisDueToOsteophyteAtDorsomedialDistalTibia = false;
    this.isAfterHalluxValgusSurgery = false;
    this.isAnkleJointEffusion = false;
    this.isGanglionToInsertionBaseDistalPhalanxD1 = false;
    this.isOsTibialAccessorium = false;
    this.isPseudotumorOnTheBackOfTheFoot = false;
    this.localizationOfTendonRuptureType = LocalizationOfTheTendonRuptureTypeEnum.None;
    this.maxExtentInCrossSectionInPercent = null;
    this.craniocaudaleExtensionInMm = null;
    this.sizeInMm = null;
    this.maxSagittalDiameterInMm = null;
    this.distanceToTuberCalcaneiInMm = null;
    this.extraarticularLocalizationType = new FootBigTendonsModel();
  }
}
