import { EnumBase } from '@abstractions/enum-base/enum-base.model';

export class FootBigModel extends EnumBase {
  tibia: boolean;
  fibula: boolean;
  talus: boolean;
  posteromedialTalus: boolean;
  anterolateralTalus: boolean;
  calcaneus: boolean;
  osNaviculare: boolean;
  osCuneiformeMediale: boolean;
  osCuneiformeIntermedium: boolean;
  osCuneiformeLaterale: boolean;
  osCuboideum: boolean;
  osMetatarsale1: boolean;
  osMetatarsale2: boolean;
  osMetatarsale3: boolean;
  osMetatarsale4: boolean;
  osMetatarsale5: boolean;
  osMetatarsale5Proximal: boolean;
  osMetatarsale5Distal: boolean;
  proximalPhalanxD1: boolean;
  proximalPhalanxD2: boolean;
  proximalPhalanxD3: boolean;
  proximalPhalanxD4: boolean;
  proximalPhalanxD5: boolean;
  // middlePhalanxD1: boolean;
  middlePhalanxD2: boolean;
  middlePhalanxD3: boolean;
  middlePhalanxD4: boolean;
  middlePhalanxD5: boolean;
  distalPhalanxD1: boolean;
  distalPhalanxD2: boolean;
  distalPhalanxD3: boolean;
  distalPhalanxD4: boolean;
  distalPhalanxD5: boolean;
  talocruralJoint: boolean;
  subtalarJoint: boolean;
  articulatioCalcaneocuboidea: boolean;
  talonavicularJoint: boolean;
  tarsometatarsalJoints: boolean;
  metatarsophalangealJointD1: boolean;
  metatarsophalangealJointD2: boolean;
  metatarsophalangealJointD3: boolean;
  metatarsophalangealJointD4: boolean;
  metatarsophalangealJointD5: boolean;
  proximalInterphalangealJointD1: boolean;
  proximalInterphalangealJointD2: boolean;
  proximalInterphalangealJointD3: boolean;
  proximalInterphalangealJointD4: boolean;
  proximalInterphalangealJointD5: boolean;
  distalInterphalangealJointD2: boolean;
  distalInterphalangealJointD3: boolean;
  distalInterphalangealJointD4: boolean;
  distalInterphalangealJointD5: boolean;
  malleoli: boolean;
  complexOrMultipleBones: boolean;
  constructor() {
    super();
    this.tibia = false;
    this.fibula = false;
    this.talus = false;
    this.posteromedialTalus = false;
    this.anterolateralTalus = false;
    this.calcaneus = false;
    this.osNaviculare = false;
    this.osCuneiformeMediale = false;
    this.osCuneiformeIntermedium = false;
    this.osCuneiformeLaterale = false;
    this.osCuboideum = false;
    this.osMetatarsale1 = false;
    this.osMetatarsale2 = false;
    this.osMetatarsale3 = false;
    this.osMetatarsale4 = false;
    this.osMetatarsale5 = false;
    this.osMetatarsale5Proximal = false;
    this.osMetatarsale5Distal = false;
    this.proximalPhalanxD1 = false;
    this.proximalPhalanxD2 = false;
    this.proximalPhalanxD3 = false;
    this.proximalPhalanxD4 = false;
    this.proximalPhalanxD5 = false;
    this.middlePhalanxD2 = false;
    this.middlePhalanxD3 = false;
    this.middlePhalanxD4 = false;
    this.middlePhalanxD5 = false;
    this.distalPhalanxD1 = false;
    this.distalPhalanxD2 = false;
    this.distalPhalanxD3 = false;
    this.distalPhalanxD4 = false;
    this.distalPhalanxD5 = false;
    this.talocruralJoint = false;
    this.subtalarJoint = false;
    this.articulatioCalcaneocuboidea = false;
    this.talonavicularJoint = false;
    this.tarsometatarsalJoints = false;
    this.metatarsophalangealJointD1 = false;
    this.metatarsophalangealJointD2 = false;
    this.metatarsophalangealJointD3 = false;
    this.metatarsophalangealJointD4 = false;
    this.metatarsophalangealJointD5 = false;
    this.proximalInterphalangealJointD1 = false;
    this.proximalInterphalangealJointD2 = false;
    this.proximalInterphalangealJointD3 = false;
    this.proximalInterphalangealJointD4 = false;
    this.proximalInterphalangealJointD5 = false;
    this.distalInterphalangealJointD2 = false;
    this.distalInterphalangealJointD3 = false;
    this.distalInterphalangealJointD4 = false;
    this.distalInterphalangealJointD5 = false;
    this.malleoli = false;
    this.complexOrMultipleBones = false;
  }
}
