export enum MusculatureLocationTypeEnum {
  None = 'None',
  MusculatureMVvastusIntermedius = 'MusculatureMVvastusIntermedius',
  MusculatureMRectusFemoris = 'MusculatureMRectusFemoris',
  MusculatureMVastusMedialis = 'MusculatureMVastusMedialis',
  MusculatureMSartorius = 'MusculatureMSartorius',
  MusculatureMSemitendinosus = 'MusculatureMSemitendinosus',
  MusculatureMGastrocnemiusCaputMediale = 'MusculatureMGastrocnemiusCaputMediale',
  MusculatureMGracilis = 'MusculatureMGracilis',
  MusculatureMAdductorMagnus = 'MusculatureMAdductorMagnus',
  MusculatureMSemimembranosus = 'MusculatureMSemimembranosus',
  MusculatureMPopliteus = 'MusculatureMPopliteus',
  MusculatureMSoleus = 'MusculatureMSoleus',
  MusculatureMPlantaris = 'MusculatureMPlantaris',
  MusculatureMGastrocnemiusCaputLaterale = 'MusculatureMGastrocnemiusCaputLaterale',
  MusculatureMTibialisAnterior = 'MusculatureMTibialisAnterior',
  MusculatureTractusIliotibialis = 'MusculatureTractusIliotibialis',
  MusculatureMVastusLateralis = 'MusculatureMVastusLateralis',
  MusculatureMTibialisPosterior = 'MusculatureMTibialisPosterior',
  MusculatureMExtensorDigitorumLongus = 'MusculatureMExtensorDigitorumLongus',
  MusculatureMBicepsFemoris = 'MusculatureMBicepsFemoris'
}
