namespace RadioReport.ThoraxMRT.Domain.Enums
{
    public enum PleuraDiagnosisType : byte
    {
        None = 0,
        BenignLesionNotFurtherSpecified = 1,
        MalignantLesionNotFurtherSpecified = 2,
        DignityUnclear = 3,
        Lipoma = 4,
        Metastasis = 5,
        Mesothelioma = 6,
        Lymphoma = 7,
        Liposarcoma = 8,
        PancoastTumor = 9,
        PleuralPlaque = 10,
        PleuralCallus = 11,
        PleuralSplenosis = 12,
        Pleuritis = 13,
        PleuralEffusionTrapped = 14,
        CloakPleuralEffusion = 15,
        HematomaExtrapleural = 16,
        Asbestosis = 17,
        PleuralFibrosis = 18,
        Hemangioma = 19,
        Lymphangioma = 20,
        NeurogenicTumorPNST = 21,
        SchwannomaNeurinoma = 22,
        Neurofibroma = 23,
        EpidermalCyst = 24,
        Elastofibroma = 25,
        Pilomatrixoma = 26,
        Sarcoma = 27,
        Angiosarcoma = 28,
        SarcomaUndifferentiatedPleomorphic = 29,
        MalignantPeripheralNerveSheathTumorMPNST = 30,
        Cyst = 31,
        Pancreatitis = 32,
        PancreaticCarcinoma = 33,
        CysticMassNotFurtherSpecified = 34,
        SolidMass = 35,
        ComplicatedCyst = 36,
        Adenoma = 37
    }
}
