import { FindingBase } from '@models/shared/finding/finding.base';
import { MeningesFindingTypeEnum } from '@enums/headCT/meninges/meninges-finding-type.enum';
import { DescriptionTypeEnum } from '@enums/shared/description-type.enum';
import { MeningesDiagnosisType } from '@enums/headCT/meninges/meninges-diagnosis-type.enum';
import { CysticPartsTypeEnum } from '@enums/headCT/meninges/cystic-parts-type.enum';
import { GrowthPatternTypeEnum } from '@enums/headCT/meninges/growth-pattern-type.enum';
import { ContrastEnhancementQuantitativeTypeEnum } from '@enums/headCT/common/contrast-enhancement-quantitative-type.enum';
import { RegionTypeEnum } from '@enums/headCT/meninges/region-type.enum';
import { CharacterizationHematomaTypeEnum } from '@enums/headCT/meninges/characterization-hematoma-type.enum';
import { DifferentialDiagnosisTypeEnum } from '@enums/headCT/meninges/differential-diagnosis-type.enum';
import { ReferencePictureUiModel } from '@models/shared/reference-picture/reference-picture-ui.model';
import { DensityTypeEnum } from '@enums/headCT/common/density-type.enum';
import { ContrastDistributionTypeEnum } from '@enums/headCT/common/contrast-distribution-type.enum';
import { HomogeneityTypeEnum } from '@enums/headCT/common/homogeneity-type.enum';
import { MidlineShiftSideTypeEnum } from '@enums/headCT/common/midline-shift-side-type.enum';
import { ShapeTypeEnum } from '@enums/headCT/common/shape-type.enum';
import { MarginTypeEnum } from '@enums/headCT/common/margin-type.enum';
import { HistologyKnownTypeEnum } from '@enums/headCT/common/histology-known-type.enum';

export class MeningesFindingUiModel extends FindingBase {
  findingType: MeningesFindingTypeEnum;
  descriptionType: DescriptionTypeEnum;
  differentialDiagnosis: MeningesDiagnosisType;
  isHistologyKnown: boolean;
  histologyKnownType: HistologyKnownTypeEnum;
  isRight: boolean;
  isLeft: boolean;
  isMedian: boolean;
  isFrontal: boolean;
  isTemporal: boolean;
  isParietal: boolean;
  isOccipital: boolean;
  isInfratentorial: boolean;
  isFalx: boolean;
  isTentorium: boolean;
  isLaminaCribrosa: boolean;
  isOpticNerveSheath: boolean;
  isIntrasellar: boolean;
  isSkullBase: boolean;
  isPosteriorClinoidProcess: boolean;
  isSphenoidWing: boolean;
  isCerebellopontineAngle: boolean;
  isSigmoidSulcus: boolean;
  isTrigoneOfTheLateralVentricle: boolean;
  isInsularCistern: boolean;
  isForamenMagnum: boolean;
  isJugularForamen: boolean;
  sizeInMm: number;
  secondPlaneInMm: number;
  thirdPlaneInMm: number;
  marginType: MarginTypeEnum;
  homogeneityType: HomogeneityTypeEnum;
  shapeType: ShapeTypeEnum;
  isEnPlaqueConfiguration: boolean;
  densityType: DensityTypeEnum;
  quantitativeInHu: number;
  isFat: boolean;
  isCysticParts: boolean;
  cysticPartsType: CysticPartsTypeEnum;
  isSolidParts: boolean;
  isHemorrhage: boolean;
  isCapsule: boolean;
  isSepta: boolean;
  isNecrosis: boolean;
  isCalcification: boolean;
  growthPatternType: GrowthPatternTypeEnum;
  isGyriformGrowth: boolean;
  isIntrameatalGrowth: boolean;
  isIntraforaminalFissuralGrowth: boolean;
  isPerifocalCerebralEdema: boolean;
  isDuraTailSign: boolean;
  isLocalVenousStasis: boolean;
  isOsteolysis: boolean;
  isHyperostosisOfTheAdjacentBone: boolean;
  contrastEnhancementType: ContrastEnhancementQuantitativeTypeEnum;
  contrastEnhancementHomogeneityType: HomogeneityTypeEnum;
  contrastDistributionType: ContrastDistributionTypeEnum;
  differentialDiagnosis1: MeningesDiagnosisType;
  isSuspicionOf: boolean;
  differentialDiagnosis2: MeningesDiagnosisType;
  isSubordinate: boolean;
  differentialDiagnosis3: MeningesDiagnosisType;
  isMoreThenOneLesionOfTheSameEntity: boolean;
  isThickening: boolean;
  meningesWidthInMm: number;
  isPachymeninges: boolean;
  isLeptomeninges: boolean;
  isAbscess: boolean;
  maxExtensionInMm: number;
  isAbscessCapsule: boolean;
  isEmpyema: boolean;
  isHydrocephalus: boolean;
  currentExaminationInHu: number;
  previousExaminationInHu: number;
  isCrescentShaped: boolean;
  isCrossingSutures: boolean;
  isDuralAttachmentNotExceeded: boolean;
  maxWidthInMm: number;
  isAlongFalx: boolean;
  isAlongTentorium: boolean;
  isSeptations: boolean;
  isContrastEnhancementMembrane: boolean;
  isFluid: boolean;
  isFluidLevel: boolean;
  isCorticalVeinDisplacement: boolean;
  isDuralThickening: boolean;
  isContrastEnhancement: boolean;
  isMidlineShift: boolean;
  midlineShiftSideType: MidlineShiftSideTypeEnum;
  midlineShiftInMm: number;
  isHerniation: boolean;
  regionType: RegionTypeEnum;
  characterizationHematomaType: CharacterizationHematomaTypeEnum;
  differentialDiagnosisType: DifferentialDiagnosisTypeEnum;
  isDuralAttachmentCrossed: boolean;
  isSuturesNotCrossed: boolean;
  isDuralDisplacementBetweenEDHAndBrain: boolean;
  isBiconvex: boolean;
  isAssociatedSkullFracture: boolean;
  isSwirlSign: boolean;
  isContrecoupSDH: boolean;
  isAdjacentContusion: boolean;
  isConcomitantHydrocephalus: boolean;
  isAssociatedInfarction: boolean;
  referencePicture: ReferencePictureUiModel;

  constructor() {
    super();

    this.findingType = MeningesFindingTypeEnum.None;
    this.descriptionType = DescriptionTypeEnum.None;
    this.differentialDiagnosis = MeningesDiagnosisType.None;
    this.isHistologyKnown = false;
    this.histologyKnownType = HistologyKnownTypeEnum.None;
    this.isRight = false;
    this.isLeft = false;
    this.isMedian = false;
    this.isFrontal = false;
    this.isTemporal = false;
    this.isParietal = false;
    this.isOccipital = false;
    this.isInfratentorial = false;
    this.isFalx = false;
    this.isTentorium = false;
    this.isLaminaCribrosa = false;
    this.isOpticNerveSheath = false;
    this.isIntrasellar = false;
    this.isSkullBase = false;
    this.isPosteriorClinoidProcess = false;
    this.isSphenoidWing = false;
    this.isCerebellopontineAngle = false;
    this.isSigmoidSulcus = false;
    this.isTrigoneOfTheLateralVentricle = false;
    this.isInsularCistern = false;
    this.isForamenMagnum = false;
    this.isJugularForamen = false;
    this.sizeInMm = null;
    this.secondPlaneInMm = null;
    this.thirdPlaneInMm = null;
    this.marginType = MarginTypeEnum.None;
    this.homogeneityType = HomogeneityTypeEnum.None;
    this.shapeType = ShapeTypeEnum.None;
    this.isEnPlaqueConfiguration = false;
    this.densityType = DensityTypeEnum.None;
    this.quantitativeInHu = null;
    this.isFat = false;
    this.isCysticParts = false;
    this.cysticPartsType = CysticPartsTypeEnum.None;
    this.isSolidParts = false;
    this.isHemorrhage = false;
    this.isCapsule = false;
    this.isSepta = false;
    this.isNecrosis = false;
    this.isCalcification = false;
    this.growthPatternType = GrowthPatternTypeEnum.None;
    this.isGyriformGrowth = false;
    this.isIntrameatalGrowth = false;
    this.isIntraforaminalFissuralGrowth = false;
    this.isPerifocalCerebralEdema = false;
    this.isDuraTailSign = false;
    this.isLocalVenousStasis = false;
    this.isOsteolysis = false;
    this.isHyperostosisOfTheAdjacentBone = false;
    this.contrastEnhancementType = ContrastEnhancementQuantitativeTypeEnum.None;
    this.contrastEnhancementHomogeneityType = HomogeneityTypeEnum.None;
    this.contrastDistributionType = ContrastDistributionTypeEnum.None;
    this.differentialDiagnosis1 = MeningesDiagnosisType.None;
    this.isSuspicionOf = false;
    this.differentialDiagnosis2 = MeningesDiagnosisType.None;
    this.isSubordinate = false;
    this.differentialDiagnosis3 = MeningesDiagnosisType.None;
    this.isMoreThenOneLesionOfTheSameEntity = false;
    this.isThickening = false;
    this.meningesWidthInMm = null;
    this.isPachymeninges = false;
    this.isLeptomeninges = false;
    this.isAbscess = false;
    this.maxExtensionInMm = null;
    this.isAbscessCapsule = false;
    this.isEmpyema = false;
    this.isHydrocephalus = false;
    this.currentExaminationInHu = null;
    this.previousExaminationInHu = null;
    this.isCrescentShaped = false;
    this.isCrossingSutures = false;
    this.isDuralAttachmentNotExceeded = false;
    this.maxWidthInMm = null;
    this.isAlongFalx = false;
    this.isAlongTentorium = false;
    this.isSeptations = false;
    this.isContrastEnhancementMembrane = false;
    this.isFluid = false;
    this.isFluidLevel = false;
    this.isCorticalVeinDisplacement = false;
    this.isDuralThickening = false;
    this.isContrastEnhancement = false;
    this.isMidlineShift = false;
    this.midlineShiftSideType = MidlineShiftSideTypeEnum.None;
    this.midlineShiftInMm = null;
    this.isHerniation = false;
    this.regionType = RegionTypeEnum.None;
    this.characterizationHematomaType = CharacterizationHematomaTypeEnum.None;
    this.differentialDiagnosisType = DifferentialDiagnosisTypeEnum.None;
    this.isDuralAttachmentCrossed = false;
    this.isSuturesNotCrossed = false;
    this.isDuralDisplacementBetweenEDHAndBrain = false;
    this.isBiconvex = false;
    this.isAssociatedSkullFracture = false;
    this.isSwirlSign = false;
    this.isContrecoupSDH = false;
    this.isAdjacentContusion = false;
    this.isConcomitantHydrocephalus = false;
    this.isAssociatedInfarction = false;

    this.referencePicture = new ReferencePictureUiModel();
  }
}
