export enum TumorRegressionGradeTypeEnum {
  None = 'None',
  Trg1RadiologicallyCompleteRemissionFibroticScarWithoutTumorSignal = 'Trg1RadiologicallyCompleteRemissionFibroticScarWithoutTumorSignal',
  Trg2GoodResponseDominanceOfDenseFibrosisPatternWithLowTumorSignal = 'Trg2GoodResponseDominanceOfDenseFibrosisPatternWithLowTumorSignal',
  Trg3ModerateResponseSignificantResidualTumorBut50FibrosisOrMucinousChanges = 'Trg3ModerateResponseSignificantResidualTumorBut50FibrosisOrMucinousChanges',
  Trg4PartialResponseMainlyTumorWithSmallFibrosisAreasWithLowSignalIntensityOrSmallMucinousChanges = 'Trg4PartialResponseMainlyTumorWithSmallFibrosisAreasWithLowSignalIntensityOrSmallMucinousChanges',
  Trg5NoResponseTumorUnchangedFromBaselineExamination = 'Trg5NoResponseTumorUnchangedFromBaselineExamination'
}
