namespace RadioReport.NeckMRT.Domain.Enums.SoftTissues.MassInflammation
{
    public enum DifferentialDiagnosisType : byte
    {
        None = 0,
        BenignLesionNotFurtherSpecified = 1,
        MalignantLesionNotFurtherSpecified = 2,
        DignityUnclear = 3,
        Atheroma = 4,
        Pseudotumor = 5,
        Cyst = 6,
        Lipoma = 7,
        MedianNeckCyst = 8,
        LateralNeckCyst = 9,
        CysticHygroma = 10,
        WarthinTumor = 11,
        Hemangioma = 12,
        MalformationVenous = 13,
        MalformationLymphatic = 14,
        Paraganglioma = 15,
        Schwannoma = 16,
        Neurofibroma = 17,
        Lymphangioma = 18,
        Fibromatosis = 19,
        JuvenileAngiofibroma = 20,
        EctopicThyroidTissue = 21,
        SquamousCellCarcinoma = 22,
        MalignantMassOfTheSalivaryGland = 23,
        Lymphoma = 24,
        LymphNodeMetastasis = 25,
        Metastasis = 26,
        Sarcoma = 27,
        MalignantFibrousHistiocytoma = 28,
        BasalCellCarcinoma = 29,
        MalignantMelanoma = 30,
        InflammationAcute = 31,
        InflammationChronic = 32,
        EnlargedLymphNode = 33,
        LymphadenopathyInMononucleosis = 34,
        LymphadenopathyInTuberculosis = 35,
        LymphadenopathyInSarcoidosis = 36,
        SoftTissueAbscess = 37,
        Phlegmon = 38,
        Hematoma = 39,
        Gas = 40,
        Edema = 41,
        Laryngocele = 42
    }
}
