export enum SecondTumorDifferentialDiagnosisEnum {
  None = 'None',
  Benigne = 'Benigne',
  Enchondrome = 'Enchondrome',
  Hemangioma = 'Hemangioma',
  SclerosisIslandOrEnostosis = 'SclerosisIslandOrEnostosis',
  IntraosseousLipoma = 'IntraosseousLipoma',
  IntraosseousCyst = 'IntraosseousCyst',
  BoneInfarction = 'BoneInfarction',
  FibrousDysplasia = 'FibrousDysplasia',
  AneurysmaticBoneCyst = 'AneurysmaticBoneCyst',
  OsteoidOsteoma = 'OsteoidOsteoma',
  Osteochondrome = 'Osteochondrome',
  Chondroblastoma = 'Chondroblastoma',
  Osteoblastoma = 'Osteoblastoma',
  EwingSarcoma = 'EwingSarcoma',
  Osteosarcoma = 'Osteosarcoma',
  GiantCellTumor = 'GiantCellTumor',
  Chondrosarcoma = 'Chondrosarcoma',
  Metastasis = 'Metastasis',
  Lymphoma = 'Lymphoma',
  MultipleMyeloma = 'MultipleMyeloma',
  Osteomyelitis = 'Osteomyelitis'
}
