
namespace RadioReport.NeckMRT.Domain.Enums.Thyroid
{
	public enum DifferentialDiagnosisType : byte
	{
		None = 0,
		BenignLesionNotFurtherSpecified = 1,
		MalignantLesionNotFurtherSpecified = 2,
		DignityUnclear = 3,
		Struma = 4,
		StrumaDiffusa = 5,
		StrumaNodosa = 6,
		Cyst = 7,
		ProteinContainingCyst = 8,
		ThyroidAdenoma = 9,
		EctopicThyroidTissue = 10,
		ParathyroidAdenoma = 11,
		ThyroidCarcinoma = 12,
		Metastasis = 13,
		Lymphoma = 14,
		Thyroiditis = 15,
		Sarcoidosis = 16,
		Amyloidosis = 17,
		Hemochromatosis = 18,
		RiedelSThyroiditis = 19,
		Ranula = 20,
		RetentionCyst = 21,
		PleomorphicAdenoma = 22,
		WarthinTumor = 23,
		IntraductalPapilloma = 24,
		DermoidCyst = 25,
		Hemangioma = 26,
		Neurofibroma = 27,
		Lipoma = 28,
		MucoepidermoidCarcinoma = 29,
		AcinarCellCarcinoma = 30,
		AdenoidCysticCarcinoma = 31,
		SquamousCellCarcinoma = 32,
		Sarcoma = 33,
		CombinedVenolymphaticMalformation = 34,
		LymphaticMalformation = 35,
		ActueSialadenitis = 36,
		ObstructiveSialadenitis = 37,
		ChronicSclerosingSialadenitis = 38,
		KuttnerTumor = 39,
		Parotitis = 40,
		ParotitisGranulomatousTbc = 41,
		SjogrenSSyndrome = 42,
		Sialosis = 43,
		VascularMalformations = 44
	}
}