namespace RadioReport.AbdomenMRT.Domain.Enums.GastrointestinalTract
{
	public enum GastrointestinalDifferentialDiagnosisType
	{
		None = 0,
		BenignLesionNotFurtherSpecified = 1,
		MalignantLesionNotFurtherSpecified = 2,
		UnclearEtiology = 3,
		Adenoma = 4,
		Leiomyoma = 5,
		Neurofibroma = 6,
		Lipoma = 7,
		Angioma = 8,
		GastricCarcinoma = 9,
		Lymphoma = 10,
		Sarcoma = 11,
		Metastasis = 12,
		Gist = 13,
		CrohnSDisease = 14,
		UlcerativeColitis = 15,
		BackwashIleitis = 16,
		PseudomembranousColitis = 17,
		ToxicMegacolon = 18,
		InfectiousEnterocolitis = 19,
		Enteritis = 20,
		IntestinalLymphoma = 21,
		MesentericIschemia = 22,
		SubmucosalHemorrhage = 23,
		RadiationInducedBowelWallChanges = 24,
		Diverticulitis = 25,
		NeoplasticWallThickening = 26,
		Polyp = 27,
		Diverticulum = 28,
		NeurofibromatousTumor = 29,
		Fibroma = 30,
		Hemangioma = 31,
		Lymphangioma = 32,
		Carcinoma = 33,
		ColorectalCarcinoma = 34,
		Carcinoid = 35,
		Leiomyosarcoma = 36,
		ChronicInflammatoryBowelDisease = 37,
		Endometriosis = 38
	}
}