export enum ParanasalSinusesDiagnosisTypeEnum {
  None = 'None',
  BenignLesionNotFurtherSpecified = 'BenignLesionNotFurtherSpecified',
  MalignantLesionNotFurtherSpecified = 'MalignantLesionNotFurtherSpecified',
  UnclearEtiology = 'UnclearEtiology',
  InvertedPapilloma = 'InvertedPapilloma',
  Osteoma = 'Osteoma',
  JuvenileNasopharyngealAngiofibroma = 'JuvenileNasopharyngealAngiofibroma',
  Meningioma = 'Meningioma',
  Carcinoma = 'Carcinoma',
  SquamousCellCarcinoma = 'SquamousCellCarcinoma',
  Metastasis = 'Metastasis',
  Lymphoma = 'Lymphoma',
  ChoanalPolyp = 'ChoanalPolyp',
  Polyposis = 'Polyposis',
  AcuteSinusitis = 'AcuteSinusitis',
  ChronicSinusitis = 'ChronicSinusitis',
  NonInvasiveFungalSinusitis = 'NonInvasiveFungalSinusitis',
  InvasiveFungalSinusitis = 'InvasiveFungalSinusitis',
  GranulomatosisWithPoyangitis = 'GranulomatosisWithPoyangitis',
  Mucocele = 'Mucocele',
  Encephalocele = 'Encephalocele',
  OdontogenicCyst = 'OdontogenicCyst',
  Keratocyst = 'Keratocyst',
  RetentionCyst = 'RetentionCyst',
  FibrousDysplasia = 'FibrousDysplasia'
}
