export const PROTOCOL_NAME = 'radioreport';
export const BASE_URL_CONFIG = '$BASE_URL';
export const UPDATE_URL_CONFIG = '$UPDATE_URL';
export const INSTITUTE_ID_CONFIG = '$INSTITUTE_ID';
export const TRACKING_CONFIG = '$TRACKING';
export const TRACELOG_CONFIG = '$TRACELOG';
export const PROTOCOL_CLIENT_CONFIG = '$PROTOCOLCLIENT';
export const DEVTOOLS_CONFIG = '$DEVTOOLS';
export const IMPORTLOGS_CONFIG = '$IMPORTLOGS';
export const IMPORT_MODULE_PRESELECT = '$IMPORT_MODULE_PRESELECT';
export const DICOM_HOST_CONFIG = '$DICOM_HOST';
export const DICOM_PORT_CONFIG = '$DICOM_PORT';
export const DICOM_CALLING_AET_CONFIG = '$DICOM_CALLING_AE';
export const DICOM_CALLED_AET_CONFIG = '$DICOM_CALLED_AE';
export const DICOM_REQUEST_TYPE_CONFIG = '$DICOM_REQUEST_TYPE';
export const DICOM_SCP_PORT_CONFIG = '$DICOM_SCP_PORT';
export const IMPORTABLE_MODULES = [
  'ABDOMENMRT',
  'ANGIOGRAPHYMRT',
  'CARDIOMRT',
  'ELBOWMRT',
  'FEETMRT',
  'HANDMRT',
  'HIPMRT',
  'KNEEMRT',
  'MAMMAMRT',
  'PELVISMRT',
  'SHOULDERMRT',
  'SPINEMRT',
  'THORAXMRT',
  'SPINECT',
  'THORAXCT',
  'MAMMAMX',
  'NECKMRT',
  'HEADMRT',
  'ANGIOGRAPHYCT'
];
