import { FindingBase } from '@models/shared/finding/finding.base';
import { ThreeCrossSection } from '@models/pelvisMRT/ui/localizers/three-cross-section';
import { OneCrossSection } from '@models/pelvisMRT/ui/localizers/one-cross-section';
import { CapsuleTypeEnum } from '@enums/pelvisMRT/prostate/capsule-type.enum';
import { ProstataFindingTypeEnum } from '@enums/pelvisMRT/prostate/prostata-finding-type.enum';
import { DescriptionTypeEnum } from '@enums/shared/description-type.enum';
import { SignalPowerTypeEnum } from '@enums/pelvisMRT/prostate/signal-power-type.enum';
import { MarginTypeEnum } from '@enums/pelvisMRT/prostate/margin-type.enum';
import { HomogenityTypeEnum } from '@enums/pelvisMRT/prostate/homogenity-type.enum';
import { DwiAdcSignalTypeEnum } from '@enums/pelvisMRT/prostate/dwi-adc-signal-type.enum';
import { DiscreteTypeEnum } from '@enums/pelvisMRT/prostate/discrete-type.enum';
import { PenetrationOfPseudocapsuleTypeEnum } from '@enums/pelvisMRT/prostate/penetration-of-pseudocapsule-type.enum';
import { DynamicContrastEnhancedTypeEnum } from '@enums/pelvisMRT/prostate/dynamic-contrast-enhanced-type.enum';
import { DceMrtNegativeTypeEnum } from '@enums/pelvisMRT/prostate/dce-mrt-negative-type.enum';
import { SideAsymmetryTypeEnum } from '@enums/pelvisMRT/prostate/page-asymmetry-type.enum';
import { SizeTypeEnum } from '@enums/pelvisMRT/prostate/size-type.enum';
import { IndexLesionTypeEnum } from '@enums/pelvisMRT/prostate/index-lesion-type.enum';
import { DirectionTypeEnum } from '@enums/shared/direction-type.enum';
import { PatternTypeEnum } from '@enums/pelvisMRT/prostate/pattern-type.enum';
import { ExtraprostaticGrowthTypeEnum } from '@enums/pelvisMRT/prostate/extraprostatic-growth-type.enum';

export class ProstateFindingUiModel extends FindingBase {
  findingType: ProstataFindingTypeEnum;
  descriptionType: DescriptionTypeEnum;

  signalPowerType: SignalPowerTypeEnum;
  isSignalLossFlowVoid: boolean;
  marginType: MarginTypeEnum;
  homogenityType: HomogenityTypeEnum;
  transitionaZoneTZCapsuleType: CapsuleTypeEnum;
  isAnteriorFibromuscularStroma: boolean;
  isCentralZone: boolean;
  isEjaculatoryDuct: boolean;
  ejaculatoryDuctDirectionType: DirectionTypeEnum;
  isProstaticUrethra: boolean;
  isLentiform: boolean;
  isInfiltrationSpiculated: boolean;
  isErasedCharcoalSign: boolean;
  isTypicalBphNode: boolean;
  isIncreasedDwiSignal: boolean;
  increasedDwiSignalType: DwiAdcSignalTypeEnum;
  dwiDiscreteType: DiscreteTypeEnum;
  isAdcHypointensity: boolean;
  adcHypointensityType: DwiAdcSignalTypeEnum;
  adcDiscreteType: DiscreteTypeEnum;
  dynamicContrastEnhancedType: DynamicContrastEnhancedTypeEnum;
  dceMrtNegativeType: DceMrtNegativeTypeEnum;
  extraprostaticGrowthType: ExtraprostaticGrowthTypeEnum;
  penetrationOfPseudocapsuleType: PenetrationOfPseudocapsuleTypeEnum;
  isPseudocapsularBulgingSpiculated: boolean;
  isSuspicionOf: boolean;
  isSeminalVesicles: boolean;
  isAlteredInternalStructure: boolean;
  isFocalOrDiffuseT2wSignalReduction: boolean;
  isSeparateFocalT2wSignalReduction: boolean;
  isEnlargedEjaculatoryDuctWithT2wSignalReduction: boolean;
  isObliterationOfProstateSeminalVesicleAngle: boolean;
  isDirectInfiltrationPerContinuitatem: boolean;
  isNeurovascularBundle: boolean;
  neurovascularBundleDirectionType: string;
  seminalVesiclesDirectionType: DirectionTypeEnum;
  isRectum: boolean;
  isUrinaryBladder: boolean;
  isExternalUrethrasphincter: boolean;
  isMembranousUrethra: boolean;
  piradsScoreSizeType: SizeTypeEnum;
  sliderPiradasScoreType: number;
  indexLesionType: IndexLesionTypeEnum;
  piradsScoreTotal: number;
  differentialDiagnosis01: string;
  isSuspicionOf01: boolean;
  differentialDiagnosis02: string;
  isSuspicionOf02: boolean;
  isDifferentialDiagnosis01GranulomatousProstatitis: boolean;
  isDifferentialDiagnosis02GranulomatousProstatitis: boolean;
  isSideAsymmetry: boolean;
  isDisplacementOrDeformationInBph: boolean;
  sideAsymmetryType: SideAsymmetryTypeEnum;
  patternType: PatternTypeEnum;

  localizationT1wSignalEnhancementType: ThreeCrossSection;
  peripheralZonePZLocalizerType: ThreeCrossSection;
  transitionaZoneTZLocalizerType: ThreeCrossSection;
  centralZoneCZLocalizerType: OneCrossSection;

  constructor() {
    super();

    this.findingType = ProstataFindingTypeEnum.None;
    this.descriptionType = DescriptionTypeEnum.None;
    this.signalPowerType = SignalPowerTypeEnum.None;
    this.isSignalLossFlowVoid = false;
    this.marginType = MarginTypeEnum.None;
    this.homogenityType = HomogenityTypeEnum.None;
    this.transitionaZoneTZCapsuleType = CapsuleTypeEnum.None;
    this.isAnteriorFibromuscularStroma = false;
    this.isCentralZone = false;
    this.isEjaculatoryDuct = false;
    this.ejaculatoryDuctDirectionType = DirectionTypeEnum.None;
    this.isProstaticUrethra = false;
    this.isLentiform = false;
    this.isInfiltrationSpiculated = false;
    this.isErasedCharcoalSign = false;
    this.isTypicalBphNode = false;
    this.isIncreasedDwiSignal = false;
    this.increasedDwiSignalType = DwiAdcSignalTypeEnum.None;
    this.dwiDiscreteType = DiscreteTypeEnum.None;
    this.isAdcHypointensity = false;
    this.adcHypointensityType = DwiAdcSignalTypeEnum.None;
    this.adcDiscreteType = DiscreteTypeEnum.None;
    this.dynamicContrastEnhancedType = DynamicContrastEnhancedTypeEnum.None;
    this.dceMrtNegativeType = DceMrtNegativeTypeEnum.None;
    this.penetrationOfPseudocapsuleType = PenetrationOfPseudocapsuleTypeEnum.None;
    this.extraprostaticGrowthType = ExtraprostaticGrowthTypeEnum.None;
    this.isPseudocapsularBulgingSpiculated = false;
    this.isSuspicionOf = false;
    this.isSeminalVesicles = false;
    this.isAlteredInternalStructure = false;
    this.isFocalOrDiffuseT2wSignalReduction = false;
    this.isSeparateFocalT2wSignalReduction = false;
    this.isEnlargedEjaculatoryDuctWithT2wSignalReduction = false;
    this.isObliterationOfProstateSeminalVesicleAngle = false;
    this.isDirectInfiltrationPerContinuitatem = false;
    this.isNeurovascularBundle = false;
    this.neurovascularBundleDirectionType = DirectionTypeEnum.None;
    this.seminalVesiclesDirectionType = DirectionTypeEnum.None;
    this.isRectum = false;
    this.isUrinaryBladder = false;
    this.isExternalUrethrasphincter = false;
    this.isMembranousUrethra = false;
    this.piradsScoreSizeType = SizeTypeEnum.None;
    this.sliderPiradasScoreType = 1;
    this.indexLesionType = IndexLesionTypeEnum.None;
    this.piradsScoreTotal = null;
    this.differentialDiagnosis01 = 'None';
    this.isSuspicionOf01 = false;
    this.differentialDiagnosis02 = 'None';
    this.isSuspicionOf02 = false;
    this.isDifferentialDiagnosis01GranulomatousProstatitis = false;
    this.isDifferentialDiagnosis02GranulomatousProstatitis = false;
    this.isSideAsymmetry = false;
    this.isDisplacementOrDeformationInBph = false;
    this.sideAsymmetryType = SideAsymmetryTypeEnum.None;
    this.patternType = PatternTypeEnum.None;

    this.localizationT1wSignalEnhancementType = new ThreeCrossSection();
    this.peripheralZonePZLocalizerType = new ThreeCrossSection();
    this.transitionaZoneTZLocalizerType = new ThreeCrossSection();
    this.centralZoneCZLocalizerType = new OneCrossSection();
  }
}
