import { EnumBase } from '@abstractions/enum-base/enum-base.model';

export class SpineLocation extends EnumBase {
  c0: boolean;
  c1: boolean;
  c1d: boolean;
  c2: boolean;
  c2d: boolean;
  c3: boolean;
  c3d: boolean;
  c4: boolean;
  c4d: boolean;
  c5: boolean;
  c5d: boolean;
  c6: boolean;
  c6d: boolean;
  c7: boolean;
  c7d: boolean;
  tH1: boolean;
  tH1d: boolean;
  tH2: boolean;
  tH2d: boolean;
  tH3: boolean;
  tH3d: boolean;
  tH4: boolean;
  tH4d: boolean;
  tH5: boolean;
  tH5d: boolean;
  tH6: boolean;
  tH6d: boolean;
  tH7: boolean;
  tH7d: boolean;
  tH8: boolean;
  tH8d: boolean;
  tH9: boolean;
  tH9d: boolean;
  tH10: boolean;
  tH10d: boolean;
  tH11: boolean;
  tH11d: boolean;
  tH12: boolean;
  tH12d: boolean;
  l1: boolean;
  l1d: boolean;
  l2: boolean;
  l2d: boolean;
  l3: boolean;
  l3d: boolean;
  l4: boolean;
  l4d: boolean;
  l5: boolean;
  l5d: boolean;
  osSacrum: boolean;
  osCoccygis: boolean;

  constructor() {
    super();

    this.c0 = false;
    this.c1 = false;
    this.c1d = false;
    this.c2 = false;
    this.c2d = false;
    this.c3 = false;
    this.c3d = false;
    this.c4 = false;
    this.c4d = false;
    this.c5 = false;
    this.c5d = false;
    this.c6 = false;
    this.c6d = false;
    this.c7 = false;
    this.c7d = false;
    this.tH1 = false;
    this.tH1d = false;
    this.tH2 = false;
    this.tH2d = false;
    this.tH3 = false;
    this.tH3d = false;
    this.tH4 = false;
    this.tH4d = false;
    this.tH5 = false;
    this.tH5d = false;
    this.tH6 = false;
    this.tH6d = false;
    this.tH7 = false;
    this.tH7d = false;
    this.tH8 = false;
    this.tH8d = false;
    this.tH9 = false;
    this.tH9d = false;
    this.tH10 = false;
    this.tH10d = false;
    this.tH11 = false;
    this.tH11d = false;
    this.tH12 = false;
    this.tH12d = false;
    this.l1 = false;
    this.l1d = false;
    this.l2 = false;
    this.l2d = false;
    this.l3 = false;
    this.l3d = false;
    this.l4 = false;
    this.l4d = false;
    this.l5 = false;
    this.l5d = false;
    this.osSacrum = false;
    this.osCoccygis = false;
  }
}
