export enum SummaryDiagnosisTypeEnum {
  None = 'None',
  FungalInfection = 'FungalInfection',
  SusacsSyndrome = 'SusacsSyndrome',
  AntiphospholipidSyndrome = 'AntiphospholipidSyndrome',
  ADEM = 'ADEM',
  NMOSD = 'NMOSD',
  TransverseMyelitis = 'TransverseMyelitis',
  NormalPressureHydrocephalus = 'NormalPressureHydrocephalus',
  AlzheimersDisease = 'AlzheimersDisease',
  MixedDementia = 'MixedDementia',
  FrontotemporalLobarDegeneration = 'FrontotemporalLobarDegeneration',
  VascularDementia = 'VascularDementia',
  MultipleSclerosis = 'MultipleSclerosis',
  CorticobasalDegeneration = 'CorticobasalDegeneration',
  LewyBodyDementia = 'LewyBodyDementia',
  AlcoholAssociated = 'AlcoholAssociated',
  MultisystemAtrophy = 'MultisystemAtrophy',
  MultisystemAtrophyP = 'MultisystemAtrophyP',
  MultisystemAtrophyA = 'MultisystemAtrophyA',
  MultisystemAtrophyC = 'MultisystemAtrophyC',
  CerebralAmyloidAngiopathy = 'CerebralAmyloidAngiopathy',
  CreutzfeldtJakobDisease = 'CreutzfeldtJakobDisease',
  CADASIL = 'CADASIL',
  TraumaticBrainInjury = 'TraumaticBrainInjury'
}
