import { DescriptionTypeEnum } from '@enums/shared/description-type.enum';
import {
  AbdomenClassificationTypeEnum,
  AbdomenLocalizationTypeEnum,
  SoftPartsDiagnosisTypeEnum,
  SoftPartsFormTypeEnum,
  SoftPartsLocalizationCraniocaudalTypeEnum,
  SoftPartsSiteTypeEnum
} from '@enums/thoraxCT/soft-parts/';
import { LymphNodesAxillaryTypeEnum } from '@enums/thoraxCT/soft-parts/lymph-nodes-axillary';
import { SoftPartsLimitationTypeEnum, VolumeTypeEnum } from '@enums/thoraxCT/soft-parts/mamma';
import { ExtensionTypeEnum, PneumothoraxTypeEnum } from '@enums/thoraxCT/soft-parts/pleura-pneumothorax';
import { DistributionTypeEnum, QualityTypeEnum } from '@enums/thoraxCT/soft-parts/pleural-effusion';
import { ChestWallAngleTypeEnum, PleuralMassTypeEnum } from '@enums/thoraxCT/soft-parts/pleural-mass';
import { PleuralThickeningLocalizationTypeEnum } from '@enums/thoraxCT/soft-parts/pleural-thickening';
import { GradingTypeEnum } from '@enums/thoraxCT/soft-parts/upper-abdomen-kidney-adrenal-gland';
import { DiffuseLesionTypeEnum } from '@enums/thoraxCT/soft-parts/upper-abdomen-liver-gall-bladder';
import { SoftPartsFindingBaseApiModel } from '@models/thoraxCT/api/soft-parts/soft-parts-finding-base-api.model';

export class SoftPartsFindingApiModel extends SoftPartsFindingBaseApiModel {
  descriptionType: DescriptionTypeEnum;
  siteType: SoftPartsSiteTypeEnum;
  formType: SoftPartsFormTypeEnum;
  localizationCraniocaudalType: SoftPartsLocalizationCraniocaudalTypeEnum;
  isAnterior: boolean;
  isLateral: boolean;
  isPosterior: boolean;
  isFissural: boolean;
  isMediastinal: boolean;
  sizeMaxWidthInMm: number;
  secondPlaneInMm: number;
  thirdPlaneInMm: number;
  differentialDiagnosis01: SoftPartsDiagnosisTypeEnum;
  isSuspected: boolean;
  differentialDiagnosis02: SoftPartsDiagnosisTypeEnum;
  isSubordinated: boolean;
  differentialDiagnosis03: SoftPartsDiagnosisTypeEnum;
  isMoreThanOneLesion: boolean;
  abdomenLocalizationType: AbdomenLocalizationTypeEnum;
  abdomenClassificationType: AbdomenClassificationTypeEnum;
  siteMaxWidthInMm: number;
  averageDensityInHU: number;
  distributionType: DistributionTypeEnum;
  qualityType: QualityTypeEnum;
  isCoagulum: boolean;
  isGasInclusions: boolean;
  isCMEnrichingCapsule: boolean;
  isSedimentation: boolean;
  isSplitPleuraSign: boolean;
  chestWallAngleType: ChestWallAngleTypeEnum;
  pleuralMassType: PleuralMassTypeEnum;
  isCircumferentialSoftTissueAugmentation: boolean;
  isCircumferentialSoftTissueAugmentationRight: boolean;
  isCircumferentialSoftTissueAugmentationLeft: boolean;
  isCloakPleuralEffusion: boolean;
  pleuralThickeningLocalizationType: PleuralThickeningLocalizationTypeEnum;
  isObtusedAngulationOfCostophrenicAngle: boolean;
  isNodularConfiguration: boolean;
  isLocoregionalOsteolysis: boolean;
  pneumothoraxType: PneumothoraxTypeEnum;
  extensionType: ExtensionTypeEnum;
  expansionMaxWidthInMm: number;
  isMediastinalshift: boolean;
  mediastinalshiftType: SoftPartsSiteTypeEnum;
  isAtelectasis: boolean;
  spineLocation: string;
  isNecroses: boolean;
  isPleura: boolean;
  isPericardium: boolean;
  isBones: boolean;
  isLungs: boolean;
  isMediastinum: boolean;
  isCutisThickening: boolean;
  isPressureErosionRib: boolean;
  volumeType: VolumeTypeEnum;
  lossOfVolumeSiteType: SoftPartsSiteTypeEnum;
  isAblatioRight: boolean;
  isAblatioLeft: boolean;
  isBreastAugmentationRight: boolean;
  isBreastAugmentationLeft: boolean;
  isThickened: boolean;
  thickenedCutisBreastLocation: string;
  isBlurred: boolean;
  blurredSiteType: SoftPartsSiteTypeEnum;
  isStove: boolean;
  stoveBreastLocation: string;
  stoveMaxDiameterAxialInMm: number;
  limitationType: SoftPartsLimitationTypeEnum;
  lymphNodesAxillaryType: LymphNodesAxillaryTypeEnum;
  isLymphNodeRight: boolean;
  rightMarginalShortAxisDiameter: number;
  isLymphNodeLeft: boolean;
  leftMarginalShortAxisDiameter: number;
  isRightLevel1: boolean;
  isRightLevel2: boolean;
  isRightLevel3: boolean;
  isLeftLevel1: boolean;
  isLeftLevel2: boolean;
  isLeftLevel3: boolean;
  isFocalLiverLesion: boolean;
  focalLiverLesionMaxDiameterAxialInMm: number;
  isDiffuseLiverLesion: boolean;
  diffuseLesionType: DiffuseLesionTypeEnum;
  isCholecystolithiasis: boolean;
  isWallThickeningOfTheGallBladder: boolean;
  isFocalPancreaticLesion: boolean;
  focalPancreaticLesionMaxDiameterAxialInMm: number;
  isDiffusePancreaticLesion: boolean;
  isFattyAtrophy: boolean;
  isAccumulationDuctusWirsungianus: boolean;
  isKidney: boolean;
  isKidneyFocalLesion: boolean;
  kidneyFocalLesionMaxDiameterInMm: number;
  isUrinaryRetention: boolean;
  isUrinaryRetentionRight: boolean;
  isUrinaryRetentionLeft: boolean;
  gradingType: GradingTypeEnum;
  isMassAdrenalGland: boolean;
  isMassAdrenalGlandRight: boolean;
  isMassAdrenalGlandLeft: boolean;
  massAdrenalGlandMaxDiameterInMm: number;
  massAdrenalGlandClassificationType: AbdomenClassificationTypeEnum;
  isSplenomegaly: boolean;
  isEnlargedAbdominalLymphNodes: boolean;
  diameterSADInMm: number;
  isPathological: boolean;
  isPathologicalMultiple: boolean;
  isPathologicalConglomerate: boolean;
  isPathologicalHiatusHernia: boolean;

  constructor() {
    super();
    this.descriptionType = DescriptionTypeEnum.None;
    this.siteType = SoftPartsSiteTypeEnum.None;
    this.formType = SoftPartsFormTypeEnum.None;
    this.localizationCraniocaudalType = SoftPartsLocalizationCraniocaudalTypeEnum.None;
    this.isAnterior = false;
    this.isLateral = false;
    this.isPosterior = false;
    this.isFissural = false;
    this.isMediastinal = false;
    this.sizeMaxWidthInMm = null;
    this.secondPlaneInMm = null;
    this.thirdPlaneInMm = null;
    this.differentialDiagnosis01 = SoftPartsDiagnosisTypeEnum.None;
    this.isSuspected = false;
    this.differentialDiagnosis02 = SoftPartsDiagnosisTypeEnum.None;
    this.isSubordinated = false;
    this.differentialDiagnosis03 = SoftPartsDiagnosisTypeEnum.None;
    this.isMoreThanOneLesion = false;
    this.abdomenLocalizationType = AbdomenLocalizationTypeEnum.None;
    this.abdomenClassificationType = AbdomenClassificationTypeEnum.None;
    this.siteMaxWidthInMm = null;
    this.averageDensityInHU = null;
    this.distributionType = DistributionTypeEnum.None;
    this.qualityType = QualityTypeEnum.None;
    this.isCoagulum = false;
    this.isGasInclusions = false;
    this.isCMEnrichingCapsule = false;
    this.isSedimentation = false;
    this.isSplitPleuraSign = false;
    this.chestWallAngleType = ChestWallAngleTypeEnum.None;
    this.pleuralMassType = PleuralMassTypeEnum.None;
    this.isCircumferentialSoftTissueAugmentation = false;
    this.isCircumferentialSoftTissueAugmentationRight = false;
    this.isCircumferentialSoftTissueAugmentationLeft = false;
    this.isCloakPleuralEffusion = false;
    this.pleuralThickeningLocalizationType = PleuralThickeningLocalizationTypeEnum.None;
    this.isObtusedAngulationOfCostophrenicAngle = false;
    this.isNodularConfiguration = false;
    this.isLocoregionalOsteolysis = false;
    this.pneumothoraxType = PneumothoraxTypeEnum.None;
    this.extensionType = ExtensionTypeEnum.None;
    this.expansionMaxWidthInMm = null;
    this.isMediastinalshift = false;
    this.mediastinalshiftType = SoftPartsSiteTypeEnum.None;
    this.isAtelectasis = false;
    this.spineLocation = 'None';
    this.isNecroses = false;
    this.isPleura = false;
    this.isPericardium = false;
    this.isBones = false;
    this.isLungs = false;
    this.isMediastinum = false;
    this.isCutisThickening = false;
    this.isPressureErosionRib = false;
    this.volumeType = VolumeTypeEnum.None;
    this.lossOfVolumeSiteType = SoftPartsSiteTypeEnum.None;
    this.isAblatioRight = false;
    this.isAblatioLeft = false;
    this.isBreastAugmentationRight = false;
    this.isBreastAugmentationLeft = false;
    this.isThickened = false;
    this.thickenedCutisBreastLocation = 'None';
    this.isBlurred = false;
    this.blurredSiteType = SoftPartsSiteTypeEnum.None;
    this.isStove = false;
    this.stoveBreastLocation = 'None';
    this.stoveMaxDiameterAxialInMm = null;
    this.limitationType = SoftPartsLimitationTypeEnum.None;
    this.lymphNodesAxillaryType = LymphNodesAxillaryTypeEnum.None;
    this.isLymphNodeRight = false;
    this.rightMarginalShortAxisDiameter = null;
    this.isLymphNodeLeft = false;
    this.leftMarginalShortAxisDiameter = null;
    this.isRightLevel1 = false;
    this.isRightLevel2 = false;
    this.isRightLevel3 = false;
    this.isLeftLevel1 = false;
    this.isLeftLevel2 = false;
    this.isLeftLevel3 = false;
    this.isFocalLiverLesion = false;
    this.focalLiverLesionMaxDiameterAxialInMm = null;
    this.isDiffuseLiverLesion = false;
    this.diffuseLesionType = DiffuseLesionTypeEnum.None;
    this.isCholecystolithiasis = false;
    this.isWallThickeningOfTheGallBladder = false;
    this.isFocalPancreaticLesion = false;
    this.focalPancreaticLesionMaxDiameterAxialInMm = null;
    this.isDiffusePancreaticLesion = false;
    this.isFattyAtrophy = false;
    this.isAccumulationDuctusWirsungianus = false;
    this.isKidney = false;
    this.isKidneyFocalLesion = false;
    this.kidneyFocalLesionMaxDiameterInMm = null;
    this.isUrinaryRetention = false;
    this.isUrinaryRetentionRight = false;
    this.isUrinaryRetentionLeft = false;
    this.gradingType = GradingTypeEnum.None;
    this.isMassAdrenalGland = false;
    this.isMassAdrenalGlandRight = false;
    this.isMassAdrenalGlandLeft = false;
    this.massAdrenalGlandMaxDiameterInMm = null;
    this.massAdrenalGlandClassificationType = AbdomenClassificationTypeEnum.None;
    this.isSplenomegaly = false;
    this.isEnlargedAbdominalLymphNodes = false;
    this.diameterSADInMm = null;
    this.isPathological = false;
    this.isPathologicalMultiple = false;
    this.isPathologicalConglomerate = false;
    this.isPathologicalHiatusHernia = false;
  }
}
