namespace RadioReport.HeadCT.Domain.Enums.BasalNuclei
{
    public enum BasalNucleiDiagnosisType : byte
    {
        None = 0,
        AcuteStroke = 1,
        Ischemia = 2,
        Hemorrhage = 3,
        HypertensiveHemorrhage = 4,
        DeepVenousThrombosis = 5,
        AcuteHypertensiveEncephalopathyPres = 6,
        CavernousMalformation = 7,
        AVM = 8,
        Cadasil = 9,
        SusacSyndrome = 10,
        HypotensiveInfarction = 11,
        HemorrhagicNecrosis = 12,
        MoyaMoya = 13,
        IdiopathicBasalGangliaCalcification = 14,
        HuntingtonsDisease = 15,
        Vasculitis = 16,
        Encephalitis = 17,
        BehcetSDisease = 18,
        Adem = 19,
        Sle = 20,
        CreutzfeldJakobDisease = 21,
        Hypoglycemia = 22,
        DiabeticKetoacidosis = 23,
        UremicEncephalopathy = 24,
        HepaticEncephalopathy = 25,
        Hypothyroidism = 26,
        Hyperparathyroidism = 27,
        FahrSyndrome = 28,
        OsmoticDemyelinationSyndrome = 29,
        ToxicEncephalopathy = 30,
        MethanolIntoxication = 31,
        Hypoxia = 32,
        CarbonMonoxideIntoxication = 33,
        WilsonsDisease = 34,
        WernickeEncephalopathy = 35,
        MelasSyndrome = 36,
        BenignLesionNotFurtherSpecified = 37,
        MalignantLesionNotFurtherSpecified = 38,
        UnknownEtiology = 39,
        Metastasis = 40,
        DiffuseAstrocytoma = 41,
        Glioma = 42,
        Glioblastoma = 43,
        PrimaryCNSLymphoma = 44,
        Germinoma = 45,
        EnlargedPerivascularSpaces = 46,
        CerebralHemorrhagicContusion = 47,
        ShearStressInducedBleeding = 48,
        ChemotherapyAssociatedChanges = 49,
        PostradiationChanges = 50,
        StatusEpilepticus = 51
    }
}
