export enum LungInterstitiumDiagnosisTypeEnum {
  None = 'None',
  ILDKnownOrigin = 'ILDKnownOrigin',
  IdiopathicInterstitialPneumopathy = 'IdiopathicInterstitialPneumopathy',
  ILDGranulomatous = 'ILDGranulomatous',
  ILDOtherTypes = 'ILDOtherTypes',
  Bronchitis = 'Bronchitis',
  Bronchiolitis = 'Bronchiolitis',
  FungalPneumonia = 'FungalPneumonia',
  OrganizingPneumonia = 'OrganizingPneumonia',
  MiliaryTuberculosis = 'MiliaryTuberculosis',
  Metastases = 'Metastases',
  BronchioloalveolarCarcinoma = 'BronchioloalveolarCarcinoma',
  LymphangiosisCarcinomatosa = 'LymphangiosisCarcinomatosa',
  PulmonaryEdema = 'PulmonaryEdema',
  Haemorrhage = 'Haemorrhage',
  PulmonaryVenoOcclusiveDisease = 'PulmonaryVenoOcclusiveDisease',
  Amyloidosis = 'Amyloidosis',
  PulmonaryAlveolarProteinosis = 'PulmonaryAlveolarProteinosis',
  IdiopathicPleuroparenchymalFibroelastosis = 'IdiopathicPleuroparenchymalFibroelastosis',
  CombinedPulmonaryFibrosisAndEmphysemaSyndrome = 'CombinedPulmonaryFibrosisAndEmphysemaSyndrome',
  CysticFibrosis = 'CysticFibrosis',
  COPD = 'COPD'
}
