import { ReportModelBase } from '@models/report-model-base';
import { BiopsyTypeEnum } from '@enums/thoraxCT/summary/biopsy-type.enum';
import { CtFollowUpTypeEnum } from '@enums/thoraxCT/summary/ct-follow-up-type.enum';
import { EvaluationInterdisciplinaryBoardTypeEnum } from '@enums/thoraxCT/summary/evaluation-interdisciplinary-board-type.enum';
import { TStagingLevelTypeEnum } from '@enums/thoraxCT/summary/TStaging-level-type.enum';
import { NStagingLevelTypeEnum } from '@enums/thoraxCT/summary/NStaging-level-type.enum';
import { ScenarioTypeEnum } from '@enums/thoraxCT/summary/scenario-type.enum';
import { Covid19CTGroupsTypeEnum } from '@enums/thoraxCT/summary/covid19-ct-groups-type.enum';
import { DynamicFindingsTypeEnum } from '@enums/thoraxCT/summary/dynamic-findings-type.enum';
import { TnStagingTypeEnum } from '@enums/thoraxCT/summary/tn-staging-type.enum';

export class SummaryApiModel extends ReportModelBase {
  isProcedure: boolean;
  isCTFollowUp: boolean;
  ctFollowUpType: CtFollowUpTypeEnum;
  isRecommendedBiopsy: boolean;
  biopsyType: BiopsyTypeEnum;
  isEvaluationOfInterdisciplinaryBoard: boolean;
  evaluationInterdisciplinaryBoardType: EvaluationInterdisciplinaryBoardTypeEnum;
  isComplementaryExamination: boolean;
  isCTAbdomen: boolean;
  isCTNeck: boolean;
  isMammographyAndBreastUltrasound: boolean;
  isMRIChest: boolean;
  isMRIAbdomen: boolean;
  isMRIThoracicSpine: boolean;
  isMRINeck: boolean;
  isCardiacDiagnostics: boolean;
  isCTAngiography: boolean;
  isCTPA: boolean;
  isPETCT: boolean;
  isSPECT: boolean;
  isBoneScan: boolean;
  isDynamicFindings: boolean;
  dynamicFindingsType: DynamicFindingsTypeEnum;
  isTNStaging: boolean;
  tnStagingType: TnStagingTypeEnum;
  tStagingLevelType: TStagingLevelTypeEnum;
  nStagingLevelType: NStagingLevelTypeEnum;
  numberOfRoundHearths: number;
  isLungRADS: boolean;
  signalType: string;
  scenarioType: ScenarioTypeEnum;
  isRiskCalculator: boolean;
  cancerProbability: number;
  isCOVID19CTGroups: boolean;
  coviD19CTGroupsType: Covid19CTGroupsTypeEnum;

  constructor() {
    super();
    this.isProcedure = false;
    this.isCTFollowUp = false;
    this.ctFollowUpType = CtFollowUpTypeEnum.None;
    this.isRecommendedBiopsy = false;
    this.biopsyType = BiopsyTypeEnum.None;
    this.isEvaluationOfInterdisciplinaryBoard = false;
    this.evaluationInterdisciplinaryBoardType = EvaluationInterdisciplinaryBoardTypeEnum.None;
    this.isComplementaryExamination = false;
    this.isCTAbdomen = false;
    this.isCTNeck = false;
    this.isMammographyAndBreastUltrasound = false;
    this.isMRIChest = false;
    this.isMRIAbdomen = false;
    this.isMRIThoracicSpine = false;
    this.isMRINeck = false;
    this.isCardiacDiagnostics = false;
    this.isCTAngiography = false;
    this.isCTPA = false;
    this.isPETCT = false;
    this.isSPECT = false;
    this.isBoneScan = false;
    this.isDynamicFindings = false;
    this.dynamicFindingsType = DynamicFindingsTypeEnum.None;
    this.isTNStaging = false;
    this.tnStagingType = TnStagingTypeEnum.None;
    this.tStagingLevelType = TStagingLevelTypeEnum.None;
    this.nStagingLevelType = NStagingLevelTypeEnum.None;
    this.numberOfRoundHearths = null;
    this.isLungRADS = false;
    this.signalType = 'None';
    this.scenarioType = ScenarioTypeEnum.None;
    this.isRiskCalculator = false;
    this.cancerProbability = null;
    this.isCOVID19CTGroups = false;
    this.coviD19CTGroupsType = Covid19CTGroupsTypeEnum.None;
  }
}
