export enum SoftPartsDiagnosisTypeEnum {
  None = 'None',
  BenignLesion = 'BenignLesion',
  MalignantLesion = 'MalignantLesion',
  DignityUnclear = 'DignityUnclear',
  GanglionCyst = 'GanglionCyst',
  Lipoma = 'Lipoma',
  Hemangioma = 'Hemangioma',
  VascularMalformation = 'VascularMalformation',
  Neurom = 'Neurom',
  Schwannoma = 'Schwannoma',
  Neurofibroma = 'Neurofibroma',
  EpidermalCyst = 'EpidermalCyst',
  TendonSheathFibroma = 'TendonSheathFibroma',
  TenosynovialGiantCellTumor = 'TenosynovialGiantCellTumor',
  Pilomatrixoma = 'Pilomatrixoma',
  NodularFasciitis = 'NodularFasciitis',
  SoftTissueSarcoma = 'SoftTissueSarcoma',
  SquamousCellCarcinoma = 'SquamousCellCarcinoma',
  MalignantPeripheralNerve = 'MalignantPeripheralNerve',
  MalignantMelanoma = 'MalignantMelanoma',
  SynovialHaemangioma = 'SynovialHaemangioma',
  SynovialChondromatosis = 'SynovialChondromatosis',
  VillonodularSynovitis = 'VillonodularSynovitis',
  SynovialSarcoma = 'SynovialSarcoma',
  HemochromatoticArthropathy = 'HemochromatoticArthropathy',
  TophoseGout = 'TophoseGout'
}
