export enum AssociatedCausalFindingsTypeEnum {
  None = 'None',
  Urolithiasis = 'Urolithiasis',
  TraumaBbloodClot = 'TraumaBbloodClot',
  Endometriosis = 'Endometriosis',
  Papilloma = 'Papilloma',
  Metastasis = 'Metastasis',
  RenalPelvicTumor = 'RenalPelvicTumor',
  UreteralTumor = 'UreteralTumor',
  Lymphocele = 'Lymphocele',
  Urinoma = 'Urinoma',
  EnlargedUterus = 'EnlargedUterus',
  Aneurysm = 'Aneurysm',
  Hematoma = 'Hematoma',
  Abscess = 'Abscess',
  InflammatoryIntestinalConvolute = 'InflammatoryIntestinalConvolute',
  KinkKidneyTransplant = 'KinkKidneyTransplant',
  Lymphoma = 'Lymphoma',
  PelvicTumor = 'PelvicTumor',
  RetroperitonealMass = 'RetroperitonealMass',
  RetroperitonealFibrosis = 'RetroperitonealFibrosis',
  AberrantVessels = 'AberrantVessels',
  UreteralAnomaly = 'UreteralAnomaly',
  SubpelvicStenosis = 'SubpelvicStenosis',
  HorseshoeKidney = 'HorseshoeKidney',
  Nephroptosis = 'Nephroptosis',
  UreteralOutletStenosis = 'UreteralOutletStenosis'
}
