import { FacialSkullFindingBaseApiModel } from '@models/headMRT/api/facial-skull/facial-skull-finding-base-api.model';
import { DescriptionTypeEnum } from '@enums/shared/description-type.enum';
import { SideTypeEnum } from '@enums/headMRT/common/side-type.enum';
import { SymmetryTypeEnum } from '@enums/headMRT/facial-skull/symmetry-type.enum';
import { FacialSkullDiagnosisTypeEnum } from '@enums/headMRT/facial-skull/facial-skull-diagnosis-type.enum';
import { ChandlerClassificationFullTypeEnum } from '@enums/headMRT/facial-skull/Orbita/chandler-classification-full-type.enum';
import { OrbitaDiagnosisTypeEnum } from '@enums/headMRT/facial-skull/Orbita/orbita-diagnosis-type.enum';
import { LevelTypeEnum } from '@enums/headMRT/facial-skull/ParanasalSinusesVariant/level-type.enum';
import { AssessmentTypeEnum } from '@enums/headMRT/facial-skull/ParanasalSinusesVariant/assessment-type.enum';
import { ConchaeTypeEnum } from '@enums/headMRT/facial-skull/ParanasalSinuses/conchae-type.enum';
import { ChandlerClassificationTypeEnum } from '@enums/headMRT/facial-skull/ParanasalSinuses/chandler-classification-type.enum';
import { ParanasalSinusesDiagnosisTypeEnum } from '@enums/headMRT/facial-skull/ParanasalSinuses/paranasal-sinuses-diagnosis-type.enum';
import { OralCavityDiagnosisTypeEnum } from '@enums/headMRT/facial-skull/OralCavity/oral-cavity-diagnosis-type.enum';
import { JawTeethTypeEnum } from '@enums/headMRT/facial-skull/JawTeeth/jaw-teeth-type.enum';
import { CharacterizationTypeEnum } from '@enums/headMRT/facial-skull/JawTeeth/characterization-type.enum';
import { OtherNonOdontogenicCystTypeEnum } from '@enums/headMRT/facial-skull/JawTeeth/other-non-odontogenic-cyst-type.enum';
import { JawTeethDiagnosisTypeEnum } from '@enums/headMRT/facial-skull/JawTeeth/jaw-teeth-diagnosis-type.enum';
import { ClassificationTypeEnum } from '@enums/headMRT/facial-skull/JawTeeth/classification-type.enum';
import { DiscDisplacementTypeEnum } from '@enums/headMRT/facial-skull/JawTeeth/disc-displacement-type.enum';
import { OsseousChangesTypeEnum } from '@enums/headMRT/facial-skull/JawTeeth/osseous-changes-type.enum';
import { JawTeethAssessmentTypeEnum } from '@enums/headMRT/facial-skull/JawTeeth/jaw-teeth-assessment-type.enum';
import { SalivaryGlandsDiagnosisTypeEnum } from '@enums/headMRT/facial-skull/SalivaryGlands/salivary-glands-diagnosis-type.enum';
import { CorticalisTypeEnum } from '@enums/headMRT/facial-skull/Skull/corticalis-type.enum';
import { ToothAnomaliesTypeEnum } from '@enums/headMRT/facial-skull/JawTeeth/tooth-anomalies-type.enum';

export class FacialSkullFindingApiModel extends FacialSkullFindingBaseApiModel {
  descriptionType: DescriptionTypeEnum;
  isRight: boolean;
  isLeft: boolean;
  sideType: SideTypeEnum;

  symmetryType: SymmetryTypeEnum;
  isMusculatureOfFloorOfMouth: boolean;
  isMaxilla: boolean;
  isFrontalBone: boolean;
  isZygomaticBone: boolean;
  isSphenoidBone: boolean;
  isMaxillaryBone: boolean;
  isEthmoidBone: boolean;
  isOrbitalFloor: boolean;
  isLaminaCribrosa: boolean;
  isInfraorbitalNerve: boolean;
  maxDiameter: number;
  size: number;
  size2ndPlane: number;
  size3rdPlane: number;
  isFat: boolean;
  isSolidParts: boolean;
  isNodularParts: boolean;
  isSepta: boolean;
  isPerineural: boolean;
  isAlongANerveCord: boolean;
  isIntraorbitalSpread: boolean;
  isDiffuse: boolean;
  isEccentric: boolean;
  isThickeningOfTheCalotte: boolean;
  maxDiameterMucosa: number;
  isLymphadenopathy: boolean;
  isWhartonDuctOcclusion: boolean;
  isUnilateralMuscleHypotonia: boolean;
  isMuscularAtrophy: boolean;
  isMuscleFattyDegeneration: boolean;
  isThickeningOfTheMaxillarySinusWall: boolean;
  isTemporalBoneApexAbscess: boolean;
  isSinusThrombosis: boolean;
  isHydrocephalus: boolean;
  abscessMaxDiameter: number;
  differentialDiagnosis1Type: FacialSkullDiagnosisTypeEnum;
  isSuspicionOf: boolean;
  differentialDiagnosis2Type: FacialSkullDiagnosisTypeEnum;
  isSubordinate: boolean;
  differentialDiagnosis3Type: FacialSkullDiagnosisTypeEnum;
  isMoreThan1LesionOfTheSameEntity: boolean;

  isAnteriorCranialFossa: boolean;
  isSphenoidBoneAnterior: boolean;
  isOlfactoryNerveI: boolean;
  isTemporalBoneMiddle: boolean;
  isSuperiorOrbitalFissure: boolean;
  isMeningeaMediaArtery: boolean;
  isInternalCarotidArtery: boolean;
  isOpticNerveII: boolean;
  isOculomotorNerveIII: boolean;
  isTrochlearNerveIV: boolean;
  isOphthalmicNerveV1: boolean;
  isMaxillaryNerveV2: boolean;
  isNMandibularisV3: boolean;
  isMeatusAcusticusInternus: boolean;
  isOccipitalBone: boolean;
  isFacialNerveVII: boolean;
  isVestibulochochlearNerveVIII: boolean;
  isGlossopharyngealNerveIX: boolean;
  isVagusNerveX: boolean;
  isAccessoryNerveXI: boolean;
  isHypoglossalNerveXII: boolean;
  isInternalJugularVein: boolean;
  isSigmoidSinus: boolean;

  isDuctusEndolymphaticus: boolean;
  isSaccusEndolymphaticus: boolean;
  isExternalAcousticCanalMeatusAcusticusExternus: boolean;
  isTemporalBoneApex: boolean;
  isAuricle: boolean;
  isForamenStylomastoideum: boolean;
  isTubaAuditiva: boolean;
  isFacialNerveCanal: boolean;

  chandlerClassificationLocalizationType: ChandlerClassificationFullTypeEnum;
  isLacrimalBone: boolean;
  isInfraorbitalGroove: boolean;
  isIntraconalSpace: boolean;
  isExtraconalSpace: boolean;
  isBulbusOculi: boolean;
  isAnteriorChamber: boolean;
  isLens: boolean;
  isPosteriorChamber: boolean;
  isCiliaryBody: boolean;
  isVitreousBody: boolean;
  isSclera: boolean;
  isOpticNerveIIOther: boolean;
  isObliquusInferiorMuscle: boolean;
  isFissuraOrbitalisSuperior: boolean;
  isFissuraOrbitalisInferior: boolean;
  isTrigeminalNerveV: boolean;
  isMeningeaRecurrensArtery: boolean;
  isSuperiorOphthalmicVein: boolean;
  isLacrimalGland: boolean;
  isEdema: boolean;
  maxDiameterMuscleBelly: number;
  isIntracranialSpread: boolean;
  isDiffuseFusiform: boolean;
  isRetinalDetachment: boolean;
  orbitaDiagnosis1Type: OrbitaDiagnosisTypeEnum;
  orbitaDiagnosis2Type: OrbitaDiagnosisTypeEnum;
  orbitaDiagnosis3Type: OrbitaDiagnosisTypeEnum;
  chandlerClassificationDiagnosisType: ChandlerClassificationFullTypeEnum;

  isDeviatedNasalSeptum: boolean;
  isConchaBullosa: boolean;
  isConchaBullosaRight: boolean;
  isConchaBullosaLeft: boolean;
  levelType: LevelTypeEnum;
  conchaBullosaSize: number;
  conchaBullosa2NdPlane: number;
  conchaBullosa3RdPlane: number;
  isInfraorbitalHallerCell: boolean;
  isInfraorbitalHallerRight: boolean;
  isInfraorbitalHallerLeft: boolean;
  infraorbitalHallerCellSize: number;
  infraorbitalHallerCell2NdPlane: number;
  infraorbitalHallerCell3RdPlane: number;
  isOnodiCells: boolean;
  isOnodiCellsRight: boolean;
  isOnodiCellsLeft: boolean;
  onodiCellsSize: number;
  onodiCells2NdPlane: number;
  onodiCells3RdPlane: number;
  isAggerNasiCells: boolean;
  isAggerNasiRight: boolean;
  isAggerNasiLeft: boolean;
  isAggerNasiMedian: boolean;
  aggerNasiCellsSize: number;
  aggerNasiCells2NdPlane: number;
  aggerNasiCells3RdPlane: number;
  isSkullBase: boolean;
  isAsymmetryOfTheSkullBase: boolean;
  isDehiscenceOfTheSkullBase: boolean;
  assessmentType: AssessmentTypeEnum;

  conchaeType: ConchaeTypeEnum;
  isPalatineBone: boolean;
  isNasalBone: boolean;
  isVomer: boolean;
  isEthmoidInfundibulum: boolean;
  isUncinateProcess: boolean;
  isHiatusSemilunaris: boolean;
  isNasofrontalDuct: boolean;
  isOstiomeatalComplex: boolean;
  isLaminaePapyraceae: boolean;
  isCavernosusSinus: boolean;
  isNasalSeptum: boolean;
  isInStructuresOutsideSinus: boolean;
  isFungusBall: boolean;
  maxDiameterFungusBall: number;
  isThickeningOfTheMaxillarySinusWalls: boolean;
  isCervicalLymphadenopathy: boolean;
  isOrbitalComplications: boolean;
  chandlerClassificationType: ChandlerClassificationTypeEnum;
  isBrainAbscess: boolean;
  maxDiameterBrainAbscess: number;
  isSubduralEmpyema: boolean;
  maxDiameterSubduralEmpyema: number;
  isEpiduralAbscess: boolean;
  maxDiameterEpiduralAbscess: number;
  paranasalSinusesDiagnosis1Type: ParanasalSinusesDiagnosisTypeEnum;
  paranasalSinusesDiagnosis2Type: ParanasalSinusesDiagnosisTypeEnum;
  paranasalSinusesDiagnosis3Type: ParanasalSinusesDiagnosisTypeEnum;

  isHardPalate: boolean;
  isSoftPalate: boolean;
  isTrigonumSubmandibulare: boolean;
  isUvula: boolean;
  isPalatineTonsils: boolean;
  isConstrictorPharyngisSuperiorMuscle: boolean;
  isMaxillaAlveolarRidge: boolean;
  isMandibularBone: boolean;
  isUpperLip: boolean;
  isUpperLipAlveolarRidge: boolean;
  isLowerLip: boolean;
  isOropharynx: boolean;
  isPosteriorWall: boolean;
  isLateralWall: boolean;
  isPeritonsillarSpace: boolean;
  isLateralPharyngealWall: boolean;
  isFloor: boolean;
  isBaseOfTongue: boolean;
  isFrenulumLinguae: boolean;
  isTongueBaseTonsil: boolean;
  isEpiglottisUpperMargin: boolean;
  isValleculae: boolean;
  isInflitrationMusculatureOfFloorOfMouth: boolean;
  isOsteomyelitisMaxilla: boolean;
  oralCavityDiagnosis1Type: OralCavityDiagnosisTypeEnum;
  oralCavityDiagnosis2Type: OralCavityDiagnosisTypeEnum;
  oralCavityDiagnosis3Type: OralCavityDiagnosisTypeEnum;

  isRamusMandibulae: boolean;
  isCondylarProcess: boolean;
  isCoronoidProcess: boolean;
  isCorpusMandibulae: boolean;
  isAlveolarRidge: boolean;
  isCorpusMaxillae: boolean;
  isAlveolarProcess: boolean;
  isRightUpperJaw: boolean;
  is11: boolean;
  is12: boolean;
  is13: boolean;
  is14: boolean;
  is15: boolean;
  is16: boolean;
  is17: boolean;
  is18: boolean;
  isLeftUpperJaw: boolean;
  is21: boolean;
  is22: boolean;
  is23: boolean;
  is24: boolean;
  is25: boolean;
  is26: boolean;
  is27: boolean;
  is28: boolean;
  isRightLowerJaw: boolean;
  is31: boolean;
  is32: boolean;
  is33: boolean;
  is34: boolean;
  is35: boolean;
  is36: boolean;
  is37: boolean;
  is38: boolean;
  isLeftLowerJaw: boolean;
  is41: boolean;
  is42: boolean;
  is43: boolean;
  is44: boolean;
  is45: boolean;
  is46: boolean;
  is47: boolean;
  is48: boolean;

  jawTeethType: JawTeethTypeEnum;
  toothAnomaliesType: ToothAnomaliesTypeEnum;
  characterizationType: CharacterizationTypeEnum;
  otherNonOdontogenicCystType: OtherNonOdontogenicCystTypeEnum;
  jawTeethDiagnosisType: JawTeethDiagnosisTypeEnum;
  classificationType: ClassificationTypeEnum;
  isDiscDisplacement: boolean;
  discDisplacementType: DiscDisplacementTypeEnum;
  isDiscusReduction: boolean;
  isDiscusReductionSuspicionOf: boolean;
  isDiscDeformation: boolean;
  isDiscDeformationDistinct: boolean;
  isDiscDeformationPerforation: boolean;
  isDiscDeformationResorption: boolean;
  isDiscDeformationSuspicionOf: boolean;
  isOsseousChanges: boolean;
  osseousChangesType: OsseousChangesTypeEnum;
  isBoneEdema: boolean;
  isPoorlyDemarcatedOsteolysis: boolean;
  isBoneMarrowContrastEnhancement: boolean;
  isSequester: boolean;
  sequesterMaxDiameter: number;
  sequesterSize2ndPlane: number;
  sequesterSize3rdPlane: number;
  isPeriostealReaction: boolean;
  isSoftTissueFistula: boolean;
  jawTeethAssessmentType: JawTeethAssessmentTypeEnum;

  isDeepMedialLobe: boolean;
  isParotidDuctStenonSDuct: boolean;
  isFacialNerve: boolean;
  isSubmandibularGland: boolean;
  isSubmandibularFossa: boolean;
  isSubmandibularMandible: boolean;
  isSubmandibularDuctWhartonSDuct: boolean;
  isCarunculaSublingualis: boolean;
  isSublingualGland: boolean;
  isMinorSalivaryGlands: boolean;
  salivaryGlandsDiagnosis1Type: SalivaryGlandsDiagnosisTypeEnum;
  salivaryGlandsDiagnosis2Type: SalivaryGlandsDiagnosisTypeEnum;

  isFrontal: boolean;
  isParietal: boolean;
  isOccipital: boolean;
  isTemporal: boolean;
  isSubperiosteal: boolean;
  corticalisType: CorticalisTypeEnum;
  isGaleaHaematoma: boolean;
  isCephalhaematoma: boolean;

  constructor() {
    super();

    this.descriptionType = DescriptionTypeEnum.None;
    this.isRight = false;
    this.isLeft = false;
    this.sideType = SideTypeEnum.None;

    this.symmetryType = SymmetryTypeEnum.None;
    this.isMusculatureOfFloorOfMouth = false;
    this.isMaxilla = false;
    this.isFrontalBone = false;
    this.isZygomaticBone = false;
    this.isSphenoidBone = false;
    this.isMaxillaryBone = false;
    this.isEthmoidBone = false;
    this.isOrbitalFloor = false;
    this.isLaminaCribrosa = false;
    this.isInfraorbitalNerve = false;
    this.maxDiameter = null;
    this.size = null;
    this.size2ndPlane = null;
    this.size3rdPlane = null;
    this.isFat = false;
    this.isSolidParts = false;
    this.isNodularParts = false;
    this.isSepta = false;

    this.isPerineural = false;
    this.isAlongANerveCord = false;
    this.isIntraorbitalSpread = false;
    this.isDiffuse = false;
    this.isEccentric = false;
    this.isThickeningOfTheCalotte = false;
    this.maxDiameterMucosa = null;
    this.isLymphadenopathy = false;
    this.isWhartonDuctOcclusion = false;
    this.isUnilateralMuscleHypotonia = false;
    this.isMuscularAtrophy = false;
    this.isMuscleFattyDegeneration = false;
    this.isThickeningOfTheMaxillarySinusWall = false;
    this.isTemporalBoneApexAbscess = false;
    this.isSinusThrombosis = false;
    this.isHydrocephalus = false;
    this.abscessMaxDiameter = null;
    this.differentialDiagnosis1Type = FacialSkullDiagnosisTypeEnum.None;
    this.isSuspicionOf = false;
    this.differentialDiagnosis2Type = FacialSkullDiagnosisTypeEnum.None;
    this.isSubordinate = false;
    this.differentialDiagnosis3Type = FacialSkullDiagnosisTypeEnum.None;
    this.isMoreThan1LesionOfTheSameEntity = false;

    this.isAnteriorCranialFossa = false;
    this.isSphenoidBoneAnterior = false;
    this.isOlfactoryNerveI = false;
    this.isTemporalBoneMiddle = false;
    this.isSuperiorOrbitalFissure = false;
    this.isMeningeaMediaArtery = false;
    this.isInternalCarotidArtery = false;
    this.isOpticNerveII = false;
    this.isOculomotorNerveIII = false;
    this.isTrochlearNerveIV = false;
    this.isOphthalmicNerveV1 = false;
    this.isMaxillaryNerveV2 = false;
    this.isNMandibularisV3 = false;
    this.isMeatusAcusticusInternus = false;
    this.isOccipitalBone = false;
    this.isFacialNerveVII = false;
    this.isVestibulochochlearNerveVIII = false;
    this.isGlossopharyngealNerveIX = false;
    this.isVagusNerveX = false;
    this.isAccessoryNerveXI = false;
    this.isHypoglossalNerveXII = false;
    this.isInternalJugularVein = false;
    this.isSigmoidSinus = false;

    this.isDuctusEndolymphaticus = false;
    this.isSaccusEndolymphaticus = false;
    this.isExternalAcousticCanalMeatusAcusticusExternus = false;
    this.isTemporalBoneApex = false;
    this.isAuricle = false;
    this.isForamenStylomastoideum = false;
    this.isTubaAuditiva = false;
    this.isFacialNerveCanal = false;

    this.chandlerClassificationLocalizationType = ChandlerClassificationFullTypeEnum.None;
    this.isLacrimalBone = false;
    this.isInfraorbitalGroove = false;
    this.isIntraconalSpace = false;
    this.isExtraconalSpace = false;
    this.isBulbusOculi = false;
    this.isAnteriorChamber = false;
    this.isLens = false;
    this.isPosteriorChamber = false;
    this.isCiliaryBody = false;
    this.isVitreousBody = false;
    this.isSclera = false;
    this.isOpticNerveIIOther = false;
    this.isObliquusInferiorMuscle = false;
    this.isFissuraOrbitalisSuperior = false;
    this.isFissuraOrbitalisInferior = false;
    this.isTrigeminalNerveV = false;
    this.isMeningeaRecurrensArtery = false;
    this.isSuperiorOphthalmicVein = false;
    this.isLacrimalGland = false;
    this.isEdema = false;
    this.maxDiameterMuscleBelly = null;
    this.isIntracranialSpread = false;
    this.isDiffuseFusiform = false;
    this.isRetinalDetachment = false;
    this.orbitaDiagnosis1Type = OrbitaDiagnosisTypeEnum.None;
    this.orbitaDiagnosis2Type = OrbitaDiagnosisTypeEnum.None;
    this.orbitaDiagnosis3Type = OrbitaDiagnosisTypeEnum.None;
    this.chandlerClassificationDiagnosisType = ChandlerClassificationFullTypeEnum.None;

    this.isDeviatedNasalSeptum = false;
    this.isConchaBullosa = false;
    this.isConchaBullosaRight = false;
    this.isConchaBullosaLeft = false;
    this.levelType = LevelTypeEnum.None;
    this.conchaBullosaSize = null;
    this.conchaBullosa2NdPlane = null;
    this.conchaBullosa3RdPlane = null;
    this.isInfraorbitalHallerCell = false;
    this.isInfraorbitalHallerRight = false;
    this.isInfraorbitalHallerLeft = false;
    this.infraorbitalHallerCellSize = null;
    this.infraorbitalHallerCell2NdPlane = null;
    this.infraorbitalHallerCell3RdPlane = null;
    this.isOnodiCells = false;
    this.isOnodiCellsRight = false;
    this.isOnodiCellsLeft = false;
    this.onodiCellsSize = null;
    this.onodiCells2NdPlane = null;
    this.onodiCells3RdPlane = null;
    this.isAggerNasiCells = false;
    this.isAggerNasiRight = false;
    this.isAggerNasiLeft = false;
    this.isAggerNasiMedian = false;
    this.aggerNasiCellsSize = null;
    this.aggerNasiCells2NdPlane = null;
    this.aggerNasiCells3RdPlane = null;
    this.isSkullBase = false;
    this.isAsymmetryOfTheSkullBase = false;
    this.isDehiscenceOfTheSkullBase = false;
    this.assessmentType = AssessmentTypeEnum.None;

    this.conchaeType = ConchaeTypeEnum.None;
    this.isPalatineBone = false;
    this.isNasalBone = false;
    this.isVomer = false;
    this.isEthmoidInfundibulum = false;
    this.isUncinateProcess = false;
    this.isHiatusSemilunaris = false;
    this.isNasofrontalDuct = false;
    this.isOstiomeatalComplex = false;
    this.isLaminaePapyraceae = false;
    this.isCavernosusSinus = false;
    this.isNasalSeptum = false;
    this.isInStructuresOutsideSinus = false;
    this.isFungusBall = false;
    this.maxDiameterFungusBall = null;
    this.isThickeningOfTheMaxillarySinusWalls = false;
    this.isCervicalLymphadenopathy = false;
    this.isOrbitalComplications = false;
    this.chandlerClassificationType = ChandlerClassificationTypeEnum.None;
    this.isBrainAbscess = false;
    this.maxDiameterBrainAbscess = null;
    this.isSubduralEmpyema = false;
    this.maxDiameterSubduralEmpyema = null;
    this.isEpiduralAbscess = false;
    this.maxDiameterEpiduralAbscess = null;
    this.paranasalSinusesDiagnosis1Type = ParanasalSinusesDiagnosisTypeEnum.None;
    this.paranasalSinusesDiagnosis2Type = ParanasalSinusesDiagnosisTypeEnum.None;
    this.paranasalSinusesDiagnosis3Type = ParanasalSinusesDiagnosisTypeEnum.None;

    this.isHardPalate = false;
    this.isSoftPalate = false;
    this.isTrigonumSubmandibulare = false;
    this.isUvula = false;
    this.isPalatineTonsils = false;
    this.isConstrictorPharyngisSuperiorMuscle = false;
    this.isMaxillaAlveolarRidge = false;
    this.isMandibularBone = false;
    this.isUpperLip = false;
    this.isUpperLipAlveolarRidge = false;
    this.isLowerLip = false;
    this.isOropharynx = false;
    this.isPosteriorWall = false;
    this.isLateralWall = false;
    this.isPeritonsillarSpace = false;
    this.isLateralPharyngealWall = false;
    this.isFloor = false;
    this.isBaseOfTongue = false;
    this.isFrenulumLinguae = false;
    this.isTongueBaseTonsil = false;
    this.isEpiglottisUpperMargin = false;
    this.isValleculae = false;
    this.isInflitrationMusculatureOfFloorOfMouth = false;
    this.isOsteomyelitisMaxilla = false;
    this.oralCavityDiagnosis1Type = OralCavityDiagnosisTypeEnum.None;
    this.oralCavityDiagnosis2Type = OralCavityDiagnosisTypeEnum.None;
    this.oralCavityDiagnosis3Type = OralCavityDiagnosisTypeEnum.None;

    this.isRamusMandibulae = false;
    this.isCondylarProcess = false;
    this.isCoronoidProcess = false;
    this.isCorpusMandibulae = false;
    this.isAlveolarRidge = false;
    this.isCorpusMaxillae = false;
    this.isAlveolarProcess = false;
    this.isRightUpperJaw = false;
    this.is11 = false;
    this.is12 = false;
    this.is13 = false;
    this.is14 = false;
    this.is15 = false;
    this.is16 = false;
    this.is17 = false;
    this.is18 = false;
    this.isLeftUpperJaw = false;
    this.is21 = false;
    this.is22 = false;
    this.is23 = false;
    this.is24 = false;
    this.is25 = false;
    this.is26 = false;
    this.is27 = false;
    this.is28 = false;
    this.isRightLowerJaw = false;
    this.is31 = false;
    this.is32 = false;
    this.is33 = false;
    this.is34 = false;
    this.is35 = false;
    this.is36 = false;
    this.is37 = false;
    this.is38 = false;
    this.isLeftLowerJaw = false;
    this.is41 = false;
    this.is42 = false;
    this.is43 = false;
    this.is44 = false;
    this.is45 = false;
    this.is46 = false;
    this.is47 = false;
    this.is48 = false;

    this.jawTeethType = JawTeethTypeEnum.None;
    this.toothAnomaliesType = ToothAnomaliesTypeEnum.None;
    this.characterizationType = CharacterizationTypeEnum.None;
    this.otherNonOdontogenicCystType = OtherNonOdontogenicCystTypeEnum.None;
    this.jawTeethDiagnosisType = JawTeethDiagnosisTypeEnum.None;
    this.classificationType = ClassificationTypeEnum.None;
    this.isDiscDisplacement = false;
    this.discDisplacementType = DiscDisplacementTypeEnum.None;
    this.isDiscusReduction = false;
    this.isDiscusReductionSuspicionOf = false;
    this.isDiscDeformation = false;
    this.isDiscDeformationDistinct = false;
    this.isDiscDeformationPerforation = false;
    this.isDiscDeformationResorption = false;
    this.isDiscDeformationSuspicionOf = false;
    this.isOsseousChanges = false;
    this.osseousChangesType = OsseousChangesTypeEnum.None;
    this.isBoneEdema = false;
    this.isPoorlyDemarcatedOsteolysis = false;
    this.isBoneMarrowContrastEnhancement = false;
    this.isSequester = false;
    this.sequesterMaxDiameter = null;
    this.sequesterSize2ndPlane = null;
    this.sequesterSize3rdPlane = null;
    this.isPeriostealReaction = false;
    this.isSoftTissueFistula = false;
    this.jawTeethAssessmentType = JawTeethAssessmentTypeEnum.None;

    this.isDeepMedialLobe = false;
    this.isParotidDuctStenonSDuct = false;
    this.isFacialNerve = false;
    this.isSubmandibularGland = false;
    this.isSubmandibularFossa = false;
    this.isSubmandibularMandible = false;
    this.isSubmandibularDuctWhartonSDuct = false;
    this.isCarunculaSublingualis = false;
    this.isSublingualGland = false;
    this.isMinorSalivaryGlands = false;
    this.salivaryGlandsDiagnosis1Type = SalivaryGlandsDiagnosisTypeEnum.None;
    this.salivaryGlandsDiagnosis2Type = SalivaryGlandsDiagnosisTypeEnum.None;

    this.isFrontal = false;
    this.isParietal = false;
    this.isOccipital = false;
    this.isTemporal = false;
    this.isSubperiosteal = false;
    this.corticalisType = CorticalisTypeEnum.None;
    this.isGaleaHaematoma = false;
    this.isCephalhaematoma = false;
  }
}
