export enum DifferentialDiagnosisTypeEnum {
  None = 'None',
  BenignLesionNotFurtherSpecified = 'BenignLesionNotFurtherSpecified',
  MalignantLesionNotFurtherSpecified = 'MalignantLesionNotFurtherSpecified',
  DignityUnclear = 'DignityUnclear',
  Enchondroma = 'Enchondroma',
  Hemangioma = 'Hemangioma',
  VertebralHemangioma = 'VertebralHemangioma',
  BoneIslandOrEnostosis = 'BoneIslandOrEnostosis',
  IntraosseousLipoma = 'IntraosseousLipoma',
  IntraosseousCyst = 'IntraosseousCyst',
  FibrousDysplasia = 'FibrousDysplasia',
  OssifyingFibroma = 'OssifyingFibroma',
  AneurysmalBoneCyst = 'AneurysmalBoneCyst',
  OsteoidOsteoma = 'OsteoidOsteoma',
  Osteochondroma = 'Osteochondroma',
  Chondroblastoma = 'Chondroblastoma',
  Osteoblastoma = 'Osteoblastoma',
  BenignOdontogenicMass = 'BenignOdontogenicMass',
  Osteosarcoma = 'Osteosarcoma',
  Chondrosarcoma = 'Chondrosarcoma',
  Metastasis = 'Metastasis',
  Lymphoma = 'Lymphoma',
  MultipleMyeloma = 'MultipleMyeloma',
  MalignantOtontogenicMass = 'MalignantOtontogenicMass',
  Osteomyelitis = 'Osteomyelitis',
  BoneInfarction = 'BoneInfarction'
}
