import { SacroiliacjJointDiagnosisTypesEnum } from '@enums/spineMRT/sacroiliac-joint/sacroiliacj-joint-diagnosis-types.enum';
import { SacroiliacJointFindingTypesEnum } from '@enums/spineMRT/sacroiliac-joint/sacroiliac-joint-finding-types.enum';
import { DescriptionTypeEnum } from '@enums/shared/description-type.enum';
import { JointSurfaceSubTypesEnum } from '@enums/spineMRT/sacroiliac-joint/joint-surface-sub-types.enum';
import { SclerosisTypesEnum } from '@enums/spineMRT/sacroiliac-joint/sclerosis-types.enum';
import { SacroiliacJointEntheitisTypesEnum } from '@enums/spineMRT/sacroiliac-joint/sacroiliac-joint-entheitis-types.enum';
import { SacroiliacJointScoreApiModel } from '@models/spineMRT/api/sacroiliac-joint/sacroiliac-joint-score-api.model';
import { FindingBase } from '@models/shared/finding/finding.base';

export class SacroiliacJointFindingApiModel extends FindingBase {
  findingType: SacroiliacJointFindingTypesEnum;
  descriptionType: DescriptionTypeEnum;
  pelvisLocation: string;
  iKnowDifferentialDiagnosis01: SacroiliacjJointDiagnosisTypesEnum;
  isBoneBridges: boolean;
  isAnkylosis: boolean;
  isOsteophytes: boolean;
  jointSurfaceSubType: JointSurfaceSubTypesEnum;
  isErosions: boolean;
  isSurfaceNarrowing: boolean;
  isVacuumPhenomenon: boolean;
  isSubchondralCysts: boolean;
  isSubchondralSclerosis: boolean;
  sclerosisType: SclerosisTypesEnum;
  isFatDeposition: boolean;
  isEnthesitis: boolean;
  entheitisType: SacroiliacJointEntheitisTypesEnum;
  isSynovitis: boolean;
  isCmEnhancement: boolean;
  isJointSpaceWidening: boolean;
  isJointEffusion: boolean;
  isBoneMarrow: boolean;
  isSPARCCScore: boolean;
  score1: SacroiliacJointScoreApiModel;
  score2: SacroiliacJointScoreApiModel;
  score3: SacroiliacJointScoreApiModel;
  score4: SacroiliacJointScoreApiModel;
  score5: SacroiliacJointScoreApiModel;
  score6: SacroiliacJointScoreApiModel;
  sparccScore: number;
  isAbscess: boolean;
  maximumExpansion: number;
  isSoftTissue: boolean;
  iDescribeDifferentialDiagnosis01: SacroiliacjJointDiagnosisTypesEnum;
  differentialDiagnosis02: SacroiliacjJointDiagnosisTypesEnum;
  isSecondary: boolean;

  constructor() {
    super();
    this.findingType = SacroiliacJointFindingTypesEnum.None;
    this.descriptionType = DescriptionTypeEnum.None;
    this.pelvisLocation = 'None';
    this.iKnowDifferentialDiagnosis01 = SacroiliacjJointDiagnosisTypesEnum.None;
    this.isBoneBridges = false;
    this.isAnkylosis = false;
    this.isOsteophytes = false;
    this.jointSurfaceSubType = JointSurfaceSubTypesEnum.None;
    this.isErosions = false;
    this.isSurfaceNarrowing = false;
    this.isVacuumPhenomenon = false;
    this.isSubchondralCysts = false;
    this.isSubchondralSclerosis = false;
    this.sclerosisType = SclerosisTypesEnum.None;
    this.isFatDeposition = false;
    this.isEnthesitis = false;
    this.entheitisType = SacroiliacJointEntheitisTypesEnum.None;
    this.isSynovitis = false;
    this.isCmEnhancement = false;
    this.isJointSpaceWidening = false;
    this.isJointEffusion = false;
    this.isBoneMarrow = false;
    this.isSPARCCScore = false;
    this.score1 = new SacroiliacJointScoreApiModel();
    this.score2 = new SacroiliacJointScoreApiModel();
    this.score3 = new SacroiliacJointScoreApiModel();
    this.score4 = new SacroiliacJointScoreApiModel();
    this.score5 = new SacroiliacJointScoreApiModel();
    this.score6 = new SacroiliacJointScoreApiModel();
    this.sparccScore = null;
    this.isAbscess = false;
    this.maximumExpansion = null;
    this.isSoftTissue = false;
    this.iDescribeDifferentialDiagnosis01 = SacroiliacjJointDiagnosisTypesEnum.None;
    this.differentialDiagnosis02 = SacroiliacjJointDiagnosisTypesEnum.None;
    this.isSecondary = false;
  }
}
