export enum DiagnosisTypeEnum {
  None = 'None',
  BenignLesionNotFurtherSpecified = 'BenignLesionNotFurtherSpecified',
  MalignantLesionNotFurtherSpecified = 'MalignantLesionNotFurtherSpecified',
  DignityUnclear = 'DignityUnclear',
  GanglionCyst = 'GanglionCyst',
  Lipoma = 'Lipoma',
  Hemangioma = 'Hemangioma',
  VascularMalformation = 'VascularMalformation',
  Neuroma = 'Neuroma',
  Schwannoma = 'Schwannoma',
  Neurofibroma = 'Neurofibroma',
  EpidermalCyst = 'EpidermalCyst',
  TendonSheathFibroma = 'TendonSheathFibroma',
  TenosynovialGiantCellTumor = 'TenosynovialGiantCellTumor',
  Pilomatrixoma = 'Pilomatrixoma',
  FibrolipomatousHamartoma = 'FibrolipomatousHamartoma',
  NodularFasciitis = 'NodularFasciitis',
  SoftTissueSarcoma = 'SoftTissueSarcoma',
  SquamousCellCarcinoma = 'SquamousCellCarcinoma',
  MPNST = 'MPNST',
  MalignantMelanoma = 'MalignantMelanoma'
}
