namespace RadioReport.HeadMRT.Domain.Enums.BrainstemCranialNerves
{
    public enum BrainstemCranialNervesDiagnosisType : byte
    {
        None = 0,
        BenignLesionNotFurtherSpecified = 1,
        MalignantLesionNotFurtherSpecified = 2,
        DignityUnclear = 3,
        AcousticNeuroma = 4,
        Schwannoma = 5,
        PinealCyst = 6,
        Meningioma = 7,
        Epidermoid = 8,
        Ependymoma = 9,
        Neurofibroma = 10,
        Pinealocytoma = 11,
        Metastasis = 12,
        PilocyticAstrocytoma = 13,
        Glioma = 14,
        TectalGlioma = 15,
        Hemangioblastoma = 16,
        Lymphoma = 17,
        PNET = 18,
        Ischemia = 19,
        LacunarInfarction = 20,
        Hemorrhage = 21,
        VascularNerveContact = 22,
        CavernousMalformation = 23,
        VascularMalformation = 24,
        CapillaryTelangiectasia = 25,
        PercheronInfarction = 26,
        Neuritis = 27,
        ViralNeuritis = 28,
        PostviralNeuritis = 29,
        Vasculitis = 30,
        MultipleSclerosis = 31,
        NeuromyelitisOpticaNMOSD = 32,
        Neurosarcoidosis = 33,
        Encephalitis = 34,
        ADEM = 35,
        CMV = 36,
        HerpesZoster = 37,
        LymeDisease = 38,
        CLIPPERS = 39,
        Abscess = 40,
        Atrophy = 41,
        EnlargedPerivascularSpaces = 42,
        ProgressiveSupranuclearPalsy = 43,
        ParkinsonsDisease = 44,
        ALS = 45,
        WallersDegeneration = 46,
        IntraparenchymalHemorrhage = 47,
        AqueductStenosis = 48,
        Syringobulbia = 49,
        IntracranialHypertension = 50,
        AcuteHypertensiveEncephalopathyPRES = 51,
        OsmoticDemyelinationSyndrome = 52,
        PosttraumaticLesion = 53,
        Intoxication = 54,
        Mitochondriopathy = 55,
        OpticGlioma = 56
    }
}
