export enum CerebralVenousThrombosisLocationsEnum {
  None = 'None',
  InferiorSagittalSinus = 'InferiorSagittalSinus',
  GreatCerebralVein = 'GreatCerebralVein',
  ConfluensOfSinuses = 'ConfluensOfSinuses',
  TransverseSinusRight = 'TransverseSinusRight',
  SigmoidSinusRight = 'SigmoidSinusRight',
  SuperiorPetrosalSinusRight = 'SuperiorPetrosalSinusRight',
  InferiorPetrosalSinusRight = 'InferiorPetrosalSinusRight',
  InternalJugularVeinRight = 'InternalJugularVeinRight',
  CavernousSinusRight = 'CavernousSinusRight',
  BasalVeinRight = 'BasalVeinRight',
  TransverseSinusLeft = 'TransverseSinusLeft',
  SigmoidSinusLeft = 'SigmoidSinusLeft',
  SuperiorPetrosalSinusLeft = 'SuperiorPetrosalSinusLeft',
  InferiorPetrosalSinusLeft = 'InferiorPetrosalSinusLeft',
  InternalJugularVeinLeft = 'InternalJugularVeinLeft',
  CavernousSinusLeft = 'CavernousSinusLeft',
  BasalVeinLeft = 'BasalVeinLeft'
}
