namespace RadioReport.FeetMRT.Domain.Enums.SoftTissue
{
    public enum DifferentialDiagnosisType : byte
    {
        None = 0,
        BenignLesion = 1,
        MalignantLesion = 2,
        DignityUnclear = 3,
        Other = 4,
        GanglionCyst = 5,
        Lipoma = 6,
        Hemangioma = 7,
        Angiomyoma = 8,
        VascularMalformation = 9,
        Xanthom = 10,
        MortonNeurom = 11,
        Schwannoma = 12,
        Neurofibrom = 13,
        EpidermalInclusionCyst = 14,
        TendonSheathFbrom = 15,
        Dermatofibroma = 16,
        GiantTenosynovialGiantCellTumor = 17,
        Lymphoma = 18,
        Sarcoma = 19,
        Liposarcoma = 20,
        Fibrosarcoma = 21,
        SynovialSarcoma = 22,
        Rhabdomyosarcoma = 23,
        Leiomyosarcoma = 24,
        Angiosarcoma = 25,
        SarcomaUndifferentiatedPleomorph = 26,
        KaposisSarcoma = 27,
        MalignantPeripheralNerve = 28,
        DermatofibrosarcomaProtuberans = 29,
        MalignantMelanoma = 30,
        ForeignBodyGranuloma = 31,
        RuptureOfPlantarPlate = 32,
        Bursitis = 33,
        Rupture = 34,
        PlantarFasciitis = 35,
        PlantarFibromatosis = 36,
        TendonXanthoma = 37,
        PlantarVenousThrombosis = 38,
        BaxtersNeuropathy = 39,
        StressFractureCalcaneus = 40,
        SynovialHemangioma = 41,
        SynovialChondromatosis = 42,
        VillonodularSynovitis = 43,
        HemochromatoticArthropathy = 44,
        TophearthritisGout = 45,
        HalluxRigidity = 46,
        Gout = 47,
        PseudoGout = 48,
        TurfToe = 49
    }
}