import { FindingBase } from '@models/shared/finding/finding.base';
import { CerebrospinalFluidSpaceFindingTypeEnum } from '@enums/headMRT/cerebrospinal-fluid-space/cerebrospinal-fluid-space-finding-type.enum';
import { CerebrospinalMassDiagnosisTypeEnum } from '@enums/headMRT/cerebrospinal-fluid-space/cerebrospinal-mass-diagnosis-type.enum';
import { HistologyKnownTypeEnum } from '@enums/headMRT/cerebrospinal-fluid-space/histology-known-type.enum';
import { HomogeneityTypeEnum } from '@enums/shared/homogeneity-type.enum';
import { SignalVoidTypeEnum } from '@enums/headMRT/common/signal-void-type.enum';
import { MarginTypeEnum } from '@enums/headMRT/common/margin-type.enum';
import { ShapeTypeEnum } from '@enums/headMRT/common/shape-type.enum';
import { ContrastEnhancementQuantitativeTypeEnum } from '@enums/headMRT/common/contrast-enhancement-quantitative-type.enum';
import { ContrastEnhancementDistributionTypeEnum } from '@enums/headMRT/common/contrast-enhancement-distribution-type.enum';

export class CerebrospinalFluidSpaceFindingBaseUiModel extends FindingBase {
  findingType: CerebrospinalFluidSpaceFindingTypeEnum;

  // Common
  isLateralVentricle: boolean;
  isAnteriorHornRight: boolean;
  isCellaMediaRight: boolean;
  isTrigonumRight: boolean;
  isPosteriorHornRight: boolean;
  isTemporalHornRight: boolean;
  isAnteriorHornLeft: boolean;
  isCellaMediaLeft: boolean;
  isTrigonumLeft: boolean;
  isPosteriorHornLeft: boolean;
  isTemporalHornLeft: boolean;
  isForamenOfMonro: boolean;
  isForamenOfMonroRight: boolean;
  isForamenOfMonroLeft: boolean;
  isIIIVentricle: boolean;
  isAquaeductusMesencephaliSylvii: boolean;
  isIVVentricle: boolean;
  isForaminaOfLuschka: boolean;
  isForaminaOfLuschkaRight: boolean;
  isForaminaOfLuschkaLeft: boolean;
  isForamenOfMagendie: boolean;
  isSubarachnoidCisterns: boolean;
  isSuprasellarCistern: boolean;
  isInterpeduncularCistern: boolean;
  isQuadrigeminalCistern: boolean;
  isPontineCistern: boolean;
  isPrepontineCistern: boolean;
  isPontomedullaryCistern: boolean;
  isPontocerebellarCistern: boolean;
  isMeckelCave: boolean;
  isCisternaMagna: boolean;
  isInsularCistern: boolean;
  t1WSignal: number;
  t2WSignal: number;
  flairSignal: number;
  isSignalVoid: boolean;
  signalVoidType: SignalVoidTypeEnum;
  isSuspicionOf: boolean;
  isSubordinate: boolean;

  // Mass
  massDifferentialDiagnosisIKnow1Type: CerebrospinalMassDiagnosisTypeEnum;
  isHistologyKnown: boolean;
  histologyKnownType: HistologyKnownTypeEnum;
  marginType: MarginTypeEnum;
  homogeneityType: HomogeneityTypeEnum;
  shapeType: ShapeTypeEnum;
  isDiffusionRestriction: boolean;
  isHemorrhage: boolean;
  isNecrosis: boolean;
  isCalcification: boolean;
  isFat: boolean;
  isCysts: boolean;
  isCapsule: boolean;
  isSepta: boolean;
  isSignalVoids: boolean;
  isFluidLevel: boolean;
  isDisplacement: boolean;
  isInfiltration: boolean;
  isSubependymalNodules: boolean;
  isCalcified: boolean;
  isHypertrophyChoroidPlexus: boolean;
  isPerifocalEdema: boolean;
  contrastEnhancementQuantitativeType: ContrastEnhancementQuantitativeTypeEnum;
  contrastEnhancementHomogeneityType: HomogeneityTypeEnum;
  contrastEnhancementDistributionType: ContrastEnhancementDistributionTypeEnum;
  massDifferentialDiagnosisIDescribe1Type: CerebrospinalMassDiagnosisTypeEnum;
  massDifferentialDiagnosis2Type: CerebrospinalMassDiagnosisTypeEnum;
  massDifferentialDiagnosis3Type: CerebrospinalMassDiagnosisTypeEnum;
  is1LesionOfTheSameEntity: boolean;

  constructor() {
    super();

    this.findingType = CerebrospinalFluidSpaceFindingTypeEnum.None;

    this.isLateralVentricle = false;
    this.isAnteriorHornRight = false;
    this.isCellaMediaRight = false;
    this.isTrigonumRight = false;
    this.isPosteriorHornRight = false;
    this.isTemporalHornRight = false;
    this.isAnteriorHornLeft = false;
    this.isCellaMediaLeft = false;
    this.isTrigonumLeft = false;
    this.isPosteriorHornLeft = false;
    this.isTemporalHornLeft = false;
    this.isForamenOfMonro = false;
    this.isForamenOfMonroRight = false;
    this.isForamenOfMonroLeft = false;
    this.isIIIVentricle = false;
    this.isAquaeductusMesencephaliSylvii = false;
    this.isIVVentricle = false;
    this.isForaminaOfLuschka = false;
    this.isForaminaOfLuschkaRight = false;
    this.isForaminaOfLuschkaLeft = false;
    this.isForamenOfMagendie = false;
    this.isSubarachnoidCisterns = false;
    this.isSuprasellarCistern = false;
    this.isInterpeduncularCistern = false;
    this.isQuadrigeminalCistern = false;
    this.isPontineCistern = false;
    this.isPrepontineCistern = false;
    this.isPontomedullaryCistern = false;
    this.isPontocerebellarCistern = false;
    this.isMeckelCave = false;
    this.isCisternaMagna = false;
    this.isInsularCistern = false;
    this.t1WSignal = 0;
    this.t2WSignal = 0;
    this.flairSignal = 0;
    this.isSignalVoid = false;
    this.signalVoidType = SignalVoidTypeEnum.None;
    this.isSuspicionOf = false;
    this.isSubordinate = false;

    // Mass
    this.massDifferentialDiagnosisIKnow1Type = CerebrospinalMassDiagnosisTypeEnum.None;
    this.isHistologyKnown = false;
    this.histologyKnownType = HistologyKnownTypeEnum.None;
    this.marginType = MarginTypeEnum.None;
    this.homogeneityType = HomogeneityTypeEnum.None;
    this.shapeType = ShapeTypeEnum.None;
    this.isDiffusionRestriction = false;
    this.isHemorrhage = false;
    this.isNecrosis = false;
    this.isCalcification = false;
    this.isFat = false;
    this.isCysts = false;
    this.isCapsule = false;
    this.isSepta = false;
    this.isSignalVoids = false;
    this.isFluidLevel = false;
    this.isDisplacement = false;
    this.isInfiltration = false;
    this.isSubependymalNodules = false;
    this.isCalcified = false;
    this.isHypertrophyChoroidPlexus = false;
    this.isPerifocalEdema = false;
    this.contrastEnhancementQuantitativeType = ContrastEnhancementQuantitativeTypeEnum.None;
    this.contrastEnhancementHomogeneityType = HomogeneityTypeEnum.None;
    this.contrastEnhancementDistributionType = ContrastEnhancementDistributionTypeEnum.None;
    this.massDifferentialDiagnosisIDescribe1Type = CerebrospinalMassDiagnosisTypeEnum.None;
    this.massDifferentialDiagnosis2Type = CerebrospinalMassDiagnosisTypeEnum.None;
    this.massDifferentialDiagnosis3Type = CerebrospinalMassDiagnosisTypeEnum.None;
    this.is1LesionOfTheSameEntity = false;
  }
}
