
namespace RadioReport.ThoraxMRT.Domain.Enums
{
    public enum MediastinumDiagnosisType : byte
    {
        None = 0,
        AcutePulmonaryEmbolism = 1,
        AcutePulmonaryEmbolismWithRightHeartStrain = 2,
        AcutePulmonaryEmbolismWithoutRightHeartStrain = 3,
        ChronicPulmonaryEmbolism = 4,
        ChronicPulmonaryEmbolismWithRightHeartStrain = 5,
        ChronicPulmonaryEmbolismWithoutRightHeartStrain = 6,
        PulmonaryHypertensionGroup1PulmonaryArterialHypertensionPah = 7,
        PulmonaryHypertensionGroup2BasedOnLeftHeartDisease = 8,
        PulmonaryHypertensionGroup3BasedOnLungDiseaseAndOrHypoxia = 9,
        PulmonaryHypertensionGroup4ChronicThromboembolicCteph = 10,
        BicuspidAorticValve = 11,
        MarfanSyndrome = 12,
        BenignLesionNotFurtherSpecified = 13,
        MalignantLesionNotFurtherSpecified = 14,
        DignityUnclear = 15,
        ThymicHyperplasia = 16,
        Lipoma = 17,
        Thymolipoma = 18,
        Thymoma = 19,
        Struma = 20,
        GoiterRetrosternal = 21,
        BenigneGermCellTumorNotFurtherSpecified = 22,
        MalignantDermoidCyst = 23,
        BenigneTeratoma = 24,
        CystNotFurtherSpecified = 25,
        ThymicCyst = 26,
        AneurysmDescendingAorta = 27,
        BronchiogenicCyst = 28,
        PericardialCyst =29,
        NeurogenicCyst = 30,
        Neuroblastoma = 31,
        Ganglioneuroma = 32,
        Neuroma = 33,
        Paraganglioma = 34,
        ThymicCarcinoma = 35,
        LymphomaNotFurtherSpecified = 36,
        MHodgkin = 37,
        NonHodgkin = 38,
        LiposarcomaBlastoma = 39,
        DescendingThoracicAorticAneurysm = 40,
        BronchogenicCyst = 41,
        HodgkinSDisease = 42,
        AorticRoot = 43,
        AscendingAorta = 44,
        ArcusAortae = 45,
        AortaThoracicaParsDescendens = 46,
        SuprarenalAbdominalAorta = 47,
        InfrarenalAbdominalAorta = 48,
        RightCommonIliacArtery = 49,
        LeftCommonIliacArtery = 50,
        RightExternalIliacArtery = 51,
        LeftExternalIliacArtery = 52,
        Polyp = 53,
        Papillomatosis = 54,
        MucuousPlugging = 55,
        MalignantGermCellTumorNotFurtherDefined = 56,
        MalignantTeratoma = 57,
        BenigneDermoidCyst = 58

    }
}
