import { FindingBase } from '@models/shared/finding/finding.base';
import { LungParenchymaFindingTypeEnum } from '@enums/thoraxCT/lung-parenchyma-focal/lung-parenchyma-finding-type.enum';
import { LungParenchymaDiagnosisTypeEnum } from '@enums/thoraxCT/lung-parenchyma-focal/lung-parenchyma-diagnosis-type.enum';
import { LungParenchymaDensityTypeEnum } from '@enums/thoraxCT/lung-parenchyma-focal/lung-parenchyma-density-type.enum';
import { MarginTypeEnum } from '@enums/thoraxCT/common/margin-type.enum';
import { HomogeneityTypeEnum } from '@enums/thoraxCT/common/homogeneity-type.enum';
import { LungParenchymaCalcificationTypeEnum } from '@enums/thoraxCT/lung-parenchyma-focal/lung-parenchyma-calcification-type.enum';
import { LocalizationDetailsTypeEnum } from '@enums/thoraxCT/lung-parenchyma-focal/localization-details-type.enum';
import { ContrastEnhancementQuantitativeTypeEnum } from '@enums/thoraxCT/common/contrast-enhancement-quantitative-type.enum';
import { ReferencePictureUiModel } from '@models/shared/reference-picture/reference-picture-ui.model';
import { HistologyKnownTypeEnum } from '@enums/thoraxCT/lung-parenchyma-focal/histology-known-type.enum';
import { LungParenchymaLocalizationTypeEnum } from '@enums/thoraxCT/lung-parenchyma-focal/lung-parenchyma-localization-type.enum';
import { PerifissuralNodulusTypeEnum } from '@enums/thoraxCT/lung-parenchyma-focal/perifissural-nodulus-type.enum';
import { SubsolidTypeEnum } from '@enums/thoraxCT/lung-parenchyma-focal/subsolid-type.enum';
import { LungsSegmentsModel } from '@models/thoraxCT/ui/thorax/lungs-segments.model';
import { LungsFlapsModel } from '@models/shared/thorax/localizers/lungs-flaps-model';
import { ConsolidationLocalizationTypeEnum } from '@enums/thoraxCT/lung-parenchyma-focal/consolidation-localization-type.enum';
import { GroundGlassOpacityTypeEnum } from '@enums/thoraxCT/lung-parenchyma-focal/ground-glass-opacity-type.enum';
import { LocalizationAxialTypeEnum } from '@enums/thoraxCT/lung-parenchyma-focal/localization-axial-type.enum';
import { MorphologyTypeEnum } from '@enums/thoraxCT/lung-parenchyma-focal/morphology-type.enum';
import { WellDefinedTypeEnum } from '@enums/thoraxCT/lung-parenchyma-focal/well-defined-type.num';

export class LungParenchymaFindingBaseUiModel extends FindingBase {
  findingType: LungParenchymaFindingTypeEnum;
  mainCharacteristicsDifferentialDiagnosis01: LungParenchymaDiagnosisTypeEnum;
  densityType: LungParenchymaDensityTypeEnum;
  marginType: MarginTypeEnum;
  homogeneityType: HomogeneityTypeEnum;
  isEccentricNecrosis: boolean;
  isFat: boolean;
  isCalcification: boolean;
  calcificationType: LungParenchymaCalcificationTypeEnum;
  isCavitation: boolean;
  isPleuralFinger: boolean;
  isCoronaRadiataOrSpiculae: boolean;
  localizationDetailsType: LocalizationDetailsTypeEnum;
  contrastEnhancementQuantitativeType: ContrastEnhancementQuantitativeTypeEnum;
  contrastEnhancementHomogeneityType: HomogeneityTypeEnum;
  isAssociatedAtelectasis: boolean;
  isHistologyKnown: boolean;
  histologyKnownType: HistologyKnownTypeEnum;
  mainCharacteristicsLocalizationType: LungParenchymaLocalizationTypeEnum;
  perifissuralNodulusType: PerifissuralNodulusTypeEnum;
  distanceToInterlobularSeptumInMm: number;
  subsolidType: SubsolidTypeEnum;
  averageDensityInHU: number;
  mainCharacteristicsLungsSegmentsLocation: LungsSegmentsModel; // localizer
  mainCharacteristicsLungsFlapsLocation: LungsFlapsModel; // localizer
  isRiglerNotchSign: boolean;
  isCentralNecrosis: boolean;
  isHaloSign: boolean;
  isReversedHaloSign: boolean;
  isMoreThanOneLesionSamePathology;
  differentialDiagnosisLocalizationType: LungParenchymaLocalizationTypeEnum;
  differentialDiagnosisLungsSegmentsLocation: LungsSegmentsModel; // localizer
  differentialDiagnosisLungsFlapsLocation: LungsFlapsModel; // localizer
  referencePicture: ReferencePictureUiModel;
  isPleura: boolean;
  isPericardium: boolean;
  isRib: boolean;
  isSternum: boolean;
  isClavicule: boolean;
  isVertebralBody: boolean;
  isAPulmonalis: boolean;
  isAPulmonalisRight: boolean;
  isAPulmonalisLeft: boolean;
  isVvPulmonary: boolean;
  isVvPulmonaryRight: boolean;
  isVvPulmonaryLeft: boolean;
  isASubclavia: boolean;
  isASubclaviaRight: boolean;
  isASubclaviaLeft: boolean;
  isVSubclavia: boolean;
  isVSubclaviaRight: boolean;
  isVSubclaviaLeft: boolean;
  isTrachea: boolean;
  isBifurcation: boolean;
  isMainBronchus: boolean;
  isMainBronchusRight: boolean;
  isMainBronchusLeft: boolean;
  isPlexusCervicalis: boolean;
  isPlexusCervicalisRight: boolean;
  isPlexusCervicalisLeft: boolean;
  isPlexusBrachialis: boolean;
  isPlexusBrachialisRight: boolean;
  isPlexusBrachialisLeft: boolean;
  isHemorrhage: boolean;
  consolidationLocalizationType: ConsolidationLocalizationTypeEnum;
  isPositiveBronchopneumogram: boolean;
  isGroundGlassOpacity: boolean;
  groundGlassOpacityType: GroundGlassOpacityTypeEnum;
  isDarkBronchusSign: boolean;
  localizationAxialType: LocalizationAxialTypeEnum;
  morphologyType: MorphologyTypeEnum;
  isConfluent: boolean;
  isRoundedShape: boolean;
  isGeographicAppearance: boolean;
  isPeribronchovascular: boolean;
  isCrazyPavingPattern: boolean;
  isInterlobularSeptalThickening: boolean;
  isMosaicPattern: boolean;
  wellDefinedType: WellDefinedTypeEnum;
  isAbscess: boolean;
  isLuftsichelSign: boolean;
  isPneumatocele: boolean;
  isAccompanyingEffusion: boolean;
  accompanyingEffusionMaxWidthInMm: number;

  constructor() {
    super();

    this.findingType = LungParenchymaFindingTypeEnum.None;
    this.mainCharacteristicsDifferentialDiagnosis01 = LungParenchymaDiagnosisTypeEnum.None;
    this.densityType = LungParenchymaDensityTypeEnum.None;
    this.marginType = MarginTypeEnum.None;
    this.homogeneityType = HomogeneityTypeEnum.None;
    this.isEccentricNecrosis = false;
    this.isFat = false;
    this.isCalcification = false;
    this.calcificationType = LungParenchymaCalcificationTypeEnum.None;
    this.isCavitation = false;
    this.isPleuralFinger = false;
    this.isCoronaRadiataOrSpiculae = false;
    this.localizationDetailsType = LocalizationDetailsTypeEnum.None;
    this.contrastEnhancementQuantitativeType = ContrastEnhancementQuantitativeTypeEnum.None;
    this.contrastEnhancementHomogeneityType = HomogeneityTypeEnum.None;
    this.isAssociatedAtelectasis = false;
    this.isHistologyKnown = false;
    this.histologyKnownType = HistologyKnownTypeEnum.None;
    this.mainCharacteristicsLocalizationType = LungParenchymaLocalizationTypeEnum.None;
    this.subsolidType = SubsolidTypeEnum.None;
    this.averageDensityInHU = null;
    this.mainCharacteristicsLungsSegmentsLocation = new LungsSegmentsModel(); // localizer
    this.mainCharacteristicsLungsFlapsLocation = new LungsFlapsModel(); // localizer
    this.isRiglerNotchSign = false;
    this.isCentralNecrosis = false;
    this.isHaloSign = false;
    this.isReversedHaloSign = false;
    this.isMoreThanOneLesionSamePathology = false;
    this.differentialDiagnosisLocalizationType = LungParenchymaLocalizationTypeEnum.None;
    this.differentialDiagnosisLungsSegmentsLocation = new LungsSegmentsModel(); // localizer
    this.differentialDiagnosisLungsFlapsLocation = new LungsFlapsModel(); // localizer
    this.perifissuralNodulusType = PerifissuralNodulusTypeEnum.None;
    this.distanceToInterlobularSeptumInMm = null;
    this.referencePicture = new ReferencePictureUiModel();
    this.isPleura = false;
    this.isPericardium = false;
    this.isRib = false;
    this.isSternum = false;
    this.isClavicule = false;
    this.isVertebralBody = false;
    this.isAPulmonalis = false;
    this.isAPulmonalisRight = false;
    this.isAPulmonalisLeft = false;
    this.isVvPulmonary = false;
    this.isVvPulmonaryRight = false;
    this.isVvPulmonaryLeft = false;
    this.isASubclavia = false;
    this.isASubclaviaRight = false;
    this.isASubclaviaLeft = false;
    this.isVSubclavia = false;
    this.isVSubclaviaRight = false;
    this.isVSubclaviaLeft = false;
    this.isTrachea = false;
    this.isBifurcation = false;
    this.isMainBronchus = false;
    this.isMainBronchusRight = false;
    this.isMainBronchusLeft = false;
    this.isPlexusCervicalis = false;
    this.isPlexusCervicalisRight = false;
    this.isPlexusCervicalisLeft = false;
    this.isPlexusBrachialis = false;
    this.isPlexusBrachialisRight = false;
    this.isPlexusBrachialisLeft = false;
    this.isHemorrhage = false;
    this.consolidationLocalizationType = ConsolidationLocalizationTypeEnum.None;
    this.isPositiveBronchopneumogram = false;
    this.isGroundGlassOpacity = false;
    this.groundGlassOpacityType = GroundGlassOpacityTypeEnum.None;
    this.isDarkBronchusSign = false;
    this.localizationAxialType = LocalizationAxialTypeEnum.None;
    this.morphologyType = MorphologyTypeEnum.None;
    this.isConfluent = false;
    this.isRoundedShape = false;
    this.isGeographicAppearance = false;
    this.isPeribronchovascular = false;
    this.isCrazyPavingPattern = false;
    this.isInterlobularSeptalThickening = false;
    this.isMosaicPattern = false;
    this.wellDefinedType = WellDefinedTypeEnum.None;
    this.isAbscess = false;
    this.isLuftsichelSign = false;
    this.isPneumatocele = false;
    this.isAccompanyingEffusion = false;
    this.accompanyingEffusionMaxWidthInMm = null;
  }
}
