export enum TraceMessage {
  WINDOW_CREATED_METHOD = 'Window created (method)',
  SCREEN_DIMENSIONS = 'Screensize | Width | Height',
  START_APP_LOADING = 'Start loading application',
  APP_LOADED = 'Application loaded',
  APPLICATION_URL = 'Application url',
  INDEX_PATH = 'Index path',
  INDEX_PATH_EXISTS = 'Index path exists',
  IMPORT_REPORT_REQUESTED = 'Import report requested',
  STUDY_SELECTION_REQUESTED = 'Study selection requested',
  CHECK_EXISTING_IMPORT_REQUESTED = 'Check existing import requested',
  MODULE_SELECTION_REQUESTED = 'Module selection requested',
  STUDY_SELECTION_ANSWERED = 'Study selection answer received',
  MODULE_SELECTION_ANSWERED = 'Module selection answer received',
  CHECK_EXISTING_IMPORT_ANSWERED = 'Check existing import received',
  REQUIRED_FIELDS_REQUESTED = 'Required fields input requested',
  REQUIRED_FIELDS_ANSWERED = 'Required fields input answer received',
  USER_LOGGED_IN = 'User logged in',
  IMPORT_REQUEST_AFTER_LOGIN = 'Report import requested after login',
  IMPORT_REQUEST_SECOND_INSTANCE = 'Report import requested by second instance',
  EXECUTING_DICOM_PARSER = 'Executing dicom parser',
  STUDIES_OF_PATIENT_RESULT_RECEIVED = 'Patient result received',
  PATIENT_RESULT_RECEIVED = 'Patient result received',
  STUDY_RESULT_RECEIVED = 'Study result received',
  SERIES_RESULT_RECEIVED = 'Series result received',
  CMOVE_RESULT_RECEIVED = 'CMove result received',
  IMPORT_SCOPE_CREATED = 'New import scope created'
}
