namespace RadioReport.HeadMRT.Domain.Enums.BasalNuclei
{
    public enum BasalNucleiDiagnosisType : byte
    {
        None = 0,
        AcuteStroke = 1,
        Ischemia = 2,
        Hemorrhage = 3,
        DeepVenousThrombosis = 4,
        AcuteHypertensiveEncephalopathyPres = 5,
        Cadasil = 6,
        SusacSyndrome = 7,
        HypotensiveCerebralInfarction = 8,
        HemorrhagicNecrosis = 9,
        MoyaMoya = 10,
        EnlargedPerivascularSpaces = 11,
        BasalGangliaCalcification = 12,
        HuntingtonSChorea = 13,
        Vasculitis = 14,
        BehcetSDisease = 15,
        Encephalitis = 16,
        Adem = 17,
        Sle = 18,
        CreutzfeldJakobDisease = 19,
        Hypoglycemia = 20,
        DiabeticKetoacidosis = 21,
        UremicEncephalopathy = 22,
        HepaticEncephalopathy = 23,
        Hypothyroidism = 24,
        Hyperparathyroidism = 25,
        FahrSDisease = 26,
        OsmoticDemyelinationSyndrome = 27,
        ToxicEncephalopathy = 28,
        MethanolIntoxication = 29,
        Hypoxia = 30,
        CarbonMonoxideIntoxication = 31,
        GadoliniumDeposit = 32,
        ManganeseDeposit = 33,
        MorbusWilson = 34,
        WernickeEncephalopathy = 35,
        MelasSyndrome = 36,
        BenignLesionNotFurtherSpecified = 37,
        MalignantLesionNotFurtherSpecified = 38,
        DignityUnclear = 39,
        Metastasis = 40,
        DiffuseAstrocytoma = 41,
        Glioma = 42, 
        ParenchymalHemorrhage = 43,
        AfterChemotherapy = 44,
        PostRadiogenic = 45,
        StatusEpilepticus = 46

    }
}
