export enum LocalizationDetailsTypeEnum {
  None = 'None',
  Radial = 'Radial',
  Ulnar = 'Ulnar',
  AbductorPollicisLongus = 'AbductorPollicisLongus',
  ExtensorPollicisBrevis = 'ExtensorPollicisBrevis',
  ExtensorCarpiRadialisLongus = 'ExtensorCarpiRadialisLongus',
  ExtensorCarpiRadialisBrevis = 'ExtensorCarpiRadialisBrevis',
  ExtensorPollicisLongus = 'ExtensorPollicisLongus',
  ExtensorIndicis = 'ExtensorIndicis',
  DigitorumD2 = 'DigitorumD2',
  DigitorumD3 = 'DigitorumD3',
  DigitorumD4 = 'DigitorumD4',
  DigitorumD5 = 'DigitorumD5',
  ExtensorDigitiMinimi = 'ExtensorDigitiMinimi',
  ExtensorCarpiUlnaris = 'ExtensorCarpiUlnaris',
  SuperficialD2 = 'SuperficialD2',
  SuperficialD3 = 'SuperficialD3',
  SuperficialD4 = 'SuperficialD4',
  SuperficialD5 = 'SuperficialD5',
  ProfundusD2 = 'ProfundusD2',
  ProfundusD3 = 'ProfundusD3',
  ProfundusD4 = 'ProfundusD4',
  ProfundusD5 = 'ProfundusD5',
  FlexorPollicisLongus = 'FlexorPollicisLongus',
  FlexorCarpiRadialis = 'FlexorCarpiRadialis',
  FlexorCarpiUlnaris = 'FlexorCarpiUlnaris'
}
