namespace RadioReport.MammaMX.Domain.Enums.MammographyFinding
{
    public enum DiagnosisType : byte
    {
        None = 0,
        BenignLesionNotFurtherDefined = 1,
        MalignantLesionNotFurtherDefined = 2,
        DignityUnclear = 3,
        FibrocysticMastopathy = 4,
        BreastParenchymaNonSpecific = 5,
        Fibroadenoma = 6,
        IntramammaryLymphNode = 7,
        BenignCyst = 8,
        RadialScar = 9,
        DuctalCarcinomaInSituDcis = 10,
        LobularCarcinomaInSituLcis = 11,
        BreastCarcinomaNotFurtherDefined = 12,
        InvasiveDuctalBreastCarcinoma = 13,
        InvasiveLobularBreastCarcinoma = 14,
        IntracysticPapillaryCarcinoma = 15,
        InvasivePapillaryCarcinoma = 16,
        MucinousCarcinoma = 17,
        MedullaryCarcinoma = 18,
        InflammatoryCarcinoma = 19,
        MetaplasticCarcinoma = 20,
        Mastitis = 21,
        BenignPhyllodesTumor = 22,
        Pash = 23,
        Lipoma = 24,
        Hemangioma = 25,
        Hamartoma = 26,
        Abscess = 27,
        FattyTissueNecrosis = 28,
        OilCyst = 29,
        Seroma = 30,
        Hematoma = 31,
        Scar = 32,
        Papilloma = 33,
        AtypicalDuctalHyperplasiaAdh = 34,
        CystWithProliferation = 35,
        Sarcoma = 36,
        Lymphoma = 37,
        MalignantPhyllodesTumor = 38
    }
}
