export enum BonesDiagnosisTypeEnum {
  None = 'None',
  BenignLesionNotDefined = 'BenignLesionNotDefined',
  MalignantLesionNotDefined = 'MalignantLesionNotDefined',
  DignityUnclear = 'DignityUnclear',
  Enchondrome = 'Enchondrome',
  Hemangioma = 'Hemangioma',
  SclerosisIslandOrEnostosis = 'SclerosisIslandOrEnostosis',
  IntraossalLipoma = 'IntraossalLipoma',
  IntraosseousCyst = 'IntraosseousCyst',
  BoneInfarct = 'BoneInfarct',
  FibrousDysplasia = 'FibrousDysplasia',
  AneurysmaticBoneCyst = 'AneurysmaticBoneCyst',
  Osteoidosteom = 'Osteoidosteom',
  Osteochondrome = 'Osteochondrome',
  Chondroblastoma = 'Chondroblastoma',
  Osteoblastoma = 'Osteoblastoma',
  EwingSarcoma = 'EwingSarcoma',
  Osteosarcoma = 'Osteosarcoma',
  GiantCellTumor = 'GiantCellTumor',
  Chondrosarcoma = 'Chondrosarcoma',
  Metastasis = 'Metastasis',
  Lymphoma = 'Lymphoma',
  MultipleMyeloma = 'MultipleMyeloma',
  Osteomyelitis = 'Osteomyelitis',
  Abscess = 'Abscess'
}
