export enum DiagnosisTypeEnum {
  None = 'None',
  BenignLesionNotFurtherClassified = 'BenignLesionNotFurtherClassified',
  MalignantLesionNotFurtherClassified = 'MalignantLesionNotFurtherClassified',
  DignityUnclear = 'DignityUnclear',
  Enchondroma = 'Enchondroma',
  Hemangioma = 'Hemangioma',
  BoneIslandOrEnostoses = 'BoneIslandOrEnostoses',
  IntraosseousLipoma = 'IntraosseousLipoma',
  IntraosseousCyst = 'IntraosseousCyst',
  FibrousDysplasia = 'FibrousDysplasia',
  AneurysmaticBoneCyst = 'AneurysmaticBoneCyst',
  OsteoidOsteoma = 'OsteoidOsteoma',
  Osteochondroma = 'Osteochondroma',
  Chondroblastoma = 'Chondroblastoma',
  Osteoblastoma = 'Osteoblastoma',
  GiantCellTumor = 'GiantCellTumor',
  EwingSarcoma = 'EwingSarcoma',
  Osteosarcoma = 'Osteosarcoma',
  Chondrosarcoma = 'Chondrosarcoma',
  Metastasis = 'Metastasis',
  Lymphoma = 'Lymphoma',
  MultipleMyeloma = 'MultipleMyeloma',
  Osteomyelitis = 'Osteomyelitis',
  BoneInfarction = 'BoneInfarction'
}
