import { DescriptionTypeEnum } from '@enums/shared/description-type.enum';
import { MyelonBaseFindingUiModel } from '@models/spineMRT/ui/myelon/myelon-base-finding-ui.model';
import { MalformationTypeEnum } from '@enums/spineMRT/myelon/malformation-type.enum';
import { CharacterizationTypeEnum } from '@enums/spineMRT/myelon/characterization-type.enum';
import { DetailsClosedDysraphismTypeEnum } from '@enums/spineMRT/myelon/details-closed-dysraphism-type.enum';
import { ClassificationSubcutaneousMassTypeEnum } from '@enums/spineMRT/myelon/classification-subcutaneous-mass-type.enum';
import { DifferentialDiagnosesTypeEnum } from '@enums/spineMRT/myelon/differential-diagnoses-type.enum';
import { ClassificationDysraphyTypeEnum } from '@enums/spineMRT/myelon/classification-dysraphy-type.enum';
import { CharacterizationOpenTypeEnum } from '@enums/spineMRT/myelon/characterization-open-type.enum';
import { SpinalCanalFindingTypeEnum } from '@enums/spineMRT/myelon/spinal-canal-finding-type.enum';
import { SpinalCanalDifferentialDiagnosisTypeEnum } from '@enums/spineMRT/myelon/spinal-canal-differential-diagnosis-type.enum';
import { SpinalCanalStenosisDetailTypeEnum } from '@enums/spineMRT/myelon/spinal-canal-stenosis-detail-type.enum';
import { LocalizationInTheSpinalCanalTypeEnum } from '@enums/spineMRT/myelon/localizationIn-the-spinal-canal-type.enum';
import { LocalizationTypeEnum } from '@enums/spineMRT/myelon/localization-type.enum';
import { SpinalCanalLocation } from '@models/shared/spine/localizers/spinal-canal-location.model';
import { LongitudinalExpansionInMyelonEnum } from '@enums/spineMRT/myelon/longitudinal-expansion-in-myelon.enum';
import { SpineLocation } from '@models/shared/spine/localizers/spine-location.model';

export class MyelonFindingUIModel extends MyelonBaseFindingUiModel {
  findingType: SpinalCanalFindingTypeEnum;
  descriptionType: DescriptionTypeEnum;
  isSecondary: boolean;
  spinalCanalStenosisDetailType: SpinalCanalStenosisDetailTypeEnum;
  widthOfTheSpinalCanal: number;
  isMyelopathy: boolean;
  malformationType: MalformationTypeEnum;
  isCaudalPositionOfTheMedullaryCone: boolean;
  isThickenedFilumTerminale: boolean;
  expansionInCcDimension: number;
  characterizationType: CharacterizationTypeEnum;
  expansionProtrusionCcDimension: number;
  diameter: number;
  characterizationOpenType: CharacterizationOpenTypeEnum;
  localizationType: LocalizationTypeEnum;
  isPerineuralCyst: boolean;
  detailsClosedDysraphismType: DetailsClosedDysraphismTypeEnum;
  classificationSubcutaneousMassType: ClassificationSubcutaneousMassTypeEnum;
  classificationDysraphyType: ClassificationDysraphyTypeEnum;
  differentialDiagnosesType: DifferentialDiagnosesTypeEnum;
  isT1wHyperintense: boolean;
  isT2wHyperintense: boolean;
  isT1wFatSaturationHypointense: boolean;
  isNoContrastEnhancement: boolean;
  spinalCanalLocation: SpinalCanalLocation;
  sizeAxial: number;
  sizeCraniocaudal: number;
  isAnterior: boolean;
  isPosterior: boolean;
  isLeft: boolean;
  isRight: boolean;
  localizationInTheSpinalCanalType: LocalizationInTheSpinalCanalTypeEnum;
  differentialDiagnosis03: SpinalCanalDifferentialDiagnosisTypeEnum;
  longitudinalExpansionInMyelon: LongitudinalExpansionInMyelonEnum;
  spineLocation: SpineLocation;

  constructor() {
    super();
    this.findingType = SpinalCanalFindingTypeEnum.None;
    this.descriptionType = DescriptionTypeEnum.IDescribe;
    this.isSecondary = false;
    this.spinalCanalStenosisDetailType = SpinalCanalStenosisDetailTypeEnum.None;
    this.widthOfTheSpinalCanal = null;
    this.isMyelopathy = false;
    this.malformationType = MalformationTypeEnum.None;
    this.isCaudalPositionOfTheMedullaryCone = false;
    this.isThickenedFilumTerminale = false;
    this.expansionInCcDimension = null;
    this.characterizationType = CharacterizationTypeEnum.None;
    this.expansionProtrusionCcDimension = null;
    this.diameter = null;
    this.characterizationOpenType = CharacterizationOpenTypeEnum.None;
    this.localizationType = LocalizationTypeEnum.None;
    this.isPerineuralCyst = false;
    this.detailsClosedDysraphismType = DetailsClosedDysraphismTypeEnum.None;
    this.classificationSubcutaneousMassType = ClassificationSubcutaneousMassTypeEnum.None;
    this.classificationDysraphyType = ClassificationDysraphyTypeEnum.None;
    this.differentialDiagnosesType = DifferentialDiagnosesTypeEnum.None;
    this.isT1wHyperintense = false;
    this.isT2wHyperintense = false;
    this.isT1wFatSaturationHypointense = false;
    this.isNoContrastEnhancement = false;
    this.spinalCanalLocation = new SpinalCanalLocation();
    this.sizeAxial = null;
    this.sizeCraniocaudal = null;
    this.localizationInTheSpinalCanalType = LocalizationInTheSpinalCanalTypeEnum.None;
    this.differentialDiagnosis03 = SpinalCanalDifferentialDiagnosisTypeEnum.None;
    this.longitudinalExpansionInMyelon = LongitudinalExpansionInMyelonEnum.None;
    this.spineLocation = new SpineLocation();
  }
}
