export enum MeningesDiffuseDiagnosisTypeEnum {
  None = 'None',
  Metastases = 'Metastases',
  MeningeosisCarcinomatosa = 'MeningeosisCarcinomatosa',
  Meningitis = 'Meningitis',
  SubacuteInfarction = 'SubacuteInfarction',
  Vasculitis = 'Vasculitis',
  Neurosarcoidosis = 'Neurosarcoidosis',
  SturgeWeberSyndrome = 'SturgeWeberSyndrome',
  Glioblastoma = 'Glioblastoma',
  IntracranialHypotensionSyndrome = 'IntracranialHypotensionSyndrome',
  Lymphoma = 'Lymphoma',
  Hemorrhage = 'Hemorrhage',
  DuralAVFistula = 'DuralAVFistula',
  PRES = 'PRES',
  Meningoangiomatosis = 'Meningoangiomatosis',
  MoyaMoya = 'MoyaMoya',
  Encephalitis = 'Encephalitis',
  NeurocutaneousMelanosis = 'NeurocutaneousMelanosis',
  PostoperativeFinding = 'PostoperativeFinding',
  PosttraumaticFinding = 'PosttraumaticFinding'
}
