export enum MyelonDifferentialDiagnoseTypeEnum {
  None = 'None',
  BenignLesionNotFurtherSpecified = 'BenignLesionNotFurtherSpecified',
  MalignantLesionNotFurtherSpecified = 'MalignantLesionNotFurtherSpecified',
  DignityUnclear = 'DignityUnclear',
  Vascular = 'Vascular',
  Inflammation = 'Inflammation',
  SchwanomaNeurinoma = 'SchwanomaNeurinoma',
  Neurofibroma = 'Neurofibroma',
  NeurofibromatosisType2 = 'NeurofibromatosisType2',
  Meningioma = 'Meningioma',
  Paraganglioma = 'Paraganglioma',
  ArachnoidCyst = 'ArachnoidCyst',
  Cyst = 'Cyst',
  Neurofibrosarcoma = 'Neurofibrosarcoma',
  Metastasis = 'Metastasis',
  MeningeosisCarcinomatosa = 'MeningeosisCarcinomatosa',
  EpiduralHematoma = 'EpiduralHematoma',
  SubduralHematoma = 'SubduralHematoma',
  Cavernoma = 'Cavernoma',
  AVMalformation = 'AVMalformation',
  SpinalSAH = 'SpinalSAH',
  DiscSequester = 'DiscSequester',
  Abscess = 'Abscess',
  SpinalArachnoiditis = 'SpinalArachnoiditis'
}
