namespace RadioReport.HeadCT.Domain.Enums.SellarRegion
{
    public enum SellarRegionDiagnosisType : byte
    {
        None = 0,
        BenignLesionNotSpecified = 1,
        MalignantLesionNotSpecified = 2,
        DignityUnclear = 3,
        Aneurysm = 4,
        RathkeCleftCyst = 5,
        ArachnoidCyst = 6,
        PituitaryMacroadenoma = 7,
        Meningioma = 8,
        Craniopharyngioma = 9,
        GliomaBenign = 10,
        Hamartoma = 11,
        TeratomaBenign = 12,
        Epidermoid = 13,
        Dermoid = 14,
        SchwannomaNeurinoma = 15,
        ParagangliomaBenign = 16,
        Metastasis = 17,
        TeratomaMalignant = 18,
        GliomaMalignant = 19,
        Germinoma = 20,
        Lymphoma = 21,
        ParagangliomaMalignant = 22,
        Chordoma = 23,
        InflammatoryEtiology = 24,
        PostInflammatoryChange = 25,
        Hypophysitis = 26,
        Neurosarcoidosis = 27,
        Demyelination = 28,
        MultipleSclerosis = 29,
        OpticNeuritis = 30,
        NeuromyelitisOpticaNMOSD = 31,
        ADEM = 32,
        PML = 33,
        Tuberculosis = 34,
        Gliosis = 35,
        StructuralDefect = 36,
        PostischemicDefect = 37,
        PostoperativeDefect = 38,
        PosttraumaticDefect = 39,
        EmptySella = 40,
        Histiocytosis = 41,
        EosinophilicGranuloma = 42,
        PostradiationChanges = 43,
        Calcification = 44,
        Hemorrhage = 45
    }
}
