export enum AbdominalTypeEnum {
  None = 'None',
  Mass = 'Mass',
  Ascites = 'Ascites',
  PeritonealCarcinomatosis = 'PeritonealCarcinomatosis',
  Splenomegaly = 'Splenomegaly',
  Hepatomegaly = 'Hepatomegaly',
  HiatalHernia = 'HiatalHernia',
  Cholestasis = 'Cholestasis',
  Cholecystitis = 'Cholecystitis',
  Cholecystolithiasis = 'Cholecystolithiasis',
  Ileus = 'Ileus',
  MesentericIschemia = 'MesentericIschemia',
  Diverticulosis = 'Diverticulosis',
  Diverticulitis = 'Diverticulitis',
  UrinaryRetention = 'UrinaryRetention',
  Hydrocele = 'Hydrocele',
  Phlebolith = 'Phlebolith',
  Fracture = 'Fracture'
}
