namespace RadioReport.HeadCT.Domain.Enums.Meninges
{
    public enum MeningesDiagnosisType : byte
    {
        None = 0,
        BenignLesionNotFurtherSpecified = 1,
        MalignantLesionNotFurtherSpecified = 2,
        UnknownEtiology = 3,
        AcuteSubduralHematoma = 4,
        ChronicSubduralHematoma = 5,
        AcuteOnChronicSubduralHematoma = 6,
        SubarachnoidHemorrhage = 7,
        EpiduralHematoma = 8,
        DuralAVFistula = 9,
        Meningioma = 10,
        Hygroma = 11,
        Lipoma = 12,
        SphenoidWingMeningioma = 13,
        ConvexityMeningioma = 14,
        FalxMeningioma = 15,
        OlfactoryGrooveMeningioma = 16,
        ParasellarMeningioma = 17,
        OpticNerveSheathMeningioma = 18,
        PetrousBoneMeningioma = 19,
        TentorialMeningioma = 20,
        Meningoangiomatosis = 21,
        Schwannoma = 22,
        Macroadenoma = 23,
        Osteoma = 24,
        PagetsDisease = 25,
        FibrousDysplasia = 26,
        ChordomaBenignLesion = 27,
        Craniopharyngioma = 28,
        DuralHemangioma = 29,
        Metastasis = 30,
        Lymphoma = 31,
        Leukaemia = 32,
        MalignantMeningioma = 33,
        MeningeosisCarcinomatosa = 34,
        Chondrosarcoma = 35,
        Fibrosarcoma = 36,
        Angiosarcoma = 37,
        Hemangiopericytoma = 38,
        ChordomaMalignantLesion = 39,
        Meningitis = 40,
        TBCMeningitis = 41,
        Neurosarcoidosis = 42,
        HypertrophicPachymeningitis = 43,
        ExtramedullaryHematopoiesis = 44,
        IgG4RelatedFinding = 45,
        OssifiedDuraWithEvidenceOfFatTissue = 46,
        NeurocutaneousMelanosis = 47,
        PostoperativeFinding = 48,
        PosttraumaticFinding = 49,
        Metastases = 50,
        Glioblastoma = 51,
        Vasculitis = 52,
        Encephalitis = 53,
        SubacuteInfarction = 54,
        MoyaMoya = 55,
        SubduralHemorrhage = 56,
        IntracranialHypotensionSyndrome = 57,
        SturgeWeberSyndrome = 58
    }
}
