namespace RadioReport.Core.CenterSpecificSettings.Domain.Enums
{
    public enum SequenceType : byte
    {
        // TODO: need to merge into one enum and after that refactor 3-rd pages of each module, because each module is using different definition for sequence type enum
        None = 0,
        SEOrTSE = 1,
        GREOrFFE = 2,
        GREOrFFEOrGRASS = 3,
        SpoiledGRE = 4,
        HASTEOrSSHOrFSE = 5,
        STIROrSPIROrSPAIR = 6,
        VIBEOrLAVAOrTHRIVEOrMDIXON = 7,
        DedicatedGRE = 8, 
        DedidactedGRE = 9,
        FSE = 10,
        LowMetalArtifactSequence = 11,
        STIROrSPIR = 12,
        SSGRE = 13,
        TSOrLLOrMOLLIOrShMOLLI = 14,
        PSIROrTIROrRIR = 15,
        STIRorSPIRorSPAIR = 16,
        FIESTAOrTrueFISPOrBalancedFFE = 17,
        DualOrMultiEcho = 18,
        GRET2 = 19,
        SEOrFSEOrTSE = 20,
        PSIFOrFFE = 21,
        DESS = 22,
        HASTEOrSSH = 23,
        SEOrTSEOrFSE = 24,
        VIBEOrLAVAOrTHRIVE = 25,
        DIXON = 26,
        MulitvaneOrBLADE = 27,
        TIRM = 28,
        TWIST = 29,
        Se = 30,
        MultiEchoMultiSe = 31,
        TseFse = 32,
        FseAmongOthersSpaceVista = 33,
        HasteUfse = 34,
        TirmIrTse = 35,
        PhaseSensitiveInversionRecoveryPsirTrueIrRealIr = 36,
        DirSpaceDualIrTse = 37,
        StirSpirSpair = 38,
        Flair = 39,
        GreFfe = 40,
        SpoiledGreUAFlashSpgr = 41,
        VibeThrive = 42,
        TrueFispBalancedFfe = 43,
        SteadyStateGrePsifT2FfeFispFfe = 44,
        SwiSwIp = 45,
        PhaseContrastPc = 46,
        TofMrAngio = 47,
        Mprage3DTfe = 48,
        NativeTrueFispBTrance = 49,
        TwistKeyhole4DTrak = 50,
        Ciss = 51,
        MultivaneBlade = 52,
        InPhaseOrOpposedPhase = 53
    }
}
