import { FindingBase } from '@models/shared/finding/finding.base';
import { FemaleGenderDiagnosisTypeEnum } from '@enums/pelvisMRT/female-sex/female-gender-diagnosis-type.enum';
import { ContrastEnhancementTypeEnum } from '@enums/pelvisMRT/female-sex/contrast-enhancement-type.enum';
import { HomogenityTypeEnum } from '@enums/pelvisMRT/female-sex/homogenity-type.enum';
import { FemaleGenderFindingTypeEnum } from '@enums/pelvisMRT/female-sex/female-gender-finding-type.enum';
import { HeterogeneousTypeEnum } from '@enums/pelvisMRT/female-sex/heterogeneous-type.enum';
import { MarginTypeEnum } from '@enums/pelvisMRT/female-sex/margin-type.enum';
import { FormTypeEnum } from '@enums/pelvisMRT/female-sex/form-type.enum';
import { TransitionZoneTypeEnum } from '@enums/pelvisMRT/female-sex/corpus-uteri-mass/transition-zone-type.enum';
import { FigoStageDetailsTypeEnum } from '@enums/pelvisMRT/female-sex/figo-stage-details-type.enum';
import { FigoStageTypeEnum } from '@enums/pelvisMRT/female-sex/figo-stage-type.enum';
import { DegenerationTypeEnum } from '@enums/pelvisMRT/female-sex/corpus-uteri-mass/degeneration-type.enum';
import { FigoClassification } from '@models/pelvisMRT/ui/localizers/figo-classification';
import { WideningObstructionTypeEnum } from '@enums/pelvisMRT/female-sex/widening-obstruction-type.enum';
import { DifferentialDiagnosisTypeEnum } from '@enums/pelvisMRT/female-sex/differential-diagnosis-type.enum';
import { SideTypeEnum } from '@enums/pelvisMRT/female-sex/side-type.enum';
import { PeritonealNodulesTypeEnum } from '@enums/pelvisMRT/female-sex/ovary-mass/peritoneal-nodules-type.enum';
import { DceMriTypeEnum } from '@enums/pelvisMRT/female-sex/ovary-mass/dce-mri-type.enum';
import { ComplexCysticTypeEnum } from '@enums/pelvisMRT/female-sex/uterine-tube-mass/complex-cystic-type.enum';

export class FemaleSexFindingBaseUiModel extends FindingBase {
  findingType: FemaleGenderFindingTypeEnum;
  differentialDiagnosis: FemaleGenderDiagnosisTypeEnum;
  t1wSignal: number;
  t2wSignal: number;
  additionalT1wSignal: number;
  homogenityType: HomogenityTypeEnum;
  contrastEnhancementType1: ContrastEnhancementTypeEnum;
  contrastEnhancementHomogenityType1: HomogenityTypeEnum;
  heterogeneousType: HeterogeneousTypeEnum;
  detailsT2wSignalHomogenityType: HomogenityTypeEnum;
  marginType: MarginTypeEnum;
  isFocalSignalVoids: boolean;
  isNecrosis: boolean;
  isComplexCystic: boolean;
  isSepta: boolean;
  isSeptaNodularParts: boolean;
  isFocalThickening: boolean;
  isDiffusionRestriction: boolean;
  formType: FormTypeEnum;
  isHemorrhage: boolean;
  isCapsuleOrPseudoCapsule: boolean;
  isT2wIncrease: boolean;
  transitionZoneType: TransitionZoneTypeEnum;
  isClawSign: boolean;
  isBridgingVesselSign: boolean;

  planeInMm: number;
  thirdPlaneInMm: number;
  isComplexCysticNodularParts: boolean;
  dceMriType: DceMriTypeEnum;
  isCentripetalEnhancement: boolean;
  isBeakSign: boolean;
  isPeritonealNodules: boolean;
  isRectouterinePouch: boolean;
  peritonealNodulesType: PeritonealNodulesTypeEnum;
  isAscites: boolean;
  isAscitesT1wSignalIncrease: boolean;
  isHemosiderin: boolean;
  isFocus: boolean;
  isGeneralized: boolean;
  isTubes: boolean;
  sideType: SideTypeEnum;
  isUterus: boolean;
  isParametria: boolean;
  isUrinaryBladder: boolean;
  isGut: boolean;
  differentialDiagnosisType1: DifferentialDiagnosisTypeEnum;
  isFollicularCysts1: boolean;
  isCystadenofibroma1: boolean;
  isTuboovarianAbscess1: boolean;
  isSalpingitis1: boolean;
  isKrukenbergTumor1: boolean;
  differentialDiagnosisType2: DifferentialDiagnosisTypeEnum;
  isFollicularCysts2: boolean;
  isCystadenofibroma2: boolean;
  isTuboovarianAbscess2: boolean;
  isSalpingitis2: boolean;
  isKrukenbergTumor2: boolean;
  isMucosalOrSubmucosal: boolean;
  isMucosalOrSubmucosalPedunculated: boolean;
  mucosalOrSubmucosalLengthInMm: number;
  isIntramural: boolean;
  isSubserous: boolean;
  isSubserousPedunculated: boolean;
  subserousLengthInMm: number;
  isExtensionIntoTheLigamentumLatumUteri: boolean;
  secondPlaneInMm: number;
  isFat: boolean;
  isCysts: boolean;
  isCalcification: boolean;
  isSignalVoids: boolean;
  isPerifocalEdema: boolean;
  isAbnormalVesselCollection: boolean;
  isCentralNidus: boolean;
  isLobulated: boolean;
  isFluidLevel: boolean;
  isFocal: boolean;
  isWideningOfTheInternalUterineOstium: boolean;
  wideningObstructionType: WideningObstructionTypeEnum;
  isObstructionOfTheEndometrialCanal: boolean;
  isCervixUteri: boolean;
  isIntactRingOfTheCervicalStroma: boolean;
  isVagina: boolean;
  isOvary: boolean;
  isRight: boolean;
  isLeft: boolean;
  isRectum: boolean;
  figoClassificationLocation1: FigoClassification;
  degenerationType1: DegenerationTypeEnum;
  isTorsion1: boolean;
  figoStageType1: FigoStageTypeEnum;
  figoStageAdditionalDetailsType1: FigoStageDetailsTypeEnum;
  figoClassificationLocation2: FigoClassification;
  degenerationType2: DegenerationTypeEnum;
  isTorsion2: boolean;
  figoStageType2: FigoStageTypeEnum;
  figoStageAdditionalDetailsType2: FigoStageDetailsTypeEnum;
  isIntactCervicalStromaRing: boolean;
  intactCervicalStromaRingHomogenityType: HomogenityTypeEnum;
  isDetailsCapsule: boolean;
  isCapsule: boolean;
  isPossiblySuperinfectedOrNecroticAreas: boolean;
  isCorpusUteri: boolean;
  isPelvisWall: boolean;
  isUreter: boolean;
  isHydroureter: boolean;
  is1BMacroinvasiveLesion1: boolean;
  figoStageDetailsType1: FigoStageDetailsTypeEnum;
  is1BMacroinvasiveLesion2: boolean;
  figoStageDetailsType2: FigoStageDetailsTypeEnum;
  isMarginal: boolean;
  isFistula: boolean;
  isVesicovaginal: boolean;
  isRectovaginal: boolean;
  isUnifocal: boolean;
  isMultifocal: boolean;
  isParavaginalSoftTissue: boolean;
  isPelvicWall: boolean;
  isPeritoneum: boolean;
  isDegeneration1: boolean;
  isBartholinitis1: boolean;
  isAbscess1: boolean;
  isDegeneration2: boolean;
  isBartholinitis2: boolean;
  isAbscess2: boolean;
  isDetectionOfACapsule: boolean;
  isExpansionBeyondTheCapsule: boolean;
  isIntestine: boolean;
  isHydrosalpinx: boolean;
  complexCysticType: ComplexCysticTypeEnum;
  isHydrosalpinxT1wSignalIncrease: boolean;
  isOtherIntestineParts: boolean;
  isHeterogeneousNodularParts: boolean;
  isParietal: boolean;
  isAlteredInternalStructureCapsule: boolean;

  constructor() {
    super();
    this.findingType = FemaleGenderFindingTypeEnum.None;
    this.differentialDiagnosis = FemaleGenderDiagnosisTypeEnum.None;
    this.t1wSignal = 0;
    this.t2wSignal = 0;
    this.additionalT1wSignal = 0;
    this.homogenityType = HomogenityTypeEnum.None;
    this.contrastEnhancementType1 = ContrastEnhancementTypeEnum.None;
    this.contrastEnhancementHomogenityType1 = HomogenityTypeEnum.None;
    this.heterogeneousType = HeterogeneousTypeEnum.None;
    this.detailsT2wSignalHomogenityType = HomogenityTypeEnum.None;
    this.marginType = MarginTypeEnum.None;
    this.isFocalSignalVoids = false;
    this.isNecrosis = false;
    this.isComplexCystic = false;
    this.isSepta = false;
    this.isSeptaNodularParts = false;
    this.isFocalThickening = false;
    this.isDiffusionRestriction = false;
    this.formType = FormTypeEnum.None;
    this.isHemorrhage = false;
    this.isCapsuleOrPseudoCapsule = false;
    this.isT2wIncrease = false;
    this.transitionZoneType = TransitionZoneTypeEnum.None;
    this.isClawSign = false;
    this.isBridgingVesselSign = false;

    this.planeInMm = null;
    this.thirdPlaneInMm = null;
    this.isComplexCysticNodularParts = false;
    this.dceMriType = DceMriTypeEnum.None;
    this.isCentripetalEnhancement = false;
    this.isBeakSign = false;
    this.isPeritonealNodules = false;
    this.isRectouterinePouch = false;
    this.peritonealNodulesType = PeritonealNodulesTypeEnum.None;
    this.isAscites = false;
    this.isAscitesT1wSignalIncrease = false;
    this.isHemosiderin = false;
    this.isFocus = false;
    this.isGeneralized = false;
    this.isTubes = false;
    this.sideType = SideTypeEnum.None;
    this.isUterus = false;
    this.isParametria = false;
    this.isUrinaryBladder = false;
    this.isGut = false;
    this.differentialDiagnosisType1 = DifferentialDiagnosisTypeEnum.None;
    this.isFollicularCysts1 = false;
    this.isCystadenofibroma1 = false;
    this.isTuboovarianAbscess1 = false;
    this.isSalpingitis1 = false;
    this.isKrukenbergTumor1 = false;
    this.differentialDiagnosisType2 = DifferentialDiagnosisTypeEnum.None;
    this.isFollicularCysts2 = false;
    this.isCystadenofibroma2 = false;
    this.isTuboovarianAbscess2 = false;
    this.isSalpingitis2 = false;
    this.isKrukenbergTumor2 = false;
    this.isMucosalOrSubmucosal = false;
    this.isMucosalOrSubmucosalPedunculated = false;
    this.mucosalOrSubmucosalLengthInMm = null;
    this.isIntramural = false;
    this.isSubserous = false;
    this.isSubserousPedunculated = false;
    this.subserousLengthInMm = null;
    this.isExtensionIntoTheLigamentumLatumUteri = false;
    this.secondPlaneInMm = null;
    this.isFat = false;
    this.isCysts = false;
    this.isCalcification = false;
    this.isSignalVoids = false;
    this.isPerifocalEdema = false;
    this.isAbnormalVesselCollection = false;
    this.isCentralNidus = false;
    this.isLobulated = false;
    this.isFluidLevel = false;
    this.isFocal = false;
    this.isWideningOfTheInternalUterineOstium = false;
    this.wideningObstructionType = WideningObstructionTypeEnum.None;
    this.isObstructionOfTheEndometrialCanal = false;
    this.isCervixUteri = false;
    this.isIntactRingOfTheCervicalStroma = false;
    this.isVagina = false;
    this.isOvary = false;
    this.isRight = false;
    this.isLeft = false;
    this.isRectum = false;
    this.figoClassificationLocation1 = new FigoClassification();
    this.degenerationType1 = DegenerationTypeEnum.None;
    this.isTorsion1 = false;
    this.figoStageType1 = FigoStageTypeEnum.None;
    this.figoStageAdditionalDetailsType1 = FigoStageDetailsTypeEnum.None;
    this.figoClassificationLocation2 = new FigoClassification();
    this.degenerationType2 = DegenerationTypeEnum.None;
    this.isTorsion2 = false;
    this.figoStageType2 = FigoStageTypeEnum.None;
    this.figoStageAdditionalDetailsType2 = FigoStageDetailsTypeEnum.None;
    this.isIntactCervicalStromaRing = false;
    this.intactCervicalStromaRingHomogenityType = HomogenityTypeEnum.None;
    this.isDetailsCapsule = false;
    this.isCapsule = false;
    this.isPossiblySuperinfectedOrNecroticAreas = false;
    this.isCorpusUteri = false;
    this.isPelvisWall = false;
    this.isUreter = false;
    this.isHydroureter = false;
    this.is1BMacroinvasiveLesion1 = false;
    this.figoStageDetailsType1 = FigoStageDetailsTypeEnum.None;
    this.is1BMacroinvasiveLesion2 = false;
    this.figoStageDetailsType2 = FigoStageDetailsTypeEnum.None;
    this.isMarginal = false;
    this.isFistula = false;
    this.isVesicovaginal = false;
    this.isRectovaginal = false;
    this.isUnifocal = false;
    this.isMultifocal = false;
    this.isParavaginalSoftTissue = false;
    this.isPelvicWall = false;
    this.isPeritoneum = false;
    this.isDegeneration1 = false;
    this.isBartholinitis1 = false;
    this.isAbscess1 = false;
    this.isDegeneration2 = false;
    this.isBartholinitis2 = false;
    this.isAbscess2 = false;
    this.isDetectionOfACapsule = false;
    this.isExpansionBeyondTheCapsule = false;
    this.isIntestine = false;
    this.isHydrosalpinx = false;
    this.complexCysticType = ComplexCysticTypeEnum.None;
    this.isHydrosalpinxT1wSignalIncrease = false;
    this.isOtherIntestineParts = false;
    this.isHeterogeneousNodularParts = false;
    this.isParietal = false;
    this.isAlteredInternalStructureCapsule = false;
  }
}
