import { PleuraFindingTypeEnum } from '@enums/thoraxMRT/pleura/pleura-finding-type.enum';
import { PleuraSiteTypeEnum } from '@enums/thoraxMRT/pleura/common/pleura-site-type.enum';
import { DistributionTypeEnum } from '@enums/thoraxMRT/pleura/pleural-effusion/distribution-type.enum';
import { FormTypeEnum } from '@enums/thoraxMRT/pleura/common/form-type.enum';
import { QualityTypeEnum } from '@enums/thoraxMRT/pleura/pleural-effusion/quality-type.enum';
import { FindingBase } from '@models/shared/finding/finding.base';
import { PleuraDiagnosisTypeEnum } from '@enums/thoraxMRT/pleura/common/pleura-diagnosis-type.enum';
import { DescriptionTypeEnum } from '@enums/shared/description-type.enum';
import { MarginTypeEnum } from '@enums/thoraxMRT/pleura/common/margin-type.enum';
import { HomogeneityTypeEnum } from '@enums/shared/homogeneity-type.enum';
import { LocalizationTypeEnum } from '@enums/thoraxMRT/pleura/pleural-thickening-mass/localization-type.enum';
import { AngleToThoracicWallTypeEnum } from '@enums/thoraxMRT/pleura/pleural-thickening-mass/angle-to-thoracic-wall-type.enum';
import { HistologyKnownTypeEnum } from '@enums/thoraxMRT/pleura/common/histology-known-type.enum';
import { DisplacementOfAdiposeTissueTypeEnum } from '@enums/thoraxMRT/pleura/pleural-thickening-mass/displacement-of-adipose-tissue-type.enum';
import { CysticChangesTypeEnum } from '@enums/thoraxMRT/pleura/common/cystic-changes-type.enum';
import { ContrastEnhancementQuantitativeTypeEnum } from '@enums/thoraxMRT/pleura/common/contrast-enhancement-quantitative-type.enum';
import { PneumothoraxTypeEnum } from '@enums/thoraxMRT/pleura/pneumothorax/pneumothorax-type.enum';
import { ExtensionTypeEnum } from '@enums/thoraxMRT/pleura/pneumothorax/extension-type.enum';
import { FocalSignalVoidsTypeEnum } from '@enums/thoraxMRT/pleura/common/focal-signal-voids-type.enum';
import { PleuraShapeTypeEnum } from '@enums/thoraxMRT/pleura/common/pleura-shape-type.enum';
import { ContrastEnhancementPatternTypeEnum } from '@enums/thoraxMRT/pleura/common/contrast-enhancement-pattern-type.enum';
import { DiffuseLesionTypeEnum } from '@enums/thoraxMRT/pleura/upper-abdomen-liver-gall-bladder/diffuse-lesion-type.enum';
import { LeasionLocalizationTypeEnum } from '@enums/thoraxMRT/pleura/upper-abdomen-pancreas/leasion-localization-type.enum';
import { GradingTypeEnum } from '@enums/thoraxMRT/pleura/upper-abdomen-kidney-adrenal-gland/grading-type.enum';
import { VolumeTypeEnum } from '@enums/thoraxMRT/pleura/mamma/volume-type.enum';
import { MammaShapeType } from '@enums/thoraxMRT/pleura/mamma/mamma-shape-type.enum';
import { LevelTypeEnum } from '@enums/thoraxMRT/pleura/chest-wall-soft-tissue/level-type.enum';
import { CraniocaudalTypeEnum } from '@enums/thoraxMRT/pleura/common/craniocaudal-type.enum';
import { FileApiModel } from '@models/shared/uploader/file-api.model';

export class PleuraFindingApiModel extends FindingBase {
  findingType: PleuraFindingTypeEnum;

  // Common

  isFocalSignalVoids: boolean;
  pleuraSiteType: PleuraSiteTypeEnum;
  descriptionType: DescriptionTypeEnum;
  homogeneityType: HomogeneityTypeEnum;
  isDiffusionRestriction: boolean;
  focalSignalVoidsType: FocalSignalVoidsTypeEnum;
  contrastEnhancementQuantitativeType: ContrastEnhancementQuantitativeTypeEnum;
  differentialDiagnosis: PleuraDiagnosisTypeEnum;
  isSuspicionOf: boolean;
  isHemorrhage: boolean;
  isNecrosis: boolean;
  isMoreThan1Lesion: boolean;

  // PleuralThickeningMass and ChestWallSoftTissueMass common
  isHistologyKnown: boolean;
  histologyKnownType: HistologyKnownTypeEnum;
  isAnterior: boolean;
  isLateral: boolean;
  isPosterior: boolean;
  expansionSizeInMM: number;
  secondPlaneInMm: number;
  thirdPlaneInMm: number;
  marginType: MarginTypeEnum;
  pleuraShapeType: PleuraShapeTypeEnum;
  t1wSignalType: string;
  t2wSignalType: string;
  isFat: boolean;
  isMacroscopic: boolean;
  isMicroscopic: boolean;
  cysticChangesType: CysticChangesTypeEnum;
  contrastEnhancementHomogeneityType: HomogeneityTypeEnum;
  contrastEnhancementPatternType: ContrastEnhancementPatternTypeEnum;
  differentialDiagnosis1: PleuraDiagnosisTypeEnum;
  differentialDiagnosis2: PleuraDiagnosisTypeEnum;
  isSubordinate: boolean;
  differentialDiagnosis3: PleuraDiagnosisTypeEnum;
  serialNumber: string;
  pictureNumber: string;
  imageFileId: string;
  uploadedImageFile: FileApiModel;

  // PleuralEffusion
  maxWidthInMM: number;
  pleuraFormType: FormTypeEnum;
  distributionType: DistributionTypeEnum;
  qualityType: QualityTypeEnum;
  isCoagulum: boolean;
  isT1wHyperintense: boolean;
  isCMEnrichingCapsule: boolean;
  isSedimentation: boolean;
  isSplitPleuraSign: boolean;

  // PleuralThickeningMass
  pleuralThickeningMassLocalizationType: LocalizationTypeEnum;
  pleuraLocalizationCraniocaudalType: CraniocaudalTypeEnum;
  isFissural: boolean;
  isMediastinal: boolean;
  angleToThoracicWallType: AngleToThoracicWallTypeEnum;
  displacementOfAdiposeTissueType: DisplacementOfAdiposeTissueTypeEnum;
  isCysticChanges: boolean;
  isNodularConfiguration: boolean;
  isInfiltrationChestWall: boolean;
  isInfiltrationOfExtrapleuralFatTissue: boolean;
  isArrosionAdjacentOsseousStructures: boolean;
  isAssociatedFindingsHemorrhage: boolean;

  // Pneumothorax
  pneumothoraxType: PneumothoraxTypeEnum;
  extensionType: ExtensionTypeEnum;
  expansionMaxWidthInMm: number;
  isMediastinalshift: boolean;
  mediastinalPleuraSiteType: PleuraSiteTypeEnum;
  isAtelectasis: boolean;
  isSoftTissueEmphysema: boolean;
  isPneumopericardium: boolean;
  isPneumomediastinum: boolean;

  // ChestWallSoftTissueMass
  craniocaudalType: CraniocaudalTypeEnum;
  spineLocations: string;
  ribLocations: string;
  isCysts: boolean;
  isLevel: boolean;
  levelType: LevelTypeEnum;
  isCapsule: boolean;
  isSepta: boolean;
  isNonDisplacing: boolean;
  isSubcutaneous: boolean;
  isInfiltration: boolean;
  isPleura: boolean;
  isPericardium: boolean;
  isBone: boolean;
  isLung: boolean;
  isMediastinum: boolean;
  isVessels: boolean;
  isCutaneousThickening: boolean;
  isPressureCorrosionRib: boolean;
  isSoftTissueEdema: boolean;
  isMuscleAtrophy: boolean;

  // Mamma
  volumeType: VolumeTypeEnum;
  isAblatioRight: boolean;
  isAblatioLeft: boolean;
  isBreastAugmentationRight: boolean;
  isBreastAugmentationLeft: boolean;
  isThickened: boolean;
  thickenedCutisBreastLocation: string;
  isObscured: boolean;
  isObscuredRight: boolean;
  isObscuredLeft: boolean;
  isMass: boolean;
  massBreastLocation: string;
  massMaxDiameterAxialInMm: number;
  mammaShapeType: MammaShapeType;
  mammaMarginType: MarginTypeEnum;
  mammaFocalSignalVoidsType: FocalSignalVoidsTypeEnum;

  // LymphNodesAxilla
  lymphNodesAxillaType: string;
  isLymphNodeRight: boolean;
  rightMarginalShortAxisDiameter: number;
  isLymphNodeLeft: boolean;
  leftMarginalShortAxisDiameter: number;
  isRightLevel1: boolean;
  isRightLevel2: boolean;
  isRightLevel3: boolean;
  isLeftLevel1: boolean;
  isLeftLevel2: boolean;
  isLeftLevel3: boolean;
  isContrastEnhancement: boolean;
  isSignalVoid: boolean;
  isAbscess: boolean;
  isVascularContact: boolean;

  // UpperAbdomenLiverGallBladder
  isFocalLiverLesion: boolean;
  focalLiverLesionMaxDiameterAxialInMm: number;
  isDiffuseLiverLesion: boolean;
  diffuseLesionType: DiffuseLesionTypeEnum;
  isSuspicionOfDiffuseLiverLesion: boolean;
  isCholecystolithiasis: boolean;
  isWallThickeningOfTheGallBladder: boolean;

  // UpperAbdomenPancreas
  isFocalPancreaticLesion: boolean;
  leasionLocalizationType: LeasionLocalizationTypeEnum;
  focalPancreaticLesionMaxDiameterInMm: number;
  isDiffusePancreaticLesion: boolean;
  isFattyAtrophy: boolean;
  isWirsungDuctDilatation: boolean;

  // UpperAbdomenKidneyAdrenalGland
  isKidney: boolean;
  isKidneyFocalLesion: boolean;
  focalLeasionSiteType: string;
  kidneyFocalLesionMaxDiameterInMm: number;
  isUrinaryRetention: boolean;
  isUrinaryRetentionRight: boolean;
  isUrinaryRetentionLeft: boolean;
  gradingType: GradingTypeEnum;
  isAdrenalGlandMass: boolean;
  adrenalGlandMassSiteType: PleuraSiteTypeEnum;
  massAdrenalGlandMaxDiameterInMm: number;
  massAdrenalGlandDifferentialDiagnosis: PleuraDiagnosisTypeEnum;
  isSuspicionOfMassAdrenalGland: boolean;

  // UpperAbdomenSpleenLymphNodesHernia
  isSplenomegaly: boolean;
  isEnlargedAbdominalLymphNodes: boolean;
  diameterSADInMm: number;
  isPathological: boolean;
  isPathologicalMultiple: boolean;
  isPathologicalConglomerate: boolean;
  isPathologicalHiatalHernia: boolean;

  // UpperAbdomenAscites
  isPerihepatic: boolean;
  isPerisplenic: boolean;
  isAscitesNotFurtherDefined: boolean;

  constructor() {
    super();
    this.findingType = PleuraFindingTypeEnum.None;

    // Common

    this.isFocalSignalVoids = false;
    this.pleuraSiteType = PleuraSiteTypeEnum.None;
    this.descriptionType = DescriptionTypeEnum.None;
    this.homogeneityType = HomogeneityTypeEnum.None;
    this.isDiffusionRestriction = false;
    this.focalSignalVoidsType = FocalSignalVoidsTypeEnum.None;
    this.contrastEnhancementQuantitativeType = ContrastEnhancementQuantitativeTypeEnum.None;
    this.differentialDiagnosis = PleuraDiagnosisTypeEnum.None;
    this.isSuspicionOf = false;
    this.isHemorrhage = false;
    this.isNecrosis = false;
    this.isMoreThan1Lesion = false;
    this.isHistologyKnown = false;
    this.histologyKnownType = HistologyKnownTypeEnum.None;
    this.isAnterior = false;
    this.isLateral = false;
    this.isPosterior = false;
    this.expansionSizeInMM = null;
    this.secondPlaneInMm = null;
    this.thirdPlaneInMm = null;
    this.marginType = MarginTypeEnum.None;
    this.pleuraShapeType = PleuraShapeTypeEnum.None;
    this.t1wSignalType = 'None';
    this.t2wSignalType = 'None';
    this.isFat = false;
    this.isMacroscopic = false;
    this.isMicroscopic = false;
    this.cysticChangesType = CysticChangesTypeEnum.None;
    this.contrastEnhancementHomogeneityType = HomogeneityTypeEnum.None;
    this.contrastEnhancementPatternType = ContrastEnhancementPatternTypeEnum.None;
    this.differentialDiagnosis1 = PleuraDiagnosisTypeEnum.None;
    this.differentialDiagnosis2 = PleuraDiagnosisTypeEnum.None;
    this.isSubordinate = false;
    this.differentialDiagnosis3 = PleuraDiagnosisTypeEnum.None;
    this.serialNumber = '';
    this.pictureNumber = '';
    this.imageFileId = null;
    this.uploadedImageFile = null;
    this.maxWidthInMM = null;
    this.pleuraFormType = FormTypeEnum.None;
    this.distributionType = DistributionTypeEnum.None;
    this.qualityType = QualityTypeEnum.None;
    this.isCoagulum = false;
    this.isT1wHyperintense = false;
    this.isCMEnrichingCapsule = false;
    this.isSedimentation = false;
    this.isSplitPleuraSign = false;
    this.pleuralThickeningMassLocalizationType = LocalizationTypeEnum.None;
    this.pleuraLocalizationCraniocaudalType = CraniocaudalTypeEnum.None;
    this.isFissural = false;
    this.isMediastinal = false;
    this.angleToThoracicWallType = AngleToThoracicWallTypeEnum.None;
    this.displacementOfAdiposeTissueType = DisplacementOfAdiposeTissueTypeEnum.None;
    this.isCysticChanges = false;
    this.isNodularConfiguration = false;
    this.isInfiltrationChestWall = false;
    this.isInfiltrationOfExtrapleuralFatTissue = false;
    this.isArrosionAdjacentOsseousStructures = false;
    this.isAssociatedFindingsHemorrhage = false;
    this.pneumothoraxType = PneumothoraxTypeEnum.None;
    this.extensionType = ExtensionTypeEnum.None;
    this.expansionMaxWidthInMm = null;
    this.isMediastinalshift = false;
    this.mediastinalPleuraSiteType = PleuraSiteTypeEnum.None;
    this.isAtelectasis = false;
    this.isSoftTissueEmphysema = false;
    this.isPneumopericardium = false;
    this.isPneumomediastinum = false;
    this.craniocaudalType = CraniocaudalTypeEnum.None;
    this.spineLocations = 'None';
    this.ribLocations = 'None';
    this.isCysts = false;
    this.isLevel = false;
    this.levelType = LevelTypeEnum.None;
    this.isCapsule = false;
    this.isSepta = false;
    this.isNonDisplacing = false;
    this.isSubcutaneous = false;
    this.isInfiltration = false;
    this.isPleura = false;
    this.isPericardium = false;
    this.isBone = false;
    this.isLung = false;
    this.isMediastinum = false;
    this.isVessels = false;
    this.isCutaneousThickening = false;
    this.isPressureCorrosionRib = false;
    this.isSoftTissueEdema = false;
    this.isMuscleAtrophy = false;
    this.volumeType = VolumeTypeEnum.None;
    this.isAblatioRight = false;
    this.isAblatioLeft = false;
    this.isBreastAugmentationRight = false;
    this.isBreastAugmentationLeft = false;
    this.isThickened = false;
    this.thickenedCutisBreastLocation = 'None';
    this.isObscured = false;
    this.isObscuredRight = false;
    this.isObscuredLeft = false;
    this.isMass = false;
    this.massBreastLocation = 'None';
    this.massMaxDiameterAxialInMm = null;
    this.mammaShapeType = MammaShapeType.None;
    this.mammaMarginType = MarginTypeEnum.None;
    this.mammaFocalSignalVoidsType = FocalSignalVoidsTypeEnum.None;
    this.lymphNodesAxillaType = 'None';
    this.isLymphNodeRight = false;
    this.rightMarginalShortAxisDiameter = null;
    this.isLymphNodeLeft = false;
    this.leftMarginalShortAxisDiameter = null;
    this.isRightLevel1 = false;
    this.isRightLevel2 = false;
    this.isRightLevel3 = false;
    this.isLeftLevel1 = false;
    this.isLeftLevel2 = false;
    this.isLeftLevel3 = false;
    this.isContrastEnhancement = false;
    this.isSignalVoid = false;
    this.isAbscess = false;
    this.isVascularContact = false;
    this.isFocalLiverLesion = false;
    this.focalLiverLesionMaxDiameterAxialInMm = null;
    this.isDiffuseLiverLesion = false;
    this.diffuseLesionType = DiffuseLesionTypeEnum.None;
    this.isSuspicionOfDiffuseLiverLesion = false;
    this.isCholecystolithiasis = false;
    this.isWallThickeningOfTheGallBladder = false;
    this.isFocalPancreaticLesion = false;
    this.leasionLocalizationType = LeasionLocalizationTypeEnum.None;
    this.focalPancreaticLesionMaxDiameterInMm = null;
    this.isDiffusePancreaticLesion = false;
    this.isFattyAtrophy = false;
    this.isWirsungDuctDilatation = false;
    this.isKidney = false;
    this.isKidneyFocalLesion = false;
    this.focalLeasionSiteType = 'None';
    this.kidneyFocalLesionMaxDiameterInMm = null;
    this.isUrinaryRetention = false;
    this.isUrinaryRetentionRight = false;
    this.isUrinaryRetentionLeft = false;
    this.gradingType = GradingTypeEnum.None;
    this.isAdrenalGlandMass = false;
    this.adrenalGlandMassSiteType = PleuraSiteTypeEnum.None;
    this.massAdrenalGlandMaxDiameterInMm = null;
    this.massAdrenalGlandDifferentialDiagnosis = PleuraDiagnosisTypeEnum.None;
    this.isSuspicionOfMassAdrenalGland = false;
    this.isSplenomegaly = false;
    this.isEnlargedAbdominalLymphNodes = false;
    this.diameterSADInMm = null;
    this.isPathological = false;
    this.isPathologicalMultiple = false;
    this.isPathologicalConglomerate = false;
    this.isPathologicalHiatalHernia = false;
    this.isPerihepatic = false;
    this.isPerisplenic = false;
    this.isAscitesNotFurtherDefined = false;
  }
}
