export enum AnamnesisClinicTypeEnum {
  None = 'None',
  Pain = 'Pain',
  ChronicPain = 'ChronicPain',
  Colic = 'Colic',
  UnclearSymptoms = 'UnclearSymptoms',
  PassengerDisturbance = 'PassengerDisturbance',
  ChronicInflammatoryBowelDiseaseCed = 'ChronicInflammatoryBowelDiseaseCed',
  Vomiting = 'Vomiting',
  Diarrhea = 'Diarrhea',
  FistulaFormation = 'FistulaFormation',
  AnastomoticInsufficiency = 'AnastomoticInsufficiency',
  UpperGastrointestinalBleeding = 'UpperGastrointestinalBleeding',
  LowerGastrointestinalBleeding = 'LowerGastrointestinalBleeding',
  Hypertension = 'Hypertension',
  Hematuria = 'Hematuria',
  HormonalDisturbance = 'HormonalDisturbance',
  UnwantedWeightLoss = 'UnwantedWeightLoss',
  Icterus = 'Icterus',
  BSymptomatics = 'BSymptomatics',
  Lymphadenopathy = 'Lymphadenopathy'
}
