namespace RadioReport.HeadMRT.Domain.Enums.FacialSkull
{
    public enum FacialSkullDiagnosisType : byte
    {
        None = 0,
        BenignLesionNotFurtherSpecified = 1,
        MalignantLesionNotFurtherSpecified = 2,
        UnclearEtiology = 3,
        Meningioma = 4,
        OlfactoryGrooveMeningioma = 5,
        Schwannoma = 6,
        OssifyingFibroma = 7,
        GiantCellTumourBenign = 8,
        GlomusJugulareBenign = 9,
        Metastasis = 10,
        Plasmocytoma = 11,
        GiantCellTumourMalignat = 12,
        ClivalChordoma = 13,
        Chondrosarcoma = 14,
        GlomusJugulareMalignat = 15,
        Osteomyelitis = 16,
        Inflammation = 17,
        PostInflammatoryChange = 18,
        PagetsDisease = 19,
        Abscess = 20,
        Fracture = 21,
        EosinophilicGranuloma = 22,
        FibrousDysplasia = 23,
        Osteoma = 24,
        HyperostosisFrontalisInterna = 25,
        GalealHaematoma = 26,
        Cephalohematoma = 27,
        LangerhansCellHistiocytosis = 28,
        AcousticNeuroma = 29,
        GlomusTympanicum = 30,
        Epidermoid = 31,
        ArachnoidCyst = 32,
        OtitisMedia = 33,
        Labyrinthitis = 34,
        FacialNeuritis = 35,
        Otosyphilis = 36,
        Otosclerosis = 37,
        LabyrinthFistula = 38,
        Cholesteatoma = 39,
        CholesterolGranuloma = 40
    }
}
