import { DescriptionTypeEnum } from '@enums/shared/description-type.enum';
import { RelationPituitaryGlandTypeEnum } from '@enums/headMRT/sellar-region/relation-pituitar-gland-type.enum';
import { SellarRegionDiagnosisTypeEnum } from '@enums/headMRT/sellar-region/sellar-region-diagnosis-type.enum';
import { SideTypeEnum } from '@enums/headMRT/common/side-type.enum';
import { SellarRegionFindingBaseApiModel } from '@models/headMRT/api/sellar-region/sellar-region-finding-base-api.model';

export class SellarRegionFindingApiModel extends SellarRegionFindingBaseApiModel {
  descriptionType: DescriptionTypeEnum;
  relationToThePituitaryGlandType: RelationPituitaryGlandTypeEnum;
  isNeurohypophysis: boolean;
  isAdenohypophysis: boolean;
  isPituitaryStalk: boolean;
  sideType: SideTypeEnum;
  isCavernousSinus: boolean;
  isOpticNerveI: boolean;
  isOpticChiasm: boolean;
  isOlfactoryNerveII: boolean;
  isOculomotorNerveIII: boolean;
  isTrochlearNerveIV: boolean;
  isAbducensNerveVI: boolean;
  isInternalCarotidArtery: boolean;
  isDuraMaterMeningen: boolean;
  isSphenoidSinus: boolean;
  isNasopharynx: boolean;
  extensionSize: number;
  extensionSize2ndPlane: number;
  extensionSize3rdPlane: number;
  isDiffusionRestriction: boolean;
  isHemorrhage: boolean;
  isCalcification: boolean;
  isFat: boolean;
  isCapsule: boolean;
  isSignalVoids: boolean;
  isToothBoneFormation: boolean;
  isDisplacement: boolean;
  isInfiltration: boolean;
  isHydrocephalus: boolean;
  isBonyRemodeling: boolean;
  isContactWithCarotidArtery: boolean;
  carotidArterySideType: SideTypeEnum;
  isDisplacementOfPituitaryStalk: boolean;
  pituitaryStalkSideType: SideTypeEnum; //
  isInfiltrationIntoCavernousSinus: boolean;
  isSuspicionOfInfiltration: boolean;
  isExtensionToSuprasellar: boolean;
  isAffectionOpticChiasm: boolean;
  isDetectionOfLesion: boolean;
  sellarRegionDiagnosis1Type: SellarRegionDiagnosisTypeEnum;
  sellarRegionDiagnosis2Type: SellarRegionDiagnosisTypeEnum;
  sellarRegionDiagnosis3Type: SellarRegionDiagnosisTypeEnum;
  isSuspicionOf: boolean;
  isSubordinate: boolean;
  is1LesionOfTheSameEntity: boolean;

  constructor() {
    super();
    this.descriptionType = DescriptionTypeEnum.None;

    this.relationToThePituitaryGlandType = RelationPituitaryGlandTypeEnum.None;
    this.isNeurohypophysis = false;
    this.isAdenohypophysis = false;
    this.isPituitaryStalk = false;
    this.sideType = SideTypeEnum.None;
    this.isCavernousSinus = false;
    this.isOpticNerveI = false;
    this.isOpticChiasm = false;
    this.isOlfactoryNerveII = false;
    this.isOculomotorNerveIII = false;
    this.isTrochlearNerveIV = false;
    this.isAbducensNerveVI = false;
    this.isInternalCarotidArtery = false;
    this.isDuraMaterMeningen = false;
    this.isSphenoidSinus = false;
    this.isNasopharynx = false;
    this.extensionSize = null;
    this.extensionSize2ndPlane = null;
    this.extensionSize3rdPlane = null;
    this.isDiffusionRestriction = false;
    this.isHemorrhage = false;
    this.isCalcification = false;
    this.isFat = false;
    this.isCapsule = false;
    this.isSignalVoids = false;
    this.isToothBoneFormation = false;
    this.isDisplacement = false;
    this.isInfiltration = false;
    this.isHydrocephalus = false;
    this.isBonyRemodeling = false;
    this.isContactWithCarotidArtery = false;
    this.carotidArterySideType = SideTypeEnum.None;
    this.isDisplacementOfPituitaryStalk = false;
    this.pituitaryStalkSideType = SideTypeEnum.None;
    this.isInfiltrationIntoCavernousSinus = false;
    this.isSuspicionOfInfiltration = false;
    this.isExtensionToSuprasellar = false;
    this.isAffectionOpticChiasm = false;
    this.isDetectionOfLesion = false;
    this.sellarRegionDiagnosis1Type = SellarRegionDiagnosisTypeEnum.None;
    this.sellarRegionDiagnosis2Type = SellarRegionDiagnosisTypeEnum.None;
    this.sellarRegionDiagnosis3Type = SellarRegionDiagnosisTypeEnum.None;
    this.isSuspicionOf = false;
    this.isSubordinate = false;
    this.is1LesionOfTheSameEntity = false;
  }
}
