import { SideTypeEnum } from '@enums/pelvisMRT/female-sex/side-type.enum';
import { SideSubTypeEnum } from '@enums/pelvisMRT/female-sex/side-sub-type.enum';
import { LocalizationTypeEnum } from '@enums/pelvisMRT/female-sex/localization-type.enum';
import { LocalizationSubTypeEnum } from '@enums/pelvisMRT/female-sex/localization-sub-type.enum';
import { LocalizationOfMassTypeEnum } from '@enums/pelvisMRT/female-sex/localization-of-mass-type.enum';
import { EndometriosisLocalizationTypeEnum } from '@enums/pelvisMRT/female-sex/endometriosis-localization-type.enum';
import { FemaleGenderDiagnosisTypeEnum } from '@enums/pelvisMRT/female-sex/female-gender-diagnosis-type.enum';
import { DifferentialDiagnosisTypeEnum } from '@enums/pelvisMRT/female-sex/differential-diagnosis-type.enum';
import { ContrastEnhancementTypeEnum } from '@enums/pelvisMRT/female-sex/contrast-enhancement-type.enum';
import { HomogenityTypeEnum } from '@enums/pelvisMRT/female-sex/homogenity-type.enum';
import { DescriptionTypeEnum } from '@enums/shared/description-type.enum';
import { SurroundingDetailsTypeEnum } from '@enums/pelvisMRT/female-sex/surrounding-details-type.enum';
import { WideningObstructionTypeEnum } from '@enums/pelvisMRT/female-sex/widening-obstruction-type.enum';
import { FigoStageTypeEnum } from '@enums/pelvisMRT/female-sex/figo-stage-type.enum';
import { FigoStageDetailsTypeEnum } from '@enums/pelvisMRT/female-sex/figo-stage-details-type.enum';
import { DceMriTypeEnum } from '@enums/pelvisMRT/female-sex/ovary-mass/dce-mri-type.enum';
import { PeritonealNodulesTypeEnum } from '@enums/pelvisMRT/female-sex/ovary-mass/peritoneal-nodules-type.enum';
import { ComplexCysticTypeEnum } from '@enums/pelvisMRT/female-sex/uterine-tube-mass/complex-cystic-type.enum';
import { DegenerationTypeEnum } from '@enums/pelvisMRT/female-sex/corpus-uteri-mass/degeneration-type.enum';
import { FemaleSexFindingBaseApiModel } from '@models/pelvisMRT/api/female-sex/female-sex-finding-base-api.model';
import { DepthOfInfiltrationTypeEnum } from '@enums/pelvisMRT/female-sex/endometriosis/depth-of-infiltration-type.enum';
import { SubperitonealInfiltrationTypeEnum } from '@enums/pelvisMRT/female-sex/endometriosis/subperitoneal-infiltration-type.enum';
import { ComplicationsTypeEnum } from '@enums/pelvisMRT/female-sex/endometriosis/complications-type.enum';

export class FemaleSexFindingApiModel extends FemaleSexFindingBaseApiModel {
  isRight: boolean;
  isLeft: boolean;
  sideType: SideTypeEnum;
  labiaMajoraSideType: SideTypeEnum;
  labiaMinoraSideType: SideTypeEnum;
  sideSubType: SideSubTypeEnum;
  localizationType: LocalizationTypeEnum;
  localizationSubType: LocalizationSubTypeEnum;
  localizationOfMassType: LocalizationOfMassTypeEnum;
  endometriosisLocalizationType: EndometriosisLocalizationTypeEnum;
  differentialDiagnosis1: FemaleGenderDiagnosisTypeEnum;
  differentialDiagnosis2: FemaleGenderDiagnosisTypeEnum;
  isSubordinate: boolean;
  differentialDiagnosisType1: DifferentialDiagnosisTypeEnum;
  differentialDiagnosisType2: DifferentialDiagnosisTypeEnum;
  additionalT2wSignal: string;
  contrastEnhancementType2: ContrastEnhancementTypeEnum;
  contrastEnhancementHomogenityType2: HomogenityTypeEnum;
  contrastEnhancementType3: ContrastEnhancementTypeEnum;
  intactCervicalStromaRingHomogenityType: HomogenityTypeEnum;
  descriptionType: DescriptionTypeEnum;
  sizeInMm: number;
  secondPlaneInMm: number;
  thirdPlaneInMm: number;
  isPeritonealNodules: boolean;
  isRectouterinePouch: boolean;
  isAscites: boolean;
  isAscitesT1wSignalIncrease: boolean;
  isHemosiderin: boolean;
  isFocal: boolean;
  isGeneralized: boolean;
  isUterus: boolean;
  isParametria: boolean;
  isUrinaryBladder: boolean;
  isTuboovarianAbscess1: boolean;
  isTuboovarianAbscess2: boolean;
  isEnlarged: boolean;
  isTwistedOvarianVessel: boolean;
  isPeripheralFollicularDisplacement: boolean;
  surroundingDetailsType: SurroundingDetailsTypeEnum;
  isOvarianVeinThrombosis: boolean;
  expansionInMm: number;
  isPeritonealContrastEnhancement: boolean;
  isIleus: boolean;
  isHydroureter: boolean;
  isPID: boolean;
  isHydrosalpinxT1wSignalIncrease: boolean;
  isHeterogeneousNodularParts: boolean;
  isParietal: boolean;
  isUnifocal: boolean;
  isMultifocal: boolean;
  isOvary: boolean;
  isBladder: boolean;
  isRectum: boolean;
  isWallThickening: boolean;
  isFat: boolean;
  isCysts: boolean;
  isSignalVoids: boolean;
  wideningObstructionType: WideningObstructionTypeEnum;
  isObstructionOfTheEndometrialCanal: boolean;
  isCervixUteri: boolean;
  isVagina: boolean;
  figoStageType1: FigoStageTypeEnum;
  figoStageType2: FigoStageTypeEnum;
  figoStageDetailsType1: FigoStageDetailsTypeEnum;
  figoStageDetailsType2: FigoStageDetailsTypeEnum;
  figoStageAdditionalDetailsType1: FigoStageDetailsTypeEnum;
  figoStageAdditionalDetailsType2: FigoStageDetailsTypeEnum;
  isThickenedEndometrium: boolean;
  isThickenedUterosacralLigaments: boolean;
  isContrastEnhancement: boolean;
  isPossiblySuperinfectedOrNecroticAreas: boolean;
  isUreter: boolean;
  isMarginal: boolean;
  isCapsule: boolean;
  isDegeneration1: boolean;
  isDegeneration2: boolean;
  isAbscess1: boolean;
  isAbscess2: boolean;
  isDetectionOfACapsule: boolean;
  isExpansionBeyondTheCapsule: boolean;
  isComplexCysticNodularParts: boolean;
  dceMriType: DceMriTypeEnum;
  isCentripetalEnhancement: boolean;
  isBeakSign: boolean;
  peritonealNodulesType: PeritonealNodulesTypeEnum;
  isTubes: boolean;
  isIntestine: boolean;
  isFollicularCysts1: boolean;
  isFollicularCysts2: boolean;
  isCystadenofibroma1: boolean;
  isCystadenofibroma2: boolean;
  isSalpingitis1: boolean;
  isSalpingitis2: boolean;
  isKrukenbergTumor1: boolean;
  isKrukenbergTumor2: boolean;
  isDetailsT2wSignalIncrease: boolean;
  isPolycysticChanges: boolean;
  isCentralStromaEnlargement: boolean;
  isSurroundingT2wSignalIncrease: boolean;
  isEnlargementOfTheCentralAfollicularStromas: boolean;
  isHematoma: boolean;
  isFocalOrParietalT1wSignalIncrease: boolean;
  isEnlargedOvary: boolean;
  isT2wSignalIncrease: boolean;
  isOvarianMass: boolean;
  isHematosalpinx: boolean;
  isIpsilateralUterineDeviation: boolean;
  complexCysticType: ComplexCysticTypeEnum;
  isOtherIntestineParts: boolean;
  isDilatedLumen: boolean;
  isIntraluminalFluid: boolean;
  uterusLocation: string; /// localizer
  sizeUterusAxialInMm: number;
  secondPlaneOrthogonalInMm: number;
  craniocaudalInMm: number;
  diameterOfTheEndometriumInMm: number;
  diameterOfEndometrialMyometrialZoneInMm: number;
  isMucosalOrSubmucosal: boolean;
  isMucosalOrSubmucosalPedunculated: boolean;
  mucosalOrSubmucosalLengthInMm: number;
  isIntramural: boolean;
  isSubserous: boolean;
  isSubserousPedunculated: boolean;
  subserousLengthInMm: number;
  isExtensionIntoTheLigamentumLatumUteri: boolean;
  isPerifocalEdema: boolean;
  isAbnormalVesselCollection: boolean;
  isCentralNidus: boolean;
  isLobulated: boolean;
  isFluidLevel: boolean;
  isWideningOfTheInternalUterineOstium: boolean;
  isIntactRingOfTheCervicalStroma: boolean;
  figoClassificationLocation1: string;
  figoClassificationLocation2: string;
  degenerationType2: DegenerationTypeEnum;
  isTorsion1: boolean;
  isTorsion2: boolean;
  isFocalSignalVoidIntrauterine: boolean;
  isMarkedUterineVessels: boolean;
  isIntactCervicalStromaRing: boolean;
  isDetailsCapsule: boolean;
  isAlteredInternalStructureCapsule: boolean;
  isCorpusUteri: boolean;
  isPelvisWall: boolean;
  is1BMacroinvasiveLesion1: boolean;
  is1BMacroinvasiveLesion2: boolean;
  isFocalSignalVoidsInTheCervicalCanal: boolean;
  isMarkedCervicalVessels: boolean;
  isFistula: boolean;
  isVesicovaginal: boolean;
  isRectovaginal: boolean;
  isParavaginalSoftTissue: boolean;
  isPelvicWall: boolean;
  isPeritoneum: boolean;
  isBartholinitis1: boolean;
  isBartholinitis2: boolean;
  isFluidDebrisLevel: boolean;
  isVaginalDisplacement: boolean;
  isPerineum: boolean;
  isUrethra: boolean;
  isAnalSphincter: boolean;
  isAnusOrRectum: boolean;
  isUrethralLeiomyoma1: boolean;
  isUrethralLeiomyoma2: boolean;
  isUrethralMetastasis1: boolean;
  isUrethralMetastasis2: boolean;
  isSoftTissueSwelling: boolean;
  isFourniersGangrene: boolean;
  isVenousThrombosis: boolean;
  isT2wSignalIncreasePerivascular: boolean;
  isCystOfSkenesGlands: boolean;
  isUrethralDiverticula: boolean;
  isHypointenseCapsule: boolean;
  isSpicula: boolean;
  isNodular: boolean;
  isLigamentousThickening: boolean;
  isMushroomSign: boolean;
  isShading: boolean;
  isMultifocalSignalIncreaseT1w: boolean;
  isMultifocalSignalIncreaseT2w: boolean;
  isCystic: boolean;
  isComplex: boolean;
  isDetectionOfBloodClots: boolean;
  isInternalBleeding: boolean;
  depthOfInfiltrationType: DepthOfInfiltrationTypeEnum;
  subperitonealInfiltrationType: SubperitonealInfiltrationTypeEnum;
  isPerifocalFatTissueObliteration: boolean;
  isPerifocalTighteningOrShortening: boolean;
  complicationsType: ComplicationsTypeEnum;
  isAtTheLevelOfTheUreterostium: boolean;
  isPrestenoticDilatation: boolean;
  isPoststenoticCollapse: boolean;
  isPosteriorDisplacementOfTheUterus: boolean;
  isPosteriorDisplacementOfTheOvaries: boolean;
  isKissingOvaries: boolean;
  isCranialDisplacementOfThePosteriorFornixVaginae: boolean;
  isDisplacementOfIntestinalLoops: boolean;
  isMoreThan1LesionSamePathology: boolean;

  constructor() {
    super();

    this.isRight = false;
    this.isLeft = false;
    this.sideType = SideTypeEnum.None;
    this.labiaMajoraSideType = SideTypeEnum.None;
    this.labiaMinoraSideType = SideTypeEnum.None;
    this.sideSubType = SideSubTypeEnum.None;
    this.localizationType = LocalizationTypeEnum.None;
    this.localizationSubType = LocalizationSubTypeEnum.None;
    this.localizationOfMassType = LocalizationOfMassTypeEnum.None;
    this.endometriosisLocalizationType = EndometriosisLocalizationTypeEnum.None;
    this.differentialDiagnosis1 = FemaleGenderDiagnosisTypeEnum.None;
    this.differentialDiagnosis2 = FemaleGenderDiagnosisTypeEnum.None;
    this.isSubordinate = false;
    this.differentialDiagnosisType1 = DifferentialDiagnosisTypeEnum.None;
    this.differentialDiagnosisType2 = DifferentialDiagnosisTypeEnum.None;
    this.additionalT2wSignal = 'None';
    this.contrastEnhancementType2 = ContrastEnhancementTypeEnum.None;
    this.contrastEnhancementHomogenityType2 = HomogenityTypeEnum.None;
    this.contrastEnhancementType3 = ContrastEnhancementTypeEnum.None;
    this.intactCervicalStromaRingHomogenityType = HomogenityTypeEnum.None;
    this.descriptionType = DescriptionTypeEnum.None;
    this.sizeInMm = null;
    this.secondPlaneInMm = null;
    this.thirdPlaneInMm = null;
    this.isPeritonealNodules = false;
    this.isRectouterinePouch = false;
    this.isAscites = false;
    this.isAscitesT1wSignalIncrease = false;
    this.isHemosiderin = false;
    this.isFocal = false;
    this.isGeneralized = false;
    this.isUterus = false;
    this.isParametria = false;
    this.isUrinaryBladder = false;
    this.isTuboovarianAbscess1 = false;
    this.isTuboovarianAbscess2 = false;
    this.isEnlarged = false;
    this.isTwistedOvarianVessel = false;
    this.isPeripheralFollicularDisplacement = false;
    this.surroundingDetailsType = SurroundingDetailsTypeEnum.None;
    this.isOvarianVeinThrombosis = false;
    this.expansionInMm = null;
    this.isPeritonealContrastEnhancement = false;
    this.isIleus = false;
    this.isHydroureter = false;
    this.isPID = false;
    this.isHydrosalpinxT1wSignalIncrease = false;
    this.isHeterogeneousNodularParts = false;
    this.isParietal = false;
    this.isUnifocal = false;
    this.isMultifocal = false;
    this.isOvary = false;
    this.isBladder = false;
    this.isRectum = false;
    this.isWallThickening = false;
    this.isFat = false;
    this.isCysts = false;
    this.isSignalVoids = false;
    this.wideningObstructionType = WideningObstructionTypeEnum.None;
    this.isObstructionOfTheEndometrialCanal = false;
    this.isCervixUteri = false;
    this.isVagina = false;
    this.figoStageType1 = FigoStageTypeEnum.None;
    this.figoStageType2 = FigoStageTypeEnum.None;
    this.figoStageDetailsType1 = FigoStageDetailsTypeEnum.None;
    this.figoStageDetailsType2 = FigoStageDetailsTypeEnum.None;
    this.figoStageAdditionalDetailsType1 = FigoStageDetailsTypeEnum.None;
    this.figoStageAdditionalDetailsType2 = FigoStageDetailsTypeEnum.None;
    this.isThickenedEndometrium = false;
    this.isThickenedUterosacralLigaments = false;
    this.isContrastEnhancement = false;
    this.isPossiblySuperinfectedOrNecroticAreas = false;
    this.isUreter = false;
    this.isMarginal = false;
    this.isCapsule = false;
    this.isDegeneration1 = false;
    this.isDegeneration2 = false;
    this.isAbscess1 = false;
    this.isAbscess2 = false;
    this.isDetectionOfACapsule = false;
    this.isExpansionBeyondTheCapsule = false;
    this.isComplexCysticNodularParts = false;
    this.dceMriType = DceMriTypeEnum.None;
    this.isCentripetalEnhancement = false;
    this.isBeakSign = false;
    this.peritonealNodulesType = PeritonealNodulesTypeEnum.None;
    this.isTubes = false;
    this.isIntestine = false;
    this.isFollicularCysts1 = false;
    this.isFollicularCysts2 = false;
    this.isCystadenofibroma1 = false;
    this.isCystadenofibroma2 = false;
    this.isSalpingitis1 = false;
    this.isSalpingitis2 = false;
    this.isKrukenbergTumor1 = false;
    this.isKrukenbergTumor2 = false;
    this.isDetailsT2wSignalIncrease = false;
    this.isPolycysticChanges = false;
    this.isCentralStromaEnlargement = false;
    this.isSurroundingT2wSignalIncrease = false;
    this.isEnlargementOfTheCentralAfollicularStromas = false;
    this.isHematoma = false;
    this.isFocalOrParietalT1wSignalIncrease = false;
    this.isEnlargedOvary = false;
    this.isT2wSignalIncrease = false;
    this.isOvarianMass = false;
    this.isHematosalpinx = false;
    this.isIpsilateralUterineDeviation = false;
    this.complexCysticType = ComplexCysticTypeEnum.None;
    this.isOtherIntestineParts = false;
    this.isDilatedLumen = false;
    this.isIntraluminalFluid = false;
    this.uterusLocation = 'None'; /// localizer
    this.sizeUterusAxialInMm = null;
    this.secondPlaneOrthogonalInMm = null;
    this.craniocaudalInMm = null;
    this.diameterOfTheEndometriumInMm = null;
    this.diameterOfEndometrialMyometrialZoneInMm = null;
    this.isMucosalOrSubmucosal = false;
    this.isMucosalOrSubmucosalPedunculated = false;
    this.mucosalOrSubmucosalLengthInMm = null;
    this.isIntramural = false;
    this.isSubserous = false;
    this.isSubserousPedunculated = false;
    this.subserousLengthInMm = null;
    this.isExtensionIntoTheLigamentumLatumUteri = false;
    this.isPerifocalEdema = false;
    this.isAbnormalVesselCollection = false;
    this.isCentralNidus = false;
    this.isLobulated = false;
    this.isFluidLevel = false;
    this.isWideningOfTheInternalUterineOstium = false;
    this.isIntactRingOfTheCervicalStroma = false;
    this.figoClassificationLocation1 = 'None';
    this.figoClassificationLocation2 = 'None';
    this.degenerationType2 = DegenerationTypeEnum.None;
    this.isTorsion1 = false;
    this.isTorsion2 = false;
    this.isFocalSignalVoidIntrauterine = false;
    this.isMarkedUterineVessels = false;
    this.isIntactCervicalStromaRing = false;
    this.isDetailsCapsule = false;
    this.isAlteredInternalStructureCapsule = false;
    this.isCorpusUteri = false;
    this.isPelvisWall = false;
    this.is1BMacroinvasiveLesion1 = false;
    this.is1BMacroinvasiveLesion2 = false;
    this.isFocalSignalVoidsInTheCervicalCanal = false;
    this.isMarkedCervicalVessels = false;
    this.isFistula = false;
    this.isVesicovaginal = false;
    this.isRectovaginal = false;
    this.isParavaginalSoftTissue = false;
    this.isPelvicWall = false;
    this.isPeritoneum = false;
    this.isBartholinitis1 = false;
    this.isBartholinitis2 = false;
    this.isFluidDebrisLevel = false;
    this.isVaginalDisplacement = false;
    this.isPerineum = false;
    this.isUrethra = false;
    this.isAnalSphincter = false;
    this.isAnusOrRectum = false;
    this.isUrethralLeiomyoma1 = false;
    this.isUrethralLeiomyoma2 = false;
    this.isUrethralMetastasis1 = false;
    this.isUrethralMetastasis2 = false;
    this.isSoftTissueSwelling = false;
    this.isFourniersGangrene = false;
    this.isVenousThrombosis = false;
    this.isT2wSignalIncreasePerivascular = false;
    this.isCystOfSkenesGlands = false;
    this.isUrethralDiverticula = false;
    this.isHypointenseCapsule = false;
    this.isSpicula = false;
    this.isNodular = false;
    this.isLigamentousThickening = false;
    this.isMushroomSign = false;
    this.isShading = false;
    this.isMultifocalSignalIncreaseT1w = false;
    this.isMultifocalSignalIncreaseT2w = false;
    this.isCystic = false;
    this.isComplex = false;
    this.isDetectionOfBloodClots = false;
    this.isInternalBleeding = false;
    this.depthOfInfiltrationType = DepthOfInfiltrationTypeEnum.None;
    this.subperitonealInfiltrationType = SubperitonealInfiltrationTypeEnum.None;
    this.isPerifocalFatTissueObliteration = false;
    this.isPerifocalTighteningOrShortening = false;
    this.complicationsType = ComplicationsTypeEnum.None;
    this.isAtTheLevelOfTheUreterostium = false;
    this.isPrestenoticDilatation = false;
    this.isPoststenoticCollapse = false;
    this.isPosteriorDisplacementOfTheUterus = false;
    this.isPosteriorDisplacementOfTheOvaries = false;
    this.isKissingOvaries = false;
    this.isCranialDisplacementOfThePosteriorFornixVaginae = false;
    this.isDisplacementOfIntestinalLoops = false;
    this.isMoreThan1LesionSamePathology = false;
  }
}
