import { FindingBase } from '@models/shared/finding/finding.base';
import { SellarRegionFindingTypeEnum } from '@enums/headMRT/sellar-region/sellar-region-finding-type.enum';
import { DescriptionTypeEnum } from '@enums/shared/description-type.enum';
import { SellarRegionDiagnosisTypeEnum } from '@enums/headMRT/sellar-region/sellar-region-diagnosis-type.enum';
import { RelationPituitaryGlandTypeEnum } from '@enums/headMRT/sellar-region/relation-pituitar-gland-type.enum';
import { SideTypeEnum } from '@enums/headMRT/common/side-type.enum';
import { MarginTypeEnum } from '@enums/headMRT/common/margin-type.enum';
import { HomogeneityTypeEnum } from '@enums/headMRT/common/homogeneity-type.enum';
import { ShapeTypeEnum } from '@enums/headMRT/sellar-region/shape-type.enum';
import { SignalVoidTypeEnum } from '@enums/headMRT/common/signal-void-type.enum';
import { ContrastEnhancementQuantitativeTypeEnum } from '@enums/headMRT/common/contrast-enhancement-quantitative-type.enum';
import { ContrastEnhancementDistributionTypeEnum } from '@enums/headMRT/common/contrast-enhancement-distribution-type.enum';

export class SellarRegionFindingBaseUiModel extends FindingBase {
  findingType: SellarRegionFindingTypeEnum;
  descriptionType: DescriptionTypeEnum;

  sellarRegionDiagnosisLocalizationType: SellarRegionDiagnosisTypeEnum;
  relationToThePituitaryGlandType: RelationPituitaryGlandTypeEnum;
  isNeurohypophysis: boolean;
  isAdenohypophysis: boolean;
  isPituitaryStalk: boolean;
  sideType: SideTypeEnum;
  isCavernousSinus: boolean;
  isOpticNerveI: boolean;
  isOpticChiasm: boolean;
  isOlfactoryNerveII: boolean;
  isOculomotorNerveIII: boolean;
  isTrochlearNerveIV: boolean;
  isAbducensNerveVI: boolean;
  isInternalCarotidArtery: boolean;
  isDuraMaterMeningen: boolean;
  isSphenoidSinus: boolean;
  isNasopharynx: boolean;
  marginType: MarginTypeEnum;
  homogeneityType: HomogeneityTypeEnum;
  shapeType: ShapeTypeEnum;
  t1wSignalType: number;
  t2wSignalType: number;
  flairSignalType: number;
  isSignalVoid: boolean;
  signalVoidType: SignalVoidTypeEnum;
  isDiffusionRestriction: boolean;
  isHemorrhage: boolean;
  isNecrosis: boolean;
  isCalcification: boolean;
  isFat: boolean;
  isCysts: boolean;
  isCapsule: boolean;
  isSepta: boolean;
  isSignalVoids: boolean;
  isFluidLevel: boolean;
  isToothBoneFormation: boolean;
  isDisplacement: boolean;
  isInfiltration: boolean;
  isHydrocephalus: boolean;
  isPerifocalEdema: boolean;
  isBonyRemodeling: boolean;
  isDuraTailSign: boolean;
  isContactWithCarotidArtery: boolean;
  carotidArterySideType: SideTypeEnum;
  isDisplacementOfPituitaryStalk: boolean;
  pituitaryStalkSideType: SideTypeEnum;
  isInfiltrationIntoCavernousSinus: boolean;
  isSuspicionOfInfiltration: boolean;
  isExtensionToSuprasellar: boolean;
  isAffectionOpticChiasm: boolean;
  contrastQuantitativeType: ContrastEnhancementQuantitativeTypeEnum;
  contrastEnhancementHomogeneityType: HomogeneityTypeEnum;
  isDetectionOfLesion: boolean;
  contrastDistributionType: ContrastEnhancementDistributionTypeEnum;

  sellarRegionDiagnosis1Type: SellarRegionDiagnosisTypeEnum;
  sellarRegionDiagnosis2Type: SellarRegionDiagnosisTypeEnum;
  sellarRegionDiagnosis3Type: SellarRegionDiagnosisTypeEnum;
  isSuspicionOf: boolean;
  isSubordinate: boolean;
  is1LesionOfTheSameEntity: boolean;

  constructor() {
    super();
    this.findingType = SellarRegionFindingTypeEnum.None;
    this.descriptionType = DescriptionTypeEnum.None;

    this.sellarRegionDiagnosisLocalizationType = SellarRegionDiagnosisTypeEnum.None;
    this.relationToThePituitaryGlandType = RelationPituitaryGlandTypeEnum.None;
    this.isNeurohypophysis = false;
    this.isAdenohypophysis = false;
    this.isPituitaryStalk = false;
    this.sideType = SideTypeEnum.None;
    this.isCavernousSinus = false;
    this.isOpticNerveI = false;
    this.isOpticChiasm = false;
    this.isOlfactoryNerveII = false;
    this.isOculomotorNerveIII = false;
    this.isTrochlearNerveIV = false;
    this.isAbducensNerveVI = false;
    this.isInternalCarotidArtery = false;
    this.isDuraMaterMeningen = false;
    this.isSphenoidSinus = false;
    this.isNasopharynx = false;
    this.marginType = MarginTypeEnum.None;
    this.homogeneityType = HomogeneityTypeEnum.None;
    this.shapeType = ShapeTypeEnum.None;
    this.t1wSignalType = 0;
    this.t2wSignalType = 0;
    this.flairSignalType = 0;
    this.isSignalVoid = false;
    this.signalVoidType = SignalVoidTypeEnum.None;
    this.isDiffusionRestriction = false;
    this.isHemorrhage = false;
    this.isNecrosis = false;
    this.isCalcification = false;
    this.isFat = false;
    this.isCysts = false;
    this.isCapsule = false;
    this.isSepta = false;
    this.isSignalVoids = false;
    this.isFluidLevel = false;
    this.isToothBoneFormation = false;
    this.isDisplacement = false;
    this.isInfiltration = false;
    this.isHydrocephalus = false;
    this.isPerifocalEdema = false;
    this.isBonyRemodeling = false;
    this.isDuraTailSign = false;
    this.isContactWithCarotidArtery = false;
    this.carotidArterySideType = SideTypeEnum.None;
    this.isDisplacementOfPituitaryStalk = false;
    this.pituitaryStalkSideType = SideTypeEnum.None;
    this.isInfiltrationIntoCavernousSinus = false;
    this.isSuspicionOfInfiltration = false;
    this.isExtensionToSuprasellar = false;
    this.isAffectionOpticChiasm = false;
    this.contrastQuantitativeType = ContrastEnhancementQuantitativeTypeEnum.None;
    this.contrastEnhancementHomogeneityType = HomogeneityTypeEnum.None;
    this.isDetectionOfLesion = false;
    this.contrastDistributionType = ContrastEnhancementDistributionTypeEnum.None;
    this.sellarRegionDiagnosis1Type = SellarRegionDiagnosisTypeEnum.None;
    this.sellarRegionDiagnosis2Type = SellarRegionDiagnosisTypeEnum.None;
    this.sellarRegionDiagnosis3Type = SellarRegionDiagnosisTypeEnum.None;
    this.isSuspicionOf = false;
    this.isSubordinate = false;
    this.is1LesionOfTheSameEntity = false;
  }
}
