export enum DifferentialDiagnosisTypeEnum {
  None = 'None',
  Lipoma = 'Lipoma',
  AdenomaPolyp = 'AdenomaPolyp',
  Endometriosis = 'Endometriosis',
  EnlargedNonInflamedAppendix = 'EnlargedNonInflamedAppendix',
  SigmoidColonCancer = 'SigmoidColonCancer',
  Lymphoma = 'Lymphoma',
  Carcinoid = 'Carcinoid',
  Metastasis = 'Metastasis',
  DiverticularSigmoiditis = 'DiverticularSigmoiditis',
  Sigmoiditis = 'Sigmoiditis',
  Mucocele = 'Mucocele',
  Diverticulitis = 'Diverticulitis',
  AcuteEpiploicAppendagitis = 'AcuteEpiploicAppendagitis',
  Colitis = 'Colitis',
  Ileitis = 'Ileitis',
  ChronicInflammatoryBowelDisease = 'ChronicInflammatoryBowelDisease',
  OmentalInfarction = 'OmentalInfarction',
  MalignantLesionNotFurtherSpecified = 'MalignantLesionNotFurtherSpecified',
  UlcerativeColitis = 'UlcerativeColitis',
  CrohnsDisease = 'CrohnsDisease',
  PseudomembranousColitis = 'PseudomembranousColitis',
  BenignSigmoidTumorNotFurtherSpecified = 'BenignSigmoidTumorNotFurtherSpecified',
  MalignantSigmoidTumorNotFurtherSpecified = 'MalignantSigmoidTumorNotFurtherSpecified',
  SigmoidTumorDignityUnclear = 'SigmoidTumorDignityUnclear',
  SigmoidTumorInflammatory = 'SigmoidTumorInflammatory'
}
