export enum FractureFormSubTypeEnum {
  None = 'None',
  LateralEpicondyle = 'LateralEpicondyle',
  MedialEpcondyle = 'MedialEpcondyle',
  SpiralFracture = 'SpiralFracture',
  ObliqueFracture = 'ObliqueFracture',
  TransverseFracture = 'TransverseFracture',
  WithAnIntactSupracondylarWedge = 'WithAnIntactSupracondylarWedge',
  WithAFragmentedSupracondylarWedge = 'WithAFragmentedSupracondylarWedge',
  ComminutedFractureMetaphyseal = 'ComminutedFractureMetaphyseal',
  Transtrochlear = 'Transtrochlear',
  CapitulumHumeri = 'CapitulumHumeri',
  FragmentedTranstrochlearFracture = 'FragmentedTranstrochlearFracture',
  TranstrochlearSimpleThroughTrochlearSulcus = 'TranstrochlearSimpleThroughTrochlearSulcus',
  TranstrochlearSimpleThroughMedialArticularSurface = 'TranstrochlearSimpleThroughMedialArticularSurface',
  Capitulum = 'Capitulum',
  Trochlea = 'Trochlea',
  CapitulumAndTrochlea = 'CapitulumAndTrochlea',
  AboveTheTranscondylarAxis = 'AboveTheTranscondylarAxis',
  BelowOrThroughTranscondylarAxis = 'BelowOrThroughTranscondylarAxis',
  ComplexMultifragmentary = 'ComplexMultifragmentary',
  MetaphysealSimple = 'MetaphysealSimple',
  WithMetaphysealFractureWedge = 'WithMetaphysealFractureWedge',
  MetaphysealComplexOrMultiFragmentary = 'MetaphysealComplexOrMultiFragmentary'
}
