using System;

namespace RadioReport.FeetMRT.Domain.Enums
{
    [Flags]
    public enum ThreeDimensionalLocalizations : ulong
    {
        None = 0uL,
        Tibia = 1uL,
        Fibula = 1uL << 1,
        Malleoli = 1uL << 2,
        Talus = 1uL << 3,
        PosteromedialTalus = 1uL << 4,
        AnterolateralTalus = 1uL << 5,
        Calcaneus = 1uL << 6,
        OsNaviculare = 1uL << 7,
        OsCuneiformeMediale = 1uL << 8,
        OsCuneiformeIntermedium =  1uL << 9,
        OsCuneiformeLaterale = 1uL << 10,
        OsCuboideum = 1uL << 11,
        OsMetatarsale1 = 1uL << 12,
        OsMetatarsale2 = 1uL << 13,
        OsMetatarsale3 = 1uL << 14,
        OsMetatarsale4 = 1uL << 15,
        OsMetatarsale5 = 1uL << 16,
        OsMetatarsale5Proximal = 1uL << 17,
        OsMetatarsale5Distal = 1uL << 18,
        ProximalPhalanxD1 = 1uL << 19,
        ProximalPhalanxD2 = 1uL << 20,
        ProximalPhalanxD3 = 1uL << 21,
        ProximalPhalanxD4 = 1uL << 22,
        ProximalPhalanxD5 = 1uL << 23,
        MiddlePhalanxD2 = 1uL << 24,
        MiddlePhalanxD3 = 1uL << 25,
        MiddlePhalanxD4 = 1uL << 26,
        MiddlePhalanxD5 = 1uL << 27,
        DistalPhalanxD1 = 1uL << 28,
        DistalPhalanxD2 = 1uL << 29,
        DistalPhalanxD3 = 1uL << 30,
        DistalPhalanxD4 = 1uL << 31,
        DistalPhalanxD5 = 1uL << 32,
        ComplexOrMultipleBones = 1uL << 33,
        TalocruralJoint = 1uL << 34,
        SubtalarJoint = 1uL << 35,
        ArticulatioCalcaneocuboidea = 1uL << 36,
        TalonavicularJoint = 1uL << 37,
        TarsometatarsalJoints = 1uL << 38,
        MetatarsophalangealJointD1 = 1uL << 39,
        MetatarsophalangealJointD2 = 1uL << 40,
        MetatarsophalangealJointD3 = 1uL << 41,
        MetatarsophalangealJointD4 = 1uL << 42,
        MetatarsophalangealJointD5 = 1uL << 43,
        ProximalInterphalangealJointD1 = 1uL << 44,
        ProximalInterphalangealJointD2 = 1uL << 45,
        ProximalInterphalangealJointD3 = 1uL << 46,
        ProximalInterphalangealJointD4 = 1uL << 47,
        ProximalInterphalangealJointD5 = 1uL << 48,
        DistalInterphalangealJointD2 = 1uL << 49,
        DistalInterphalangealJointD3 = 1uL << 50,
        DistalInterphalangealJointD4 = 1uL << 51,
        DistalInterphalangealJointD5 = 1uL << 52
    }
}
