export enum FractureTypeEnum {
  None = 'None',
  MedialEndSegment15_1 = 'MedialEndSegment15_1',
  DiaphysealSegment15_2 = 'DiaphysealSegment15_2',
  LateralEndSegment15_3 = 'LateralEndSegment15_3',
  NotFurtherSpecified15 = 'NotFurtherSpecified15',
  Process14A = 'Process14A',
  Body14B = 'Body14B',
  GlenoidFossa14F = 'GlenoidFossa14F',
  NotFurtherSpecified14 = 'NotFurtherSpecified14',
  PosteriorSegment16_1 = 'PosteriorSegment16_1',
  Shaft16_2 = 'Shaft16_2',
  AnteriorEndSegment16_3 = 'AnteriorEndSegment16_3',
  NotFurtherSpecified16 = 'NotFurtherSpecified16',
  SternalManubrium16_3_1 = 'SternalManubrium16_3_1',
  SternalBody16_3_2 = 'SternalBody16_3_2',
  XiphoidProcess16_3_3 = 'XiphoidProcess16_3_3',
  NotFurtherSpecified16_3 = 'NotFurtherSpecified16_3',
  CompressionInjuryA = 'CompressionInjuryA',
  TensionBandInjuryB = 'TensionBandInjuryB',
  TranslationalInjuryC = 'TranslationalInjuryC',
  NotFurtherDefined = 'NotFurtherDefined',
  PathologyNoFracture = 'PathologyNoFracture'
}
