import { DifferentialDiagnosisPenisTraumaTypeEnum } from '@enums/pelvisMRT/male-sex/differential-diagnosis-penis-trauma-type.enum';
import { DifferentialDiagnosisScrotumInfectionInflammationTypeEnum } from '@enums/pelvisMRT/male-sex/differential-diagnosis-scrotum-infection-inflammation-type.enum';
import { DifferentialDiagnosisScrotumMassTypeEnum } from '@enums/pelvisMRT/male-sex/differential-diagnosis-scrotum-mass-type.enum';
import { DifferentialDiagnosisScrotumTraumaTypeEnum } from '@enums/pelvisMRT/male-sex/differential-diagnosis-scrotum-trauma-type.enum';
import { ExpansionTypeEnum } from '@enums/pelvisMRT/male-sex/expansion-type.enum';
import { FormTypeEnum } from '@enums/pelvisMRT/male-sex/form-type.enum';
import { HomogeneityTypeEnum } from '@enums/pelvisMRT/male-sex/homogeneity-type.enum';
import { LocalizationOfTheNondescendedTypeEnum } from '@enums/pelvisMRT/male-sex/localization-of-the-nondescended-type.enum';
import { SeminalVesicleChannelTypeEnum } from '@enums/pelvisMRT/male-sex/seminal-vesicle-channel-type.enum';
import { SeptationsTypeEnum } from '@enums/pelvisMRT/male-sex/septations-type.enum';
import { SignalLossFlowVoidTypeEnum } from '@enums/pelvisMRT/male-sex/signal-loss-flow-void-type.enum';
import { TesticlesTypeEnum } from '@enums/pelvisMRT/male-sex/testicles-type.enum';
import { TunicaAlbugineaTypeEnum } from '@enums/pelvisMRT/male-sex/tunica-albuginea-type.enum';
import { CMEnhancementTypeEnum } from '@enums/shared/cm-enhancement-type.enum';
import { MaleSexFindingBaseApiModel } from './male-sex-finding-base-api.model';

export class MaleSexFindingApiModel extends MaleSexFindingBaseApiModel {
  descriptionType: string;
  isHematoma: boolean;
  isDiggingUp: boolean;
  isScrotal: boolean;
  homogeneousType: string;
  isDistension: boolean;
  isAirInclusions: boolean;
  isCircumscribedFluidCollection: boolean;
  isCircumscribedFluidAccumulation: boolean;
  isDilatationOfSeminalVesicularTubules: boolean;
  isAbscess: boolean;
  expansionInMm: number;
  isFascialThickening: boolean;
  sizeInMm: number;
  isHomogeneousEpididymis: boolean;
  isHeterogeneousEpididymis: boolean;
  epididymisSignalT2wSliderType: string;
  testiclesSignalT2wSliderType: string;
  surroundingSoftTissueSignalT1wSliderType: string;
  surroundingSoftTissueSignalT2wSliderType: string;
  expansionType: ExpansionTypeEnum;
  noKMEnhancementType: string;
  kmEnhancementType: string;
  testiclesCMEnhancement: CMEnhancementTypeEnum;
  t2wSignalBoostType: string;
  penisInfectionKMEnhancementType: string;
  epididymisCMEnhancement: string;
  surroundingSoftTissueCMEnhancement: CMEnhancementTypeEnum;
  cmEnhancementType: CMEnhancementTypeEnum;
  cmEnhancementFocalPlaquesType: CMEnhancementTypeEnum;
  testiclesKMEnhancement: string;
  epididymisKMEnhancement: string;
  surroundingSoftTissueKMEnhancementType: string;
  differentialDiagnosisInfection01Type: string;
  differentialDiagnosisInfection02Type: string;
  t2WSignalType: string;
  testiclesSignalType: string;
  epididymisSignalType: string;
  epididymisHomogeneityType: string;
  scrotumInfectionInflammationT2wSignalBoostType: string;
  isHeterogeneous: boolean;
  isHomogeneous: boolean;
  tunicaAlbugineaType: TunicaAlbugineaTypeEnum;
  isFocalT2wCorpusCavernosumLeft: boolean;
  isFocalT2wCorpusCavernosumRight: boolean;
  isCorporaCavernosa: boolean;
  isSoftTissueEdema: boolean;
  isScrotalHematocele: boolean;
  differentialDiagnosisPenisTraumaType: DifferentialDiagnosisPenisTraumaTypeEnum;
  isSuspicionOf: boolean;
  signalBehaviourT2wType: string;
  isScrotalExpansion: boolean;
  isFocalPlaquesOfTheTunicaAlbuginea: boolean;
  isT1wHypointense: boolean;
  isT2wHypointense: boolean;
  isLocalizationCorpusCavernosumLeft: boolean;
  isLocalizationCorpusCavernosumRight: boolean;
  isLocalizationCorpusSpongiosum: boolean;
  isFocalSignalVoids: boolean;
  isFluidAroundProsthesis: boolean;
  isProsthesisDefect: boolean;
  isHeterogeneousTesticles: boolean;
  isHeterogeneousSurroundingSoftTissue: boolean;
  isHomogeneousTesticles: boolean;
  isHomogeneousSurroundingSoftTissue: boolean;
  isVenousInfarction: boolean;
  isPyrocele: boolean;
  isDiscontinuityOfTheTunicaAlbuginea: boolean;
  isAirFluidLevel: boolean;
  isCutaneousFistula: boolean;
  isSinusTract: boolean;
  isEpididymitis: boolean;
  isEpididymitisFournierGangrene: boolean;
  isFournierGangrene: boolean;
  isEpididymoorchitis: boolean;
  differentialDiagnosisScrotumInfectionInflammationType: DifferentialDiagnosisScrotumInfectionInflammationTypeEnum;
  exampleThicknessInMm: number;
  differentialDiagnosisMainFeatures01Type: string;
  isCryptorchidismLeft: boolean;
  isCryptorchidismRight: boolean;
  isTesticularAtrophyRight: boolean;
  isTesticularAtrophyLeft: boolean;
  localizationOfTheNondescendedType: LocalizationOfTheNondescendedTypeEnum;
  testiclesType: TesticlesTypeEnum;
  isDiscontinuityOfTheTunicaAlbugineaLeft: boolean;
  isDiscontinuityOfTheTunicaAlbugineaRight: boolean;
  isHematocele: boolean;
  isNonDisplacing: boolean;
  differentialDiagnosisScrotumTraumaType: DifferentialDiagnosisScrotumTraumaTypeEnum;
  differentialDiagnosisScrotumMassType: DifferentialDiagnosisScrotumMassTypeEnum;
  reductionTypeTw2: string;
  reductionTypeTw1: string;
  isSeptations: boolean;
  septationsType: SeptationsTypeEnum;
  isFluidLevel: boolean;
  isCorpusCavernosumLeft: boolean;
  isCorpusCavernosumRight: boolean;
  isCorpusSpongiosum: boolean;
  isMarginalKMEnhancement: boolean;
  t1wSignalType: string;
  t2wSignalType: string;
  seminalVesiclesMassSignalT2wSliderType: string;
  differentialDiagnosisSeminalVesiclesMassMainFeatures01Type: string;
  t2wSignalSeminalVesiclesMassType: string;
  isT2wHomogeneousSurfaceSeminalVesiclesMass: boolean;
  isT2wStripedSeminalVesiclesMass: boolean;
  isTranscribedLiquid: boolean;
  isT1wSignalBoost: boolean;
  isCysticNecrotic: boolean;
  isVesicoChamberAccumulation: boolean;
  cmEnhancementSeminalVesiclesMassType: CMEnhancementTypeEnum;
  homogeneitySeminalVesiclesMassType: HomogeneityTypeEnum;
  isProstate: boolean;
  isUrinaryBladder: boolean;
  isRectum: boolean;
  differentialDiagnosisSeminalVesiclesMass01Type: string;
  differentialDiagnosisSeminalVesiclesMass02Type: string;
  seminalVesiclesInfectionInflammationCmEnhancementType: CMEnhancementTypeEnum;
  isDiffuse: boolean;
  isParietal: boolean;
  isSeptal: boolean;
  seminalVesicleChannelType: SeminalVesicleChannelTypeEnum;
  seminalVesiclesInfectionInflammation: number;
  isSeminalVesiculitis: boolean;
  isAbsconding: boolean;
  isDiffuseWallThickening: boolean;

  constructor() {
    super();
    this.descriptionType = 'None';
    this.isHematoma = false;
    this.isDiggingUp = false;
    this.isScrotal = false;
    this.homogeneousType = 'None';
    this.isAirInclusions = false;
    this.isCircumscribedFluidCollection = false;
    this.isCircumscribedFluidAccumulation = false;
    this.isDilatationOfSeminalVesicularTubules = false;
    this.isAbscess = false;
    this.expansionInMm = null;
    this.isFascialThickening = false;
    this.sizeInMm = null;

    this.epididymisSignalT2wSliderType = 'None';
    this.testiclesSignalT2wSliderType = 'None';
    this.surroundingSoftTissueSignalT1wSliderType = 'None';
    this.surroundingSoftTissueSignalT2wSliderType = 'None';
    this.expansionType = ExpansionTypeEnum.None;
    this.isHomogeneous = false;
    this.isHeterogeneous = false;
    this.isHomogeneousEpididymis = false;
    this.isHeterogeneousEpididymis = false;
    this.differentialDiagnosisScrotumInfectionInflammationType = DifferentialDiagnosisScrotumInfectionInflammationTypeEnum.None;
    this.noKMEnhancementType = 'None';
    this.homogeneousType = 'None';
    this.testiclesCMEnhancement = CMEnhancementTypeEnum.None;
    this.kmEnhancementType = 'None';
    this.t2wSignalBoostType = 'None';
    this.penisInfectionKMEnhancementType = 'None';
    this.epididymisCMEnhancement = 'None';
    this.surroundingSoftTissueCMEnhancement = CMEnhancementTypeEnum.None;
    this.testiclesKMEnhancement = 'None';
    this.cmEnhancementType = CMEnhancementTypeEnum.None;
    this.cmEnhancementFocalPlaquesType = CMEnhancementTypeEnum.None;
    this.epididymisKMEnhancement = 'None';
    this.surroundingSoftTissueKMEnhancementType = 'None';
    this.differentialDiagnosisInfection01Type = 'None';
    this.differentialDiagnosisInfection02Type = 'None';
    this.t2WSignalType = 'None';
    this.testiclesSignalType = 'None';
    this.epididymisSignalType = 'None';
    this.epididymisHomogeneityType = 'None';
    this.scrotumInfectionInflammationT2wSignalBoostType = 'None';
    this.isHeterogeneous = false;
    this.isHomogeneous = false;
    this.tunicaAlbugineaType = TunicaAlbugineaTypeEnum.None;
    this.isFocalT2wCorpusCavernosumLeft = false;
    this.isFocalT2wCorpusCavernosumRight = false;
    this.isCorporaCavernosa = false;
    this.isSoftTissueEdema = false;
    this.isHematoma = false;
    this.isScrotalHematocele = false;
    this.differentialDiagnosisPenisTraumaType = DifferentialDiagnosisPenisTraumaTypeEnum.None;
    this.isSuspicionOf = false;
    this.isDistension = false;
    this.signalBehaviourT2wType = 'None';
    this.isAirInclusions = false;
    this.isAbscess = false;
    this.isScrotalExpansion = false;
    this.isFocalPlaquesOfTheTunicaAlbuginea = false;
    this.isT1wHypointense = false;
    this.isT2wHypointense = false;
    this.isLocalizationCorpusCavernosumLeft = false;
    this.isLocalizationCorpusCavernosumRight = false;
    this.isLocalizationCorpusSpongiosum = false;
    this.isFocalSignalVoids = false;
    this.isFluidAroundProsthesis = false;
    this.isProsthesisDefect = false;
    this.isHeterogeneousTesticles = false;
    this.isHeterogeneousSurroundingSoftTissue = false;
    this.isHomogeneousTesticles = false;
    this.isHomogeneousSurroundingSoftTissue = false;
    this.isVenousInfarction = false;
    this.isPyrocele = false;
    this.isDiscontinuityOfTheTunicaAlbuginea = false;
    this.isAirFluidLevel = false;
    this.isCutaneousFistula = false;
    this.isSinusTract = false;
    this.isEpididymitis = false;
    this.isEpididymitisFournierGangrene = false;
    this.isFournierGangrene = false;
    this.isEpididymoorchitis = false;
    this.expansionInMm = null;
    this.exampleThicknessInMm = null;
    this.differentialDiagnosisMainFeatures01Type = 'None';
    this.formType = FormTypeEnum.None;
    this.t2wSignalType = 'None';
    this.t1wSignalType = 'None';
    this.isSignalLossFlowVoid = false;
    this.signalLossFlowVoidType = SignalLossFlowVoidTypeEnum.None;
    this.isMarginalCMEnhancement = false;
    this.isDiffusionRestriction = false;
    this.isCorpusCavernosumLeft = false;
    this.isCorpusCavernosumRight = false;
    this.isCorpusSpongiosum = false;
    this.isCryptorchidismLeft = false;
    this.isCryptorchidismRight = false;
    this.isTesticularAtrophyLeft = false;
    this.isTesticularAtrophyRight = false;
    this.localizationOfTheNondescendedType = LocalizationOfTheNondescendedTypeEnum.None;
    this.testiclesType = TesticlesTypeEnum.None;
    this.isDiscontinuityOfTheTunicaAlbugineaLeft = false;
    this.isDiscontinuityOfTheTunicaAlbugineaRight = false;
    this.isHematocele = false;
    this.isNonDisplacing = false;
    this.differentialDiagnosisScrotumTraumaType = DifferentialDiagnosisScrotumTraumaTypeEnum.None;
    this.differentialDiagnosisScrotumMassType = DifferentialDiagnosisScrotumMassTypeEnum.None;
    this.reductionTypeTw2 = 'None';
    this.reductionTypeTw1 = 'None';
    this.isSeptations = false;
    this.septationsType = SeptationsTypeEnum.None;
    this.isFluidLevel = false;
    this.isMarginalKMEnhancement = false;
    this.t1wSignalType = 'None';
    this.t2wSignalType = 'None';
    this.seminalVesiclesMassSignalT2wSliderType = 'None';
    this.differentialDiagnosisSeminalVesiclesMassMainFeatures01Type = 'None';
    this.t2wSignalSeminalVesiclesMassType = 'None';
    this.isT2wHomogeneousSurfaceSeminalVesiclesMass = false;
    this.isT2wStripedSeminalVesiclesMass = false;
    this.isTranscribedLiquid = false;
    this.isT1wSignalBoost = false;
    this.isCysticNecrotic = false;
    this.isVesicoChamberAccumulation = false;
    this.cmEnhancementSeminalVesiclesMassType = CMEnhancementTypeEnum.None;
    this.homogeneitySeminalVesiclesMassType = HomogeneityTypeEnum.None;
    this.isProstate = false;
    this.isUrinaryBladder = false;
    this.isRectum = false;
    this.differentialDiagnosisSeminalVesiclesMass01Type = 'None';
    this.differentialDiagnosisSeminalVesiclesMass02Type = 'None';
    this.seminalVesiclesInfectionInflammationCmEnhancementType = CMEnhancementTypeEnum.None;
    this.isDiffuse = false;
    this.isParietal = false;
    this.isSeptal = false;
    this.seminalVesicleChannelType = SeminalVesicleChannelTypeEnum.None;
    this.seminalVesiclesInfectionInflammation = null;
    this.isSeminalVesiculitis = false;
    this.isAbsconding = false;
    this.isDiffuseWallThickening = false;
  }
}
